# 12 CatBoost Hyperparameter Optimisierung Optuna

## Import

In [1]:
import time

import numpy as np
import pandas as pd

from sklearn.datasets import fetch_openml
from sklearn.metrics import roc_auc_score

import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner

from optuna_integration import CatBoostPruningCallback

from catboost import CatBoostClassifier

import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
mpl.style.use("seaborn-v0_8-colorblind")
RANDOM_STATE = 42

## Dataframe

In [3]:
df_raw = fetch_openml(data_id=42742, as_frame=True).frame

In [4]:
feat_cols = [col for col in df_raw.columns if col not in ("target",)]
cat_cols = [col for col in feat_cols if col.endswith("_cat")]
bin_cols = [col for col in feat_cols if col.endswith("_bin")]
num_cols = [col for col in feat_cols if col not in cat_cols and col not in bin_cols]

for col in cat_cols:
    df_raw[col] = df_raw[col].astype("category")

for col in bin_cols:
    if df_raw[col].isna().sum() == 0:
        df_raw[col] = df_raw[col].astype(int).astype("bool")
    else:
        df_raw[col] = df_raw[col].astype("Int8")

for col in num_cols:
    df_raw[col] = df_raw[col].astype("float32")

df_raw["target"] = df_raw["target"].astype(int).astype("bool")

idx_train = np.load("../../../data/processed/train_idx.npy")
idx_val = np.load("../../../data/processed/val_idx.npy")
idx_test = np.load("../../../data/processed/test_idx.npy")

df_train = df_raw.iloc[idx_train]
df_val = df_raw.iloc[idx_val]
df_test = df_raw.iloc[idx_test]

x_train, y_train = df_train[feat_cols], df_train["target"]
x_val, y_val = df_val[feat_cols], df_val["target"]
x_test, y_test = df_test[feat_cols], df_test["target"]
x_full, y_full = df_raw[feat_cols], df_raw["target"]

pd.Series(
    {
        "train": [len(df_train), len(x_train), len(y_train)],
        "val": [len(df_val), len(x_val), len(y_val)],
        "test": [len(df_test), len(x_test), len(y_test)],
        "full": [len(df_raw), len(x_full), len(y_full)]
    }
)

train    [476168, 476168, 476168]
val         [59522, 59522, 59522]
test        [59522, 59522, 59522]
full     [595212, 595212, 595212]
dtype: object

## Hilfsvariablen

In [5]:
calc_cols = [c for c in feat_cols if c.startswith("ps_calc_")]

mv_cols = ["ps_car_03_cat", "ps_car_05_cat", "ps_reg_03", "ps_car_14"]

num_cols_no_calc = [c for c in num_cols if c not in calc_cols]
bin_cols_no_calc = [c for c in bin_cols if c not in calc_cols]
feat_cols_no_calc = [c for c in feat_cols if c not in calc_cols]

high_kard_cols = ["ps_car_11_cat"]
low_kard_cols = [c for c in cat_cols if c not in high_kard_cols]

In [6]:
def eval_modell(mod_idx, model, x_train, y_train, x_val, y_val, train_time, best_iter=None):
    """AUC auf Train und Val"""
    auc_train = roc_auc_score(y_train, model.predict_proba(x_train)[:, 1])
    auc_val = roc_auc_score(y_val, model.predict_proba(x_val)[:, 1])
    return {
        "model_idx": mod_idx,
        "auc_train": auc_train,
        "auc_val": auc_val,
        "gini": 2 * auc_val - 1,
        "delta_auc": auc_train - auc_val,
        "best_iter": best_iter,
        "trainingszeit": train_time
    }

In [7]:
def mv_for_cb(df, fill_var="missing"):
    """df copy mit ersetzten nans"""
    outs = df.copy()
    for col in outs.columns:
        if outs[col].dtype.name == "category":
            if fill_var not in outs[col].cat.categories:
                outs[col] = outs[col].cat.add_categories([fill_var])
            outs[col] = outs[col].fillna(fill_var)
    return outs

In [8]:
x_train_cb = mv_for_cb(x_train)
x_val_cb = mv_for_cb(x_val)
x_test_cb = mv_for_cb(x_test)
x_full_cb = mv_for_cb(x_full)

x_train_no_calc_cb = x_train_cb[feat_cols_no_calc]
x_val_no_calc_cb = x_val_cb[feat_cols_no_calc]
x_test_no_calc_cb = x_test_cb[feat_cols_no_calc]
x_full_no_calc_cb = x_full_cb[feat_cols_no_calc]

pd.Series(
    {
        "train": [len(x_train_cb), len(x_train_no_calc_cb)],
        "val": [len(x_val_cb), len(x_val_no_calc_cb)],
        "test": [len(x_test_cb), len(x_test_no_calc_cb)],
        "full": [len(x_full_cb), len(x_full_no_calc_cb)]
    }
)

train    [476168, 476168]
val        [59522, 59522]
test       [59522, 59522]
full     [595212, 595212]
dtype: object

In [9]:
def subsample(x_set, y_set, anteil, random_state=RANDOM_STATE):
    """Subsample erzeugen"""
    if anteil >= 1.0:
        return x_set, y_set
    rng = np.random.default_rng(random_state)
    n = int(len(x_set) * anteil)
    idx_sub = rng.permutation(len(x_set))[:n]
    return x_set.iloc[idx_sub], y_set.iloc[idx_sub]

In [10]:
x_sub_75, y_sub_75 = subsample(x_train_cb, y_train, 0.75)
x_sub_no_calc_75, y_sub_no_calc_75 = subsample(x_train_no_calc_cb, y_train, 0.75)

pd.Series(
    {
        "sub": len(x_sub_75),
        "sub no calc": len(x_sub_no_calc_75),
        "anteil target": y_sub_75.mean()
    }
)

sub              357126.0000
sub no calc      357126.0000
anteil target         0.0365
dtype: float64

## Optuna Hilfe

## Suchräume

|Paramerter|Bereich|
|---|---|
|learning rate|0.01-0.3|
|depth|4-10|
|l2_leaf_reg|1-30|
|random_strength|1e3-10|
|bootstrap_type|Bayesian / Bernoulli / MVS|
|bagging_temperature|0-5|
|one_hot_max_size|2-105|
|leaf_estimation_iterations|1-10|
|auto_class_weights|none / Balanced|

In [11]:
fixed_params_plain = {
    "random_seed": RANDOM_STATE,
    "task_type": "CPU",
    "eval_metric": "AUC",
    "thread_count": -1,
    "allow_writing_files": False,
    "cat_features": cat_cols,
    "use_best_model": True,
    "early_stopping_rounds": 100,
    "loss_function": "Logloss",
    "border_count": 254,
    "verbose": 0,
    "iterations": 5000,
    "boosting_type": "Plain"
}

In [12]:
fixed_params_ordered = {
    "random_seed": RANDOM_STATE,
    "task_type": "CPU",
    "eval_metric": "AUC",
    "thread_count": -1,
    "allow_writing_files": False,
    "cat_features": cat_cols,
    "use_best_model": True,
    "early_stopping_rounds": 100,
    "loss_function": "Logloss",
    "border_count": 254,
    "verbose": 0,
    "iterations": 5000,
    "boosting_type": "Ordered"
}

In [13]:
def suchraum_params(trial):
    """Suchraum definition"""
    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "depth": trial.suggest_int("depth", 4, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1.0, 30.0, log=True),
        "random_strength": trial.suggest_float("random_strength", 1e-3, 10.0, log=True),
        "one_hot_max_size": trial.suggest_categorical("one_hot_max_size", [2, 10, 18, 105]),
        "leaf_estimation_iterations": trial.suggest_int("leaf_estimation_iterations", 1, 10),
        "auto_class_weights": trial.suggest_categorical("auto_class_weights", [None, "Balanced"]),
        "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli", "MVS"])
    }

    if params["bootstrap_type"] == "Bayesian":
        params["bagging_temperature"] = trial.suggest_float("bagging_temperature", 0.0, 5.0)
    else:
        params["subsample"] = trial.suggest_float("subsample", 0.5, 1.0)

    return params

## Plain mit Calc

In [15]:
def objective_plain_calc(trial):
    modell = CatBoostClassifier(
        **fixed_params_plain,
        **suchraum_params(trial)
    )
    pruning_callback = CatBoostPruningCallback(trial, "AUC")

    modell.fit(x_sub_75, y_sub_75, eval_set=[(x_val_cb, y_val)], callbacks=[pruning_callback])
    pruning_callback.check_pruned()

    return roc_auc_score(y_val, modell.predict_proba(x_val_cb)[:, 1])

In [18]:
study_plain_with_calc = optuna.create_study(
    study_name = "CatBoost_Plain_with_calc",
    storage = "sqlite:///catboost_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=200)
)

[I 2026-08-13 02:02:48,345] A new study created in RDB with name: CatBoost_Plain_with_calc

In [20]:
study_plain_with_calc.optimize(
    objective_plain_calc,
    n_trials = 50,
    timeout = 3*60*60,
    catch = (Exception, )
)

C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 02:38:59,744] Trial 0 finished with value: 0.62754305297685 and parameters: {'learning_rate': 0.03574712922600244, 'depth': 10, 'l2_leaf_reg': 12.057126287443763, 'random_strength': 0.24810409748678125, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.9091248360355031}. Best is trial 0 with value: 0.62754305297685.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 02:40:38,241] Trial 1 finished with value: 0.6305607945590602 and parameters: {'learning_rate': 0.018659959624904916, 'depth': 6, 'l2_leaf_reg': 5.958389350068956, 'random_strength': 0.05342937261279776, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.5232252063599989}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 02:42:35,208] Trial 2 finished with value: 0.6291950241874396 and parameters: {'learning_rate': 0.07896186801026692, 'depth': 5, 'l2_leaf_reg': 1.2476394272569447, 'random_strength': 6.245139574743075, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.6293899908000085}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 02:43:33,644] Trial 3 finished with value: 0.6278725742191895 and parameters: {'learning_rate': 0.09519754482692679, 'depth': 6, 'l2_leaf_reg': 5.864129169696525, 'random_strength': 0.1537592023548176, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6626651653816322}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 02:45:23,933] Trial 4 finished with value: 0.6293777592791858 and parameters: {'learning_rate': 0.03750796359625606, 'depth': 5, 'l2_leaf_reg': 16.755052359850303, 'random_strength': 0.026730883107816707, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.8534286719238086}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 02:45:47,811] Trial 5 finished with value: 0.6237304957399983 and parameters: {'learning_rate': 0.11935262708510537, 'depth': 9, 'l2_leaf_reg': 1.286390810198991, 'random_strength': 0.02715581955282941, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7361074625809747}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:11:09,628] Trial 6 finished with value: 0.627495729314827 and parameters: {'learning_rate': 0.015019490572374374, 'depth': 8, 'l2_leaf_reg': 13.297554090738672, 'random_strength': 0.17583640270008521, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 4.537832369630465}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:11:36,794] Trial 7 finished with value: 0.6285314961237886 and parameters: {'learning_rate': 0.02334720250903525, 'depth': 6, 'l2_leaf_reg': 13.062931388340921, 'random_strength': 0.008226074946221037, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7696711209578253}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:12:00,217] Trial 8 finished with value: 0.6297005360757231 and parameters: {'learning_rate': 0.1558428978238547, 'depth': 10, 'l2_leaf_reg': 2.949372944095385, 'random_strength': 0.002755546207779663, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.9714548519562596}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:21:52,445] Trial 9 finished with value: 0.6282126100444959 and parameters: {'learning_rate': 0.030019946952402964, 'depth': 7, 'l2_leaf_reg': 10.925573591447922, 'random_strength': 0.02847858516856297, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.3932323211830573}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:22:17,615] Trial 10 finished with value: 0.6294253642947287 and parameters: {'learning_rate': 0.25441416790751953, 'depth': 4, 'l2_leaf_reg': 27.047297227177754, 'random_strength': 5.359957765771775, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5248259995479624}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:23:12,881] Trial 11 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 03:23:30,914] Trial 12 finished with value: 0.6231555779577267 and parameters: {'learning_rate': 0.22287218859308172, 'depth': 8, 'l2_leaf_reg': 3.248412359708818, 'random_strength': 0.001110835886188128, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.9901697749881503}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:23:49,390] Trial 13 finished with value: 0.6292122992935526 and parameters: {'learning_rate': 0.05445057683691509, 'depth': 8, 'l2_leaf_reg': 3.2072615131434117, 'random_strength': 0.8387744815011882, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 6, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.5246423867088743}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:24:15,533] Trial 14 finished with value: 0.6292435777662776 and parameters: {'learning_rate': 0.16406004394991577, 'depth': 4, 'l2_leaf_reg': 5.647196273200802, 'random_strength': 0.006077373869429218, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.8705765955899739}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:24:27,827] Trial 15 pruned. Trial was pruned at iteration 249.
[I 2026-08-13 03:24:59,954] Trial 16 finished with value: 0.6289529395803687 and parameters: {'learning_rate': 0.06175599823298681, 'depth': 7, 'l2_leaf_reg': 6.117039351977243, 'random_strength': 0.06177562735490054, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.6218164696016999}. Best is trial 1 with value: 0.6305607945590602.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:25:33,291] Trial 17 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 03:25:41,831] Trial 18 finished with value: 0.6309928812173591 and parameters: {'learning_rate': 0.15917911692015974, 'depth': 7, 'l2_leaf_reg': 7.726484663624008, 'random_strength': 0.0031144785621379147, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.9362705527423543}. Best is trial 18 with value: 0.6309928812173591.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:26:42,202] Trial 19 finished with value: 0.6308607977978411 and parameters: {'learning_rate': 0.05268673331708821, 'depth': 6, 'l2_leaf_reg': 7.892766324267427, 'random_strength': 0.010311343054234461, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5731755248201813}. Best is trial 18 with value: 0.6309928812173591.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:27:03,251] Trial 20 finished with value: 0.634440522939086 and parameters: {'learning_rate': 0.047611121022996535, 'depth': 7, 'l2_leaf_reg': 8.593733349151965, 'random_strength': 0.011423191447041188, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9178574821162729}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:27:15,674] Trial 21 finished with value: 0.6299572832205094 and parameters: {'learning_rate': 0.047352244354476145, 'depth': 7, 'l2_leaf_reg': 7.6191650140020935, 'random_strength': 0.011237669165316197, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9317109596670372}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:27:24,337] Trial 22 finished with value: 0.6306793408549418 and parameters: {'learning_rate': 0.0677485100894611, 'depth': 7, 'l2_leaf_reg': 8.647655366221898, 'random_strength': 0.0032524158204335785, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.931323588421291}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:27:39,229] Trial 23 finished with value: 0.6297636476895405 and parameters: {'learning_rate': 0.09903955875093695, 'depth': 5, 'l2_leaf_reg': 21.679214861105667, 'random_strength': 0.013073692286639125, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.8170064962868606}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:27:51,954] Trial 24 finished with value: 0.6292047509805512 and parameters: {'learning_rate': 0.04375622805616019, 'depth': 6, 'l2_leaf_reg': 4.2969936705895355, 'random_strength': 0.0032563021969691194, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9307264482979007}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:28:10,559] Trial 25 finished with value: 0.6240841731916767 and parameters: {'learning_rate': 0.2990004339585014, 'depth': 7, 'l2_leaf_reg': 8.942467550896106, 'random_strength': 0.011097437019186324, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6940042236718941}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:28:49,274] Trial 26 finished with value: 0.6285977428196833 and parameters: {'learning_rate': 0.1537308516512574, 'depth': 8, 'l2_leaf_reg': 16.737759773695036, 'random_strength': 0.0010932019929636512, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 5, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.5802880751449888}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:29:35,073] Trial 27 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 03:29:41,887] Trial 28 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 03:29:50,574] Trial 29 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 03:30:15,100] Trial 30 finished with value: 0.6284025879797077 and parameters: {'learning_rate': 0.12209676418171535, 'depth': 6, 'l2_leaf_reg': 4.4321970188651845, 'random_strength': 0.0017467211591977226, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 5, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9036813508594743}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:30:26,110] Trial 31 finished with value: 0.6303263788450707 and parameters: {'learning_rate': 0.06072261614242802, 'depth': 7, 'l2_leaf_reg': 9.62380455435222, 'random_strength': 0.002613592320850958, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9331678142265862}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:30:46,296] Trial 32 finished with value: 0.6318779711584829 and parameters: {'learning_rate': 0.04137343989120443, 'depth': 7, 'l2_leaf_reg': 7.133669294955594, 'random_strength': 0.006288148618613259, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9077005426941609}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 03:30:55,805] Trial 33 pruned. Trial was pruned at iteration 202.
[I 2026-08-13 03:31:02,961] Trial 34 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 03:31:17,971] Trial 35 finished with value: 0.6306420333782221 and parameters: {'learning_rate': 0.03989973048028742, 'depth': 6, 'l2_leaf_reg': 15.894134528310815, 'random_strength': 0.008301741313892531, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.8602332646777167}. Best is trial 20 with value: 0.634440522939086.
C:\Users\linus\AppData\Local\Temp\ipykernel_16940\1179548323.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")

In [21]:
pd.DataFrame({
    "best auc_val": study_plain_with_calc.best_value,
    "best gini": 2 * study_plain_with_calc.best_value - 1,
    "trials": len(study_plain_with_calc.trials),
    "pruned": len([t for t in study_plain_with_calc.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_plain_with_calc.trials if t.state.name == "FAIL"]),
    "best params": study_plain_with_calc.best_params
})

,best auc_val,best gini,trials,pruned,fail,best params
learning_rate,0.634441,0.268881,50,14,0,0.047611
depth,0.634441,0.268881,50,14,0,7
l2_leaf_reg,0.634441,0.268881,50,14,0,8.593733
random_strength,0.634441,0.268881,50,14,0,0.011423
one_hot_max_size,0.634441,0.268881,50,14,0,105
leaf_estimation_iterations,0.634441,0.268881,50,14,0,2
auto_class_weights,0.634441,0.268881,50,14,0,Balanced
bootstrap_type,0.634441,0.268881,50,14,0,Bernoulli
subsample,0.634441,0.268881,50,14,0,0.917857

## Plain ohne Calc

In [14]:
def objective_plain_no_calc(trial):
    modell = CatBoostClassifier(
        **fixed_params_plain,
        **suchraum_params(trial)
    )
    pruning_callback = CatBoostPruningCallback(trial, "AUC")

    modell.fit(x_sub_no_calc_75, y_sub_75, eval_set=[(x_val_no_calc_cb, y_val)], callbacks=[pruning_callback])
    pruning_callback.check_pruned()

    return roc_auc_score(y_val, modell.predict_proba(x_val_no_calc_cb)[:, 1])

In [15]:
study_plain_without_calc = optuna.create_study(
    study_name = "CatBoost_Plain_without_calc",
    storage = "sqlite:///catboost_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=200)
)

[I 2026-08-13 07:48:13,396] Using an existing study with name 'CatBoost_Plain_without_calc' instead of creating a new one.

In [16]:
study_plain_without_calc.optimize(
    objective_plain_no_calc,
    n_trials = 50,
    timeout = 3*60*60,
    catch = (Exception, )
)

C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:48:33,657] Trial 17 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:49:11,998] Trial 18 finished with value: 0.6324996579344101 and parameters: {'learning_rate': 0.1706769518716959, 'depth': 4, 'l2_leaf_reg': 19.26564052774494, 'random_strength': 1.935391410669271, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5780545957082477}. Best is trial 14 with value: 0.6340737665680749.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:49:30,490] Trial 19 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:50:49,615] Trial 20 finished with value: 0.6346247773398389 and parameters: {'learning_rate': 0.08962717626942558, 'depth': 4, 'l2_leaf_reg': 29.558267636211944, 'random_strength': 9.941450502972573, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5797654491534234}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:51:20,498] Trial 21 finished with value: 0.6316355971592201 and parameters: {'learning_rate': 0.1549896302324905, 'depth': 5, 'l2_leaf_reg': 9.132020886092892, 'random_strength': 9.639798532690996, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5680808857528666}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:52:12,717] Trial 22 finished with value: 0.6333086377291035 and parameters: {'learning_rate': 0.07636073188933429, 'depth': 4, 'l2_leaf_reg': 27.02272241241035, 'random_strength': 0.6876847313606971, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6335106722647657}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:53:02,082] Trial 23 finished with value: 0.6331744562161953 and parameters: {'learning_rate': 0.10924956593762239, 'depth': 4, 'l2_leaf_reg': 17.658478614656957, 'random_strength': 3.328870763227455, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5065896071904618}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:53:28,131] Trial 24 pruned. Trial was pruned at iteration 244.
[I 2026-08-13 07:54:44,816] Trial 25 finished with value: 0.6335809477428682 and parameters: {'learning_rate': 0.07564463686149055, 'depth': 4, 'l2_leaf_reg': 28.762510263887805, 'random_strength': 1.2697134124026839, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 5, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5859555410712751}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:55:07,006] Trial 26 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:55:45,430] Trial 27 pruned. Trial was pruned at iteration 457.
[I 2026-08-13 07:56:15,888] Trial 28 finished with value: 0.6310898034855795 and parameters: {'learning_rate': 0.19215293084840904, 'depth': 4, 'l2_leaf_reg': 21.79001124828681, 'random_strength': 1.0949960522799382, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 5, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5957760994260553}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:56:43,027] Trial 29 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:56:58,714] Trial 30 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:57:35,058] Trial 31 finished with value: 0.6323380082793015 and parameters: {'learning_rate': 0.09335669687890168, 'depth': 5, 'l2_leaf_reg': 14.655434684324105, 'random_strength': 0.10982201690585713, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 7, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.8055110742746786}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 07:57:52,696] Trial 32 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:58:09,544] Trial 33 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:58:30,227] Trial 34 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:58:47,828] Trial 35 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:59:07,723] Trial 36 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 07:59:25,082] Trial 37 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:00:40,937] Trial 38 finished with value: 0.6333419580245147 and parameters: {'learning_rate': 0.11856822253041005, 'depth': 5, 'l2_leaf_reg': 24.592063181569944, 'random_strength': 6.10321821709513, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 7, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.5016821779662053}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:00:47,847] Trial 39 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:01:13,892] Trial 40 pruned. Trial was pruned at iteration 214.
[I 2026-08-13 08:01:50,540] Trial 41 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:02:47,537] Trial 42 pruned. Trial was pruned at iteration 351.
[I 2026-08-13 08:03:28,030] Trial 43 pruned. Trial was pruned at iteration 240.
[I 2026-08-13 08:03:53,609] Trial 44 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:04:21,501] Trial 45 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:07:23,570] Trial 46 finished with value: 0.6340184363887466 and parameters: {'learning_rate': 0.08435324561959887, 'depth': 6, 'l2_leaf_reg': 17.82146489515744, 'random_strength': 0.47147415580414687, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.5855777674344093}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:07:38,374] Trial 47 finished with value: 0.6329090916150325 and parameters: {'learning_rate': 0.08602114963305976, 'depth': 8, 'l2_leaf_reg': 11.33309855850888, 'random_strength': 0.5003249688323994, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 10, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.9466039228376142}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:08:03,102] Trial 48 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:08:56,729] Trial 49 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:09:50,269] Trial 50 finished with value: 0.632710496223444 and parameters: {'learning_rate': 0.14251421333722045, 'depth': 6, 'l2_leaf_reg': 1.7033452765632833, 'random_strength': 0.9087113615843058, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 5, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.6208487054553586}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:10:09,901] Trial 51 finished with value: 0.6324247214340908 and parameters: {'learning_rate': 0.08138147705132466, 'depth': 7, 'l2_leaf_reg': 14.030303519669408, 'random_strength': 0.04736345202762908, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 6, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.674806930510814}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:10:43,608] Trial 52 pruned. Trial was pruned at iteration 201.
[I 2026-08-13 08:11:18,378] Trial 53 pruned. Trial was pruned at iteration 231.
[I 2026-08-13 08:11:53,629] Trial 54 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:12:19,995] Trial 55 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:13:38,701] Trial 56 finished with value: 0.6318965646068029 and parameters: {'learning_rate': 0.0858767866258044, 'depth': 5, 'l2_leaf_reg': 16.9654647601099, 'random_strength': 0.21745929716916942, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7205296699171181}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:14:38,399] Trial 57 finished with value: 0.6339616190550995 and parameters: {'learning_rate': 0.11968283442437884, 'depth': 4, 'l2_leaf_reg': 26.008209671528398, 'random_strength': 0.9105488698499096, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 5, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6138002627320079}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:15:10,841] Trial 58 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 08:16:04,529] Trial 59 finished with value: 0.633905444815212 and parameters: {'learning_rate': 0.16414362330500334, 'depth': 4, 'l2_leaf_reg': 26.682701398597597, 'random_strength': 0.545942933648998, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.6859436110868861}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:16:31,548] Trial 60 finished with value: 0.626895763030625 and parameters: {'learning_rate': 0.2512852993917909, 'depth': 9, 'l2_leaf_reg': 7.053433715896464, 'random_strength': 0.0010400700591837093, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.682782815719236}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:17:19,155] Trial 61 finished with value: 0.6338888690735625 and parameters: {'learning_rate': 0.1450614229279682, 'depth': 4, 'l2_leaf_reg': 3.676289544068066, 'random_strength': 0.4117442470361202, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.775806216966228}. Best is trial 20 with value: 0.6346247773398389.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:18:17,834] Trial 62 finished with value: 0.6346269236652611 and parameters: {'learning_rate': 0.17595817710624895, 'depth': 4, 'l2_leaf_reg': 3.9143184149527266, 'random_strength': 0.5015455446392323, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.7854715288197278}. Best is trial 62 with value: 0.6346269236652611.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:18:59,533] Trial 63 finished with value: 0.6331949548297776 and parameters: {'learning_rate': 0.19393979819294574, 'depth': 4, 'l2_leaf_reg': 3.6513310295921793, 'random_strength': 0.46416259047738445, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.7688916706547583}. Best is trial 62 with value: 0.6346269236652611.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:19:38,981] Trial 64 finished with value: 0.6327790580568728 and parameters: {'learning_rate': 0.1645859545425007, 'depth': 4, 'l2_leaf_reg': 2.549638173438883, 'random_strength': 0.13639102988729282, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8513603154962275}. Best is trial 62 with value: 0.6346269236652611.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:20:09,896] Trial 65 finished with value: 0.6340475685360494 and parameters: {'learning_rate': 0.24078055126118744, 'depth': 4, 'l2_leaf_reg': 4.90001816887503, 'random_strength': 0.339832629962287, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8171226090872435}. Best is trial 62 with value: 0.6346269236652611.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\1090979878.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:20:51,257] Trial 66 finished with value: 0.6334789771886363 and parameters: {'learning_rate': 0.2061394090187974, 'depth': 4, 'l2_leaf_reg': 5.377947453988876, 'random_strength': 0.5985888428709888, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8834032048025573}. Best is trial 62 with value: 0.6346269236652611.

In [17]:
pd.Series({
    "best auc_val": study_plain_without_calc.best_value,
    "best gini": 2 * study_plain_without_calc.best_value - 1,
    "trials": len(study_plain_without_calc.trials),
    "pruned": len([t for t in study_plain_without_calc.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_plain_without_calc.trials if t.state.name == "FAIL"]),
    "best params": study_plain_without_calc.best_params
})

best auc_val                                             0.634627
best gini                                                0.269254
trials                                                         67
pruned                                                         29
fail                                                            0
best params     {'learning_rate': 0.17595817710624895, 'depth'...
dtype: object

In [22]:
study_plain_without_calc.best_params

{'learning_rate': 0.17595817710624895,
 'depth': 4,
 'l2_leaf_reg': 3.9143184149527266,
 'random_strength': 0.5015455446392323,
 'one_hot_max_size': 10,
 'leaf_estimation_iterations': 2,
 'auto_class_weights': None,
 'bootstrap_type': 'Bernoulli',
 'subsample': 0.7854715288197278}

## Ordered ohne Calc

In [18]:
def objective_ordered_no_calc(trial):
    modell = CatBoostClassifier(
        **fixed_params_ordered,
        **suchraum_params(trial)
    )
    pruning_callback = CatBoostPruningCallback(trial, "AUC")

    modell.fit(x_sub_no_calc_75, y_sub_75, eval_set=[(x_val_no_calc_cb, y_val)], callbacks=[pruning_callback])
    pruning_callback.check_pruned()

    return roc_auc_score(y_val, modell.predict_proba(x_val_no_calc_cb)[:, 1])

In [19]:
study_ordered_without_calc = optuna.create_study(
    study_name = "CatBoost_Ordered_without_calc",
    storage = "sqlite:///catboost_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=200)
)

[I 2026-08-13 08:20:51,439] A new study created in RDB with name: CatBoost_Ordered_without_calc

In [20]:
study_ordered_without_calc.optimize(
    objective_ordered_no_calc,
    n_trials = 50,
    timeout = 3*60*60,
    catch = (Exception, )
)

C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:30:04,694] Trial 0 finished with value: 0.6315642459066098 and parameters: {'learning_rate': 0.03574712922600244, 'depth': 10, 'l2_leaf_reg': 12.057126287443763, 'random_strength': 0.24810409748678125, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.9091248360355031}. Best is trial 0 with value: 0.6315642459066098.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:31:39,094] Trial 1 finished with value: 0.6285824050335206 and parameters: {'learning_rate': 0.018659959624904916, 'depth': 6, 'l2_leaf_reg': 5.958389350068956, 'random_strength': 0.05342937261279776, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.5232252063599989}. Best is trial 0 with value: 0.6315642459066098.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:36:14,592] Trial 2 finished with value: 0.6319688644227083 and parameters: {'learning_rate': 0.07896186801026692, 'depth': 5, 'l2_leaf_reg': 1.2476394272569447, 'random_strength': 6.245139574743075, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.6293899908000085}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:37:18,011] Trial 3 finished with value: 0.6294957750227158 and parameters: {'learning_rate': 0.09519754482692679, 'depth': 6, 'l2_leaf_reg': 5.864129169696525, 'random_strength': 0.1537592023548176, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6626651653816322}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:38:03,184] Trial 4 finished with value: 0.6314682963177005 and parameters: {'learning_rate': 0.03750796359625606, 'depth': 5, 'l2_leaf_reg': 16.755052359850303, 'random_strength': 0.026730883107816707, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.8534286719238086}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 08:38:55,576] Trial 5 finished with value: 0.6291121374405192 and parameters: {'learning_rate': 0.11935262708510537, 'depth': 9, 'l2_leaf_reg': 1.286390810198991, 'random_strength': 0.02715581955282941, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7361074625809747}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 09:15:18,710] Trial 6 finished with value: 0.6315957816168385 and parameters: {'learning_rate': 0.015019490572374374, 'depth': 8, 'l2_leaf_reg': 13.297554090738672, 'random_strength': 0.17583640270008521, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 4.537832369630465}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 09:16:15,770] Trial 7 finished with value: 0.628793822106938 and parameters: {'learning_rate': 0.02334720250903525, 'depth': 6, 'l2_leaf_reg': 13.062931388340921, 'random_strength': 0.008226074946221037, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7696711209578253}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 09:17:51,643] Trial 8 finished with value: 0.6304549011328957 and parameters: {'learning_rate': 0.1558428978238547, 'depth': 10, 'l2_leaf_reg': 2.949372944095385, 'random_strength': 0.002755546207779663, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.9714548519562596}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 09:42:27,063] Trial 9 finished with value: 0.6296453907858507 and parameters: {'learning_rate': 0.030019946952402964, 'depth': 7, 'l2_leaf_reg': 10.925573591447922, 'random_strength': 0.02847858516856297, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.3932323211830573}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 09:43:13,373] Trial 10 finished with value: 0.6298090501089574 and parameters: {'learning_rate': 0.2646758809966218, 'depth': 4, 'l2_leaf_reg': 1.0260022325256586, 'random_strength': 5.494747759980004, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 6, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.5268383824514689}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 09:44:46,061] Trial 11 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 09:45:38,326] Trial 12 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 09:46:55,978] Trial 13 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 09:48:09,528] Trial 14 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 09:48:39,846] Trial 15 finished with value: 0.6287008548653383 and parameters: {'learning_rate': 0.27441025250371953, 'depth': 5, 'l2_leaf_reg': 3.6344818956968377, 'random_strength': 0.0011065136021090993, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 6, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.6453017955724255}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 09:49:42,209] Trial 16 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 09:52:28,648] Trial 17 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 09:53:10,611] Trial 18 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 09:53:43,129] Trial 19 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 09:58:50,961] Trial 20 finished with value: 0.6300795433828518 and parameters: {'learning_rate': 0.08571782380456483, 'depth': 9, 'l2_leaf_reg': 18.590112816357692, 'random_strength': 0.11214554164491186, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 10, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.9969213925248543}. Best is trial 2 with value: 0.6319688644227083.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:04:26,123] Trial 21 finished with value: 0.6323100256620937 and parameters: {'learning_rate': 0.03660767448596424, 'depth': 10, 'l2_leaf_reg': 7.6191650140020935, 'random_strength': 0.381050808207718, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.15085884738285726}. Best is trial 21 with value: 0.6323100256620937.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:07:40,675] Trial 22 finished with value: 0.6297606331875432 and parameters: {'learning_rate': 0.04570239628659368, 'depth': 10, 'l2_leaf_reg': 8.40219204686988, 'random_strength': 0.3327426214301337, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 6, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.28306126188161684}. Best is trial 21 with value: 0.6323100256620937.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:08:32,361] Trial 23 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 10:10:29,580] Trial 24 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 10:12:39,554] Trial 25 finished with value: 0.6317161687686065 and parameters: {'learning_rate': 0.07909167719957816, 'depth': 10, 'l2_leaf_reg': 21.923338477824867, 'random_strength': 2.8045899126476894, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 5, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.015254992635892639}. Best is trial 21 with value: 0.6323100256620937.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:15:01,827] Trial 26 finished with value: 0.631266284490515 and parameters: {'learning_rate': 0.07511346033555827, 'depth': 10, 'l2_leaf_reg': 23.142051953867483, 'random_strength': 2.570682527587929, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 5, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.08580865635810463}. Best is trial 21 with value: 0.6323100256620937.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:17:20,943] Trial 27 finished with value: 0.6311270546915952 and parameters: {'learning_rate': 0.10680578799557817, 'depth': 10, 'l2_leaf_reg': 4.602716010304526, 'random_strength': 2.8729887930186147, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 5, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.706497977414204}. Best is trial 21 with value: 0.6323100256620937.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:18:16,807] Trial 28 finished with value: 0.6314674924505013 and parameters: {'learning_rate': 0.1595190267084587, 'depth': 9, 'l2_leaf_reg': 2.561710829441785, 'random_strength': 0.5376866097546624, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 8, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.7055027880413638}. Best is trial 21 with value: 0.6323100256620937.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:19:47,997] Trial 29 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 10:21:13,781] Trial 30 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 10:24:28,615] Trial 31 finished with value: 0.6334112352997509 and parameters: {'learning_rate': 0.07280137370509145, 'depth': 9, 'l2_leaf_reg': 20.36398989981563, 'random_strength': 0.14871766095846403, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.007144204532009171}. Best is trial 31 with value: 0.6334112352997509.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:30:10,973] Trial 32 finished with value: 0.6334479318373992 and parameters: {'learning_rate': 0.07522925545685702, 'depth': 9, 'l2_leaf_reg': 21.727358099820517, 'random_strength': 1.7703555608560753, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.0044302304989518315}. Best is trial 32 with value: 0.6334479318373992.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:31:01,443] Trial 33 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 10:32:15,064] Trial 34 finished with value: 0.632365404073454 and parameters: {'learning_rate': 0.12384496355940418, 'depth': 6, 'l2_leaf_reg': 19.533604382964825, 'random_strength': 0.22786979711448643, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.5389152261017656}. Best is trial 32 with value: 0.6334479318373992.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:32:54,920] Trial 35 finished with value: 0.6307055790803272 and parameters: {'learning_rate': 0.2018330172129141, 'depth': 7, 'l2_leaf_reg': 18.9062751444769, 'random_strength': 0.05186542441353868, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.5260455627714199}. Best is trial 32 with value: 0.6334479318373992.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:34:11,832] Trial 36 finished with value: 0.6302658958769949 and parameters: {'learning_rate': 0.1297419910326708, 'depth': 9, 'l2_leaf_reg': 15.24520194006423, 'random_strength': 0.21713805752461005, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.1913522081881256}. Best is trial 32 with value: 0.6334479318373992.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:35:18,052] Trial 37 finished with value: 0.6312687443241449 and parameters: {'learning_rate': 0.10051261938484611, 'depth': 6, 'l2_leaf_reg': 9.875610525360512, 'random_strength': 0.13411960696067665, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.04494902205914575}. Best is trial 32 with value: 0.6334479318373992.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:36:38,784] Trial 38 finished with value: 0.6301820605667793 and parameters: {'learning_rate': 0.07126211645245285, 'depth': 6, 'l2_leaf_reg': 20.781461336599076, 'random_strength': 0.06139343220349307, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.4790013975975352}. Best is trial 32 with value: 0.6334479318373992.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:38:48,813] Trial 39 finished with value: 0.6311773124688959 and parameters: {'learning_rate': 0.12376106230407358, 'depth': 9, 'l2_leaf_reg': 13.699240801286921, 'random_strength': 0.3631525281161778, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.2004702123136384}. Best is trial 32 with value: 0.6334479318373992.
C:\Users\linus\AppData\Local\Temp\ipykernel_4008\2304183874.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 10:40:33,586] Trial 40 finished with value: 0.6313714463975282 and parameters: {'learning_rate': 0.09195687055616128, 'depth': 8, 'l2_leaf_reg': 6.787550398114915, 'random_strength': 0.019325485245184234, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.47742586719971364}. Best is trial 32 with value: 0.6334479318373992.

In [21]:
pd.Series({
    "best auc_val": study_ordered_without_calc.best_value,
    "best gini": 2 * study_ordered_without_calc.best_value - 1,
    "trials": len(study_ordered_without_calc.trials),
    "pruned": len([t for t in study_ordered_without_calc.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_ordered_without_calc.trials if t.state.name == "FAIL"]),
    "best params": study_ordered_without_calc.best_params
})

best auc_val                                             0.633448
best gini                                                0.266896
trials                                                         50
pruned                                                         19
fail                                                            0
best params     {'learning_rate': 0.07522925545685702, 'depth'...
dtype: object

In [23]:
study_ordered_without_calc.best_params

{'learning_rate': 0.07522925545685702,
 'depth': 9,
 'l2_leaf_reg': 21.727358099820517,
 'random_strength': 1.7703555608560753,
 'one_hot_max_size': 10,
 'leaf_estimation_iterations': 3,
 'auto_class_weights': None,
 'bootstrap_type': 'Bayesian',
 'bagging_temperature': 0.0044302304989518315}

## Load Study

In [24]:
study_plain_with_calc_loaded = optuna.load_study(
    study_name = "CatBoost_Plain_with_calc",
    storage = "sqlite:///catboost_opti.db"
)

In [25]:
study_plain_without_calc_loaded = optuna.load_study(
    study_name = "CatBoost_Plain_without_calc",
    storage = "sqlite:///catboost_opti.db"
)

In [26]:
study_ordered_without_calc_loaded = optuna.load_study(
    study_name = "CatBoost_Ordered_without_calc",
    storage = "sqlite:///catboost_opti.db"
)

## Best Params again

In [27]:
study_plain_with_calc_loaded.best_params

{'learning_rate': 0.047611121022996535,
 'depth': 7,
 'l2_leaf_reg': 8.593733349151965,
 'random_strength': 0.011423191447041188,
 'one_hot_max_size': 105,
 'leaf_estimation_iterations': 2,
 'auto_class_weights': 'Balanced',
 'bootstrap_type': 'Bernoulli',
 'subsample': 0.9178574821162729}

In [28]:
study_plain_without_calc_loaded.best_params

{'learning_rate': 0.17595817710624895,
 'depth': 4,
 'l2_leaf_reg': 3.9143184149527266,
 'random_strength': 0.5015455446392323,
 'one_hot_max_size': 10,
 'leaf_estimation_iterations': 2,
 'auto_class_weights': None,
 'bootstrap_type': 'Bernoulli',
 'subsample': 0.7854715288197278}

In [29]:
study_ordered_without_calc_loaded.best_params

{'learning_rate': 0.07522925545685702,
 'depth': 9,
 'l2_leaf_reg': 21.727358099820517,
 'random_strength': 1.7703555608560753,
 'one_hot_max_size': 10,
 'leaf_estimation_iterations': 3,
 'auto_class_weights': None,
 'bootstrap_type': 'Bayesian',
 'bagging_temperature': 0.0044302304989518315}

## 100% Train

In [30]:
results = []
train_times = {}

In [31]:
name = "L_cb_opt_01"

L_cb_opt_01 = CatBoostClassifier(
    **fixed_params_plain,
    **study_plain_with_calc_loaded.best_params
)

start = time.time()
L_cb_opt_01.fit(
    x_train_cb, y_train, 
    eval_set=(x_val_cb, y_val), 
    verbose=250
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_cb_opt_01, x_train_cb, y_train, x_val_cb, y_val, train_times[name], best_iter=L_cb_opt_01.get_best_iteration())
)

0:	test: 0.6037890	best: 0.6037890 (0)	total: 36.4ms	remaining: 3m 2s
250:	test: 0.6320888	best: 0.6323677 (245)	total: 9.32s	remaining: 2m 56s
500:	test: 0.6332904	best: 0.6336649 (478)	total: 18.5s	remaining: 2m 46s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6336873958
bestIteration = 549

Shrink model to first 550 iterations.

In [32]:
name = "L_cb_opt_02"

L_cb_opt_02 = CatBoostClassifier(
    **fixed_params_plain,
    **study_plain_without_calc_loaded.best_params
)

start = time.time()
L_cb_opt_02.fit(
    x_train_no_calc_cb, y_train, 
    eval_set=(x_val_no_calc_cb, y_val), 
    verbose=250
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_cb_opt_02, x_train_no_calc_cb, y_train, x_val_no_calc_cb, y_val, train_times[name], best_iter=L_cb_opt_02.get_best_iteration())
)

0:	test: 0.5382770	best: 0.5382770 (0)	total: 87.9ms	remaining: 7m 19s
250:	test: 0.6316706	best: 0.6316958 (244)	total: 21.1s	remaining: 6m 39s
500:	test: 0.6333197	best: 0.6335711 (459)	total: 42.2s	remaining: 6m 19s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6336871949
bestIteration = 518

Shrink model to first 519 iterations.

In [33]:
name = "L_cb_opt_03"

L_cb_opt_03 = CatBoostClassifier(
    **fixed_params_ordered,
    **study_ordered_without_calc_loaded.best_params
)

start = time.time()
L_cb_opt_03.fit(
    x_train_no_calc_cb, y_train, 
    eval_set=(x_val_no_calc_cb, y_val), 
    verbose=250
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_cb_opt_03, x_train_no_calc_cb, y_train, x_val_no_calc_cb, y_val, train_times[name], best_iter=L_cb_opt_03.get_best_iteration())
)

0:	test: 0.5613484	best: 0.5613484 (0)	total: 495ms	remaining: 41m 13s
250:	test: 0.6284516	best: 0.6284516 (246)	total: 1m 28s	remaining: 27m 49s
500:	test: 0.6295876	best: 0.6296311 (412)	total: 3m 6s	remaining: 27m 55s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6296310739
bestIteration = 412

Shrink model to first 413 iterations.

In [35]:
pd.DataFrame(results)

,model_idx,auc_train,auc_val,gini,delta_auc,best_iter,trainingszeit
0,L_cb_opt_01,0.740788,0.633687,0.267375,0.107101,549,24.047395
1,L_cb_opt_02,0.664717,0.633687,0.267374,0.031030,518,52.476140
2,L_cb_opt_03,0.655782,0.629631,0.259262,0.026151,412,192.045585

## Save Models

In [36]:
Modelle = [
    (L_cb_opt_01, "L_cb_opt_01"),
    (L_cb_opt_02, "L_cb_opt_02"),
    (L_cb_opt_03, "L_cb_opt_03")
]

for modell, name in Modelle:
    modell.save_model(f"{name}.cbm")

## Notizen
- Weil ich auf cpu trainiere setze ich border_count fix auf 254. (Soll auf GPU größeren einfluss auf laufzeit haben, als auf cpu)
- Mit log=True den suchraum um den zahlenbereich nicht linear zu halten
- bagging temp oder subsample von bootstrap type abhängig
- storage über den sqlite, kopiere aus quell, erstellt eine db. (eine db für mehrere deshalb nicht study name als name und load if exists) muss ich in die .gitignore einfügen
- direction max weil höhere auc
- TPE sampler für tree based
- medianpruner (scheint mir am meisten straight forward)
- best iters lagen meist über 200 also nehme ich das mal als warmup um den early stop etwas hinaus zu zögern
- n_trials funktioniert etwas wie iterations, ich nehme erstmal 50 wenn ich ein timelimit stelle wird das wohl kaum erreicht.
- time limit setze ich pro versuch mal auf 3 stunden. also stunden * minuten * sekunden : 3 * 60 * 60
- catch um errors zu überspringen
- pc ist im ersten durchlauf abgestürzt ich muss nochmal runnen
- Nächster Schritt: Neues Notebook mit logreg und diesen modellen auf test testen + diese modelle mit den parametern dann nochmal auf train+val trainieren und auif test testen.



## Ressourcen [Aufrufdatun 13.08.2026]:
- https://forecastegy.com/posts/catboost-hyperparameter-tuning-guide-with-optuna/
- https://catboost.ai/docs/en/references/training-parameters/output
- https://www.geeksforgeeks.org/machine-learning/catboost-cross-validation-and-hyperparameter-tuning/
- https://mljourney.com/catboost-classifier-complete-guide/
- https://catboost.ai/docs/en/concepts/parameter-tuning
- https://www.geeksforgeeks.org/machine-learning/catboost-parameters-and-hyperparameters/
- https://catboost.ai/docs/en/references/training-parameters/common
- https://catboost.ai/docs/en/concepts/python-reference_catboostclassifier
- https://github.com/catboost/catboost/blob/master/catboost/tutorials/hyperparameters_tuning/hyperparameters_tuning.ipynb
- https://github.com/optuna/optuna-examples/blob/main/catboost/catboost_pruning.py
- https://optuna-integration.readthedocs.io/en/latest/reference/generated/optuna_integration.CatBoostPruningCallback.html
- https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html
- https://optuna.readthedocs.io/en/stable/reference/pruners.html
- https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html
- https://stackoverflow.com/questions/69446166/a-question-about-the-n-trials-in-optuna