# 14 CatBoost Hyperparameter Optimisierung Optuna (on 100%)

## Import

In [1]:
import time

import numpy as np
import pandas as pd

from sklearn.datasets import fetch_openml
from sklearn.metrics import roc_auc_score

import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner

from optuna_integration import CatBoostPruningCallback

from catboost import CatBoostClassifier

import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
mpl.style.use("seaborn-v0_8-colorblind")
RANDOM_STATE = 42

## Dataframe

In [3]:
df_raw = fetch_openml(data_id=42742, as_frame=True).frame

In [4]:
feat_cols = [col for col in df_raw.columns if col not in ("target",)]
cat_cols = [col for col in feat_cols if col.endswith("_cat")]
bin_cols = [col for col in feat_cols if col.endswith("_bin")]
num_cols = [col for col in feat_cols if col not in cat_cols and col not in bin_cols]

for col in cat_cols:
    df_raw[col] = df_raw[col].astype("category")

for col in bin_cols:
    if df_raw[col].isna().sum() == 0:
        df_raw[col] = df_raw[col].astype(int).astype("bool")
    else:
        df_raw[col] = df_raw[col].astype("Int8")

for col in num_cols:
    df_raw[col] = df_raw[col].astype("float32")

df_raw["target"] = df_raw["target"].astype(int).astype("bool")

idx_train = np.load("../../../data/processed/train_idx.npy")
idx_val = np.load("../../../data/processed/val_idx.npy")
idx_test = np.load("../../../data/processed/test_idx.npy")

df_train = df_raw.iloc[idx_train]
df_val = df_raw.iloc[idx_val]
df_test = df_raw.iloc[idx_test]

x_train, y_train = df_train[feat_cols], df_train["target"]
x_val, y_val = df_val[feat_cols], df_val["target"]
x_test, y_test = df_test[feat_cols], df_test["target"]
x_full, y_full = df_raw[feat_cols], df_raw["target"]

pd.Series(
    {
        "train": [len(df_train), len(x_train), len(y_train)],
        "val": [len(df_val), len(x_val), len(y_val)],
        "test": [len(df_test), len(x_test), len(y_test)],
        "full": [len(df_raw), len(x_full), len(y_full)]
    }
)

train    [476168, 476168, 476168]
val         [59522, 59522, 59522]
test        [59522, 59522, 59522]
full     [595212, 595212, 595212]
dtype: object

## Hilfsvariablen

In [5]:
calc_cols = [c for c in feat_cols if c.startswith("ps_calc_")]

mv_cols = ["ps_car_03_cat", "ps_car_05_cat", "ps_reg_03", "ps_car_14"]

num_cols_no_calc = [c for c in num_cols if c not in calc_cols]
bin_cols_no_calc = [c for c in bin_cols if c not in calc_cols]
feat_cols_no_calc = [c for c in feat_cols if c not in calc_cols]

high_kard_cols = ["ps_car_11_cat"]
low_kard_cols = [c for c in cat_cols if c not in high_kard_cols]

In [6]:
def eval_modell(mod_idx, model, x_train, y_train, x_val, y_val, train_time, best_iter=None):
    """AUC auf Train und Val"""
    auc_train = roc_auc_score(y_train, model.predict_proba(x_train)[:, 1])
    auc_val = roc_auc_score(y_val, model.predict_proba(x_val)[:, 1])
    return {
        "model_idx": mod_idx,
        "auc_train": auc_train,
        "auc_val": auc_val,
        "gini": 2 * auc_val - 1,
        "delta_auc": auc_train - auc_val,
        "best_iter": best_iter,
        "trainingszeit": train_time
    }

In [7]:
def mv_for_cb(df, fill_var="missing"):
    """df copy mit ersetzten nans"""
    outs = df.copy()
    for col in outs.columns:
        if outs[col].dtype.name == "category":
            if fill_var not in outs[col].cat.categories:
                outs[col] = outs[col].cat.add_categories([fill_var])
            outs[col] = outs[col].fillna(fill_var)
    return outs

In [8]:
x_train_cb = mv_for_cb(x_train)
x_val_cb = mv_for_cb(x_val)
x_test_cb = mv_for_cb(x_test)
x_full_cb = mv_for_cb(x_full)

x_train_no_calc_cb = x_train_cb[feat_cols_no_calc]
x_val_no_calc_cb = x_val_cb[feat_cols_no_calc]
x_test_no_calc_cb = x_test_cb[feat_cols_no_calc]
x_full_no_calc_cb = x_full_cb[feat_cols_no_calc]

pd.Series(
    {
        "train": [len(x_train_cb), len(x_train_no_calc_cb)],
        "val": [len(x_val_cb), len(x_val_no_calc_cb)],
        "test": [len(x_test_cb), len(x_test_no_calc_cb)],
        "full": [len(x_full_cb), len(x_full_no_calc_cb)]
    }
)

train    [476168, 476168]
val        [59522, 59522]
test       [59522, 59522]
full     [595212, 595212]
dtype: object

## Optuna Hilfe

## Suchräume

|Paramerter|Bereich|
|---|---|
|learning rate|0.01-0.3|
|depth|4-10|
|l2_leaf_reg|1-30|
|random_strength|1e3-10|
|bootstrap_type|Bayesian / Bernoulli / MVS|
|bagging_temperature|0-5|
|one_hot_max_size|2-105|
|leaf_estimation_iterations|1-10|
|auto_class_weights|none / Balanced|

In [9]:
fixed_params_plain = {
    "random_seed": RANDOM_STATE,
    "task_type": "CPU",
    "eval_metric": "AUC",
    "thread_count": -1,
    "allow_writing_files": False,
    "cat_features": cat_cols,
    "use_best_model": True,
    "early_stopping_rounds": 100,
    "loss_function": "Logloss",
    "border_count": 254,
    "verbose": 0,
    "iterations": 5000,
    "boosting_type": "Plain"
}

In [10]:
fixed_params_ordered = {
    "random_seed": RANDOM_STATE,
    "task_type": "CPU",
    "eval_metric": "AUC",
    "thread_count": -1,
    "allow_writing_files": False,
    "cat_features": cat_cols,
    "use_best_model": True,
    "early_stopping_rounds": 100,
    "loss_function": "Logloss",
    "border_count": 254,
    "verbose": 0,
    "iterations": 5000,
    "boosting_type": "Ordered"
}

In [11]:
def suchraum_params(trial):
    """Suchraum definition"""
    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "depth": trial.suggest_int("depth", 4, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1.0, 30.0, log=True),
        "random_strength": trial.suggest_float("random_strength", 1e-3, 10.0, log=True),
        "one_hot_max_size": trial.suggest_categorical("one_hot_max_size", [2, 10, 18, 105]),
        "leaf_estimation_iterations": trial.suggest_int("leaf_estimation_iterations", 1, 10),
        "auto_class_weights": trial.suggest_categorical("auto_class_weights", [None, "Balanced"]),
        "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli", "MVS"])
    }

    if params["bootstrap_type"] == "Bayesian":
        params["bagging_temperature"] = trial.suggest_float("bagging_temperature", 0.0, 5.0)
    else:
        params["subsample"] = trial.suggest_float("subsample", 0.5, 1.0)

    return params

## Plain mit Calc

In [12]:
def objective_plain_calc_full(trial):
    modell = CatBoostClassifier(
        **fixed_params_plain,
        **suchraum_params(trial)
    )
    pruning_callback = CatBoostPruningCallback(trial, "AUC")

    modell.fit(x_train_cb, y_train, eval_set=[(x_val_cb, y_val)], callbacks=[pruning_callback])
    pruning_callback.check_pruned()

    return roc_auc_score(y_val, modell.predict_proba(x_val_cb)[:, 1])

In [13]:
study_plain_with_calc_full = optuna.create_study(
    study_name = "CatBoost_Plain_with_calc_full",
    storage = "sqlite:///catboost_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=200)
)

[I 2026-08-13 13:48:09,103] A new study created in RDB with name: CatBoost_Plain_with_calc_full

In [14]:
study_plain_with_calc_full.optimize(
    objective_plain_calc_full,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 13:49:37,345] Trial 0 finished with value: 0.6307018491365225 and parameters: {'learning_rate': 0.03574712922600244, 'depth': 10, 'l2_leaf_reg': 12.057126287443763, 'random_strength': 0.24810409748678125, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.9091248360355031}. Best is trial 0 with value: 0.6307018491365225.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 13:53:52,364] Trial 1 finished with value: 0.633360077191187 and parameters: {'learning_rate': 0.018659959624904916, 'depth': 6, 'l2_leaf_reg': 5.958389350068956, 'random_strength': 0.05342937261279776, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.5232252063599989}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 13:56:50,389] Trial 2 finished with value: 0.6295687661644128 and parameters: {'learning_rate': 0.07896186801026692, 'depth': 5, 'l2_leaf_reg': 1.2476394272569447, 'random_strength': 6.245139574743075, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.6293899908000085}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 13:57:57,478] Trial 3 finished with value: 0.6299498152942278 and parameters: {'learning_rate': 0.09519754482692679, 'depth': 6, 'l2_leaf_reg': 5.864129169696525, 'random_strength': 0.1537592023548176, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6626651653816322}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 13:58:52,696] Trial 4 finished with value: 0.6294304768901163 and parameters: {'learning_rate': 0.03750796359625606, 'depth': 5, 'l2_leaf_reg': 16.755052359850303, 'random_strength': 0.026730883107816707, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.8534286719238086}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 13:59:21,898] Trial 5 finished with value: 0.6289542739999195 and parameters: {'learning_rate': 0.11935262708510537, 'depth': 9, 'l2_leaf_reg': 1.286390810198991, 'random_strength': 0.02715581955282941, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7361074625809747}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:23:08,580] Trial 6 finished with value: 0.6274211384774033 and parameters: {'learning_rate': 0.015019490572374374, 'depth': 8, 'l2_leaf_reg': 13.297554090738672, 'random_strength': 0.17583640270008521, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 4.537832369630465}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:23:45,804] Trial 7 finished with value: 0.6312746768640758 and parameters: {'learning_rate': 0.02334720250903525, 'depth': 6, 'l2_leaf_reg': 13.062931388340921, 'random_strength': 0.008226074946221037, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7696711209578253}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:24:07,421] Trial 8 finished with value: 0.6301273172105065 and parameters: {'learning_rate': 0.1558428978238547, 'depth': 10, 'l2_leaf_reg': 2.949372944095385, 'random_strength': 0.002755546207779663, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.9714548519562596}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:37:46,118] Trial 9 finished with value: 0.6286579605115833 and parameters: {'learning_rate': 0.030019946952402964, 'depth': 7, 'l2_leaf_reg': 10.925573591447922, 'random_strength': 0.02847858516856297, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.3932323211830573}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:38:17,269] Trial 10 finished with value: 0.6331905657148694 and parameters: {'learning_rate': 0.25441416790751953, 'depth': 4, 'l2_leaf_reg': 27.047297227177754, 'random_strength': 5.359957765771775, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5248259995479624}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:38:44,561] Trial 11 finished with value: 0.6296665164158485 and parameters: {'learning_rate': 0.29427550404323227, 'depth': 4, 'l2_leaf_reg': 24.950292438859467, 'random_strength': 6.190548092869249, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5024168892606999}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:39:04,543] Trial 12 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:39:31,373] Trial 13 finished with value: 0.6252855929143993 and parameters: {'learning_rate': 0.29596284206078805, 'depth': 6, 'l2_leaf_reg': 28.118760496047877, 'random_strength': 0.962852247027322, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5817565488531816}. Best is trial 1 with value: 0.633360077191187.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:41:06,708] Trial 14 finished with value: 0.6338146399763785 and parameters: {'learning_rate': 0.06338750302989393, 'depth': 5, 'l2_leaf_reg': 2.430516929648288, 'random_strength': 0.0011888525233311397, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5657526432159653}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:41:41,673] Trial 15 finished with value: 0.6280274874671679 and parameters: {'learning_rate': 0.054761008302518364, 'depth': 7, 'l2_leaf_reg': 2.2396686912858104, 'random_strength': 0.0011065136021090993, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.6020116544034899}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:43:01,673] Trial 16 finished with value: 0.6320500469711663 and parameters: {'learning_rate': 0.06430771824478079, 'depth': 5, 'l2_leaf_reg': 5.558579067292345, 'random_strength': 0.007963058363330307, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6863387125611958}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:45:34,775] Trial 17 finished with value: 0.631031177450734 and parameters: {'learning_rate': 0.020655958307775498, 'depth': 7, 'l2_leaf_reg': 2.6657976518184223, 'random_strength': 0.005062211604639415, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.5712468789525892}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:46:12,962] Trial 18 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:46:43,224] Trial 19 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:47:34,874] Trial 20 finished with value: 0.6326466289744592 and parameters: {'learning_rate': 0.16161445557774803, 'depth': 6, 'l2_leaf_reg': 1.715903546303226, 'random_strength': 0.8131095290595369, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6798255348913913}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:48:08,882] Trial 21 finished with value: 0.6310401566473502 and parameters: {'learning_rate': 0.19215293084840904, 'depth': 4, 'l2_leaf_reg': 8.10926215973725, 'random_strength': 2.3115171147632756, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 5, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5313961714106215}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:48:29,941] Trial 22 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:49:13,129] Trial 23 finished with value: 0.6320461160605616 and parameters: {'learning_rate': 0.11883834866827832, 'depth': 5, 'l2_leaf_reg': 3.7769631122629024, 'random_strength': 0.06574566121950637, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6217550058005971}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:50:00,430] Trial 24 finished with value: 0.6323531290213206 and parameters: {'learning_rate': 0.19685490223416638, 'depth': 4, 'l2_leaf_reg': 1.890856191844742, 'random_strength': 2.7466854809502967, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 3, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5083651991137286}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:50:52,370] Trial 25 finished with value: 0.6316601633408309 and parameters: {'learning_rate': 0.07656005892965895, 'depth': 5, 'l2_leaf_reg': 7.665308109271201, 'random_strength': 0.002387802477727909, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.56295154335765}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:51:19,257] Trial 26 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:52:05,248] Trial 27 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:52:44,643] Trial 28 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:52:53,545] Trial 29 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:53:24,435] Trial 30 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:54:02,820] Trial 31 finished with value: 0.6314366882594238 and parameters: {'learning_rate': 0.22089878834016985, 'depth': 6, 'l2_leaf_reg': 1.8109201556541348, 'random_strength': 0.7993181059122649, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.7191398220107695}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:54:53,254] Trial 32 finished with value: 0.6309938378193263 and parameters: {'learning_rate': 0.1595724737142096, 'depth': 5, 'l2_leaf_reg': 1.568985051883073, 'random_strength': 8.511372040313388, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.8111630092146314}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:55:22,686] Trial 33 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:56:30,381] Trial 34 finished with value: 0.6314439954122656 and parameters: {'learning_rate': 0.14660804122144333, 'depth': 6, 'l2_leaf_reg': 1.4126271604026748, 'random_strength': 2.2954776430419965, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.5874322982238879}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:57:22,206] Trial 35 finished with value: 0.6334233736944604 and parameters: {'learning_rate': 0.08337510856158523, 'depth': 5, 'l2_leaf_reg': 1.0994582369948818, 'random_strength': 0.14195151535629463, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.532852157900372}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 14:58:15,369] Trial 36 pruned. Trial was pruned at iteration 241.
[I 2026-08-13 14:58:36,502] Trial 37 pruned. Trial was pruned at iteration 202.
[I 2026-08-13 14:58:44,587] Trial 38 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 14:59:07,562] Trial 39 pruned. Trial was pruned at iteration 202.
[I 2026-08-13 15:00:37,779] Trial 40 pruned. Trial was pruned at iteration 202.
[I 2026-08-13 15:01:37,131] Trial 41 finished with value: 0.631832721473834 and parameters: {'learning_rate': 0.062047833177577796, 'depth': 6, 'l2_leaf_reg': 1.5088728957811488, 'random_strength': 0.24472889648788568, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 2, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.8951174073552459}. Best is trial 14 with value: 0.6338146399763785.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\2264105452.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:02:06,326] Trial 42 finished with value: 0.6275277634227193 and parameters: {'learning_rate': 0.13365681659888387, 'depth': 7, 'l2_leaf_reg': 1.2135047478532761, 'random_strength': 0.6240697997397237, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.667596406991307}. Best is trial 14 with value: 0.6338146399763785.

In [15]:
pd.DataFrame({
    "best auc_val": study_plain_with_calc_full.best_value,
    "best gini": 2 * study_plain_with_calc_full.best_value - 1,
    "trials": len(study_plain_with_calc_full.trials),
    "pruned": len([t for t in study_plain_with_calc_full.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_plain_with_calc_full.trials if t.state.name == "FAIL"]),
    "best params": study_plain_with_calc_full.best_params
})

,best auc_val,best gini,trials,pruned,fail,best params
learning_rate,0.633815,0.267629,50,17,0,0.063388
depth,0.633815,0.267629,50,17,0,5
l2_leaf_reg,0.633815,0.267629,50,17,0,2.430517
random_strength,0.633815,0.267629,50,17,0,0.001189
one_hot_max_size,0.633815,0.267629,50,17,0,10
leaf_estimation_iterations,0.633815,0.267629,50,17,0,3
auto_class_weights,0.633815,0.267629,50,17,0,Balanced
bootstrap_type,0.633815,0.267629,50,17,0,Bernoulli
subsample,0.633815,0.267629,50,17,0,0.565753

## Plain ohne Calc

In [16]:
def objective_plain_no_calc_full(trial):
    modell = CatBoostClassifier(
        **fixed_params_plain,
        **suchraum_params(trial)
    )
    pruning_callback = CatBoostPruningCallback(trial, "AUC")

    modell.fit(x_train_no_calc_cb, y_train, eval_set=[(x_val_no_calc_cb, y_val)], callbacks=[pruning_callback])
    pruning_callback.check_pruned()

    return roc_auc_score(y_val, modell.predict_proba(x_val_no_calc_cb)[:, 1])

In [17]:
study_plain_without_calc_full = optuna.create_study(
    study_name = "CatBoost_Plain_without_calc_full",
    storage = "sqlite:///catboost_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=200)
)

[I 2026-08-13 15:06:02,132] A new study created in RDB with name: CatBoost_Plain_without_calc_full

In [18]:
study_plain_without_calc_full.optimize(
    objective_plain_no_calc_full,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:07:39,202] Trial 0 finished with value: 0.6353305486248135 and parameters: {'learning_rate': 0.03574712922600244, 'depth': 10, 'l2_leaf_reg': 12.057126287443763, 'random_strength': 0.24810409748678125, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.9091248360355031}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:10:18,185] Trial 1 finished with value: 0.6327083016659898 and parameters: {'learning_rate': 0.018659959624904916, 'depth': 6, 'l2_leaf_reg': 5.958389350068956, 'random_strength': 0.05342937261279776, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.5232252063599989}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:13:58,282] Trial 2 finished with value: 0.6299605549600106 and parameters: {'learning_rate': 0.07896186801026692, 'depth': 5, 'l2_leaf_reg': 1.2476394272569447, 'random_strength': 6.245139574743075, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.6293899908000085}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:14:40,107] Trial 3 finished with value: 0.6328339782639293 and parameters: {'learning_rate': 0.09519754482692679, 'depth': 6, 'l2_leaf_reg': 5.864129169696525, 'random_strength': 0.1537592023548176, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6626651653816322}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:17:27,332] Trial 4 finished with value: 0.6325339107157724 and parameters: {'learning_rate': 0.03750796359625606, 'depth': 5, 'l2_leaf_reg': 16.755052359850303, 'random_strength': 0.026730883107816707, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.8534286719238086}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:18:04,605] Trial 5 finished with value: 0.6274953675745871 and parameters: {'learning_rate': 0.11935262708510537, 'depth': 9, 'l2_leaf_reg': 1.286390810198991, 'random_strength': 0.02715581955282941, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7361074625809747}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:42:24,668] Trial 6 finished with value: 0.6335096366836178 and parameters: {'learning_rate': 0.015019490572374374, 'depth': 8, 'l2_leaf_reg': 13.297554090738672, 'random_strength': 0.17583640270008521, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 4.537832369630465}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:43:12,784] Trial 7 finished with value: 0.6332357993221743 and parameters: {'learning_rate': 0.02334720250903525, 'depth': 6, 'l2_leaf_reg': 13.062931388340921, 'random_strength': 0.008226074946221037, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7696711209578253}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:43:37,492] Trial 8 finished with value: 0.6336632958987652 and parameters: {'learning_rate': 0.1558428978238547, 'depth': 10, 'l2_leaf_reg': 2.949372944095385, 'random_strength': 0.002755546207779663, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.9714548519562596}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:58:29,236] Trial 9 finished with value: 0.6328602486440027 and parameters: {'learning_rate': 0.030019946952402964, 'depth': 7, 'l2_leaf_reg': 10.925573591447922, 'random_strength': 0.02847858516856297, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.3932323211830573}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 15:59:20,978] Trial 10 finished with value: 0.6348059690065625 and parameters: {'learning_rate': 0.2544068995955869, 'depth': 4, 'l2_leaf_reg': 27.047297227177754, 'random_strength': 5.359957765771775, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 6, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.25806078833796153}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:00:22,385] Trial 11 finished with value: 0.6341472963007952 and parameters: {'learning_rate': 0.29500203186219026, 'depth': 4, 'l2_leaf_reg': 26.813599307015753, 'random_strength': 7.0041443144661555, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 6, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.15727489608551082}. Best is trial 0 with value: 0.6353305486248135.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:01:11,377] Trial 12 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:03:04,257] Trial 13 finished with value: 0.6364019990987524 and parameters: {'learning_rate': 0.05445057683691509, 'depth': 8, 'l2_leaf_reg': 7.076480471311773, 'random_strength': 0.8387744815011882, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 5, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.8158099900059381}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:03:39,596] Trial 14 finished with value: 0.633697098514496 and parameters: {'learning_rate': 0.05316380516382915, 'depth': 8, 'l2_leaf_reg': 6.732321194046503, 'random_strength': 0.7340900778459258, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.9254321473620877}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:04:20,996] Trial 15 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:04:32,717] Trial 16 pruned. Trial was pruned at iteration 212.
[I 2026-08-13 16:06:16,568] Trial 17 finished with value: 0.6355731557455641 and parameters: {'learning_rate': 0.06834487145135539, 'depth': 8, 'l2_leaf_reg': 8.389012487233568, 'random_strength': 1.9279070384709986, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 3, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 2.021013668060606}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:06:45,000] Trial 18 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:07:14,405] Trial 19 pruned. Trial was pruned at iteration 211.
[I 2026-08-13 16:08:02,901] Trial 20 pruned. Trial was pruned at iteration 338.
[I 2026-08-13 16:08:55,600] Trial 21 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:09:07,092] Trial 22 pruned. Trial was pruned at iteration 205.
[I 2026-08-13 16:10:32,715] Trial 23 finished with value: 0.6337081436498144 and parameters: {'learning_rate': 0.0694735499935331, 'depth': 8, 'l2_leaf_reg': 9.701544808702586, 'random_strength': 1.2646359724174814, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 8, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.9740840450095323}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:11:07,038] Trial 24 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:11:54,904] Trial 25 finished with value: 0.6359757002842885 and parameters: {'learning_rate': 0.054782420114662896, 'depth': 7, 'l2_leaf_reg': 17.066989126353967, 'random_strength': 0.4213988723242522, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 5, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8190253690047185}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:12:53,634] Trial 26 pruned. Trial was pruned at iteration 330.
[I 2026-08-13 16:13:55,903] Trial 27 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:15:00,307] Trial 28 finished with value: 0.6346418032471203 and parameters: {'learning_rate': 0.13144940718283563, 'depth': 7, 'l2_leaf_reg': 8.671069138924357, 'random_strength': 0.4856225211564218, 'one_hot_max_size': 18, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.7870840765614774}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:15:12,188] Trial 29 finished with value: 0.6330559099203137 and parameters: {'learning_rate': 0.20131894511659193, 'depth': 8, 'l2_leaf_reg': 12.479803775965994, 'random_strength': 0.10005588886427291, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.997833986580405}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:15:20,746] Trial 30 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:16:38,963] Trial 31 finished with value: 0.6350385117099777 and parameters: {'learning_rate': 0.06108750943445127, 'depth': 10, 'l2_leaf_reg': 21.741034430598393, 'random_strength': 1.2443602535091407, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 8, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 3.3033069877390675}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:16:48,028] Trial 32 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:17:16,902] Trial 33 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:17:25,313] Trial 34 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:18:51,362] Trial 35 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:19:23,940] Trial 36 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:19:33,269] Trial 37 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:21:07,152] Trial 38 pruned. Trial was pruned at iteration 492.
[I 2026-08-13 16:21:21,387] Trial 39 pruned. Trial was pruned at iteration 302.
[I 2026-08-13 16:22:26,183] Trial 40 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:23:49,017] Trial 41 finished with value: 0.6359698963631094 and parameters: {'learning_rate': 0.0631299706164084, 'depth': 10, 'l2_leaf_reg': 23.88864418682232, 'random_strength': 1.211382555857048, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 8, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 3.6054524809956736}. Best is trial 13 with value: 0.6364019990987524.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\568654475.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:24:13,417] Trial 42 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:24:37,666] Trial 43 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:25:01,002] Trial 44 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:25:11,481] Trial 45 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:25:51,596] Trial 46 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:26:14,802] Trial 47 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 16:27:04,918] Trial 48 pruned. Trial was pruned at iteration 252.
[I 2026-08-13 16:27:44,040] Trial 49 pruned. Trial was pruned at iteration 200.

In [19]:
pd.Series({
    "best auc_val": study_plain_without_calc_full.best_value,
    "best gini": 2 * study_plain_without_calc_full.best_value - 1,
    "trials": len(study_plain_without_calc_full.trials),
    "pruned": len([t for t in study_plain_without_calc_full.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_plain_without_calc_full.trials if t.state.name == "FAIL"]),
    "best params": study_plain_without_calc_full.best_params
})

best auc_val                                             0.636402
best gini                                                0.272804
trials                                                         50
pruned                                                         29
fail                                                            0
best params     {'learning_rate': 0.05445057683691509, 'depth'...
dtype: object

In [20]:
study_plain_without_calc_full.best_params

{'learning_rate': 0.05445057683691509,
 'depth': 8,
 'l2_leaf_reg': 7.076480471311773,
 'random_strength': 0.8387744815011882,
 'one_hot_max_size': 18,
 'leaf_estimation_iterations': 5,
 'auto_class_weights': None,
 'bootstrap_type': 'Bayesian',
 'bagging_temperature': 1.8158099900059381}

## Ordered ohne Calc

In [21]:
def objective_ordered_no_calc_full(trial):
    modell = CatBoostClassifier(
        **fixed_params_ordered,
        **suchraum_params(trial)
    )
    pruning_callback = CatBoostPruningCallback(trial, "AUC")

    modell.fit(x_train_no_calc_cb, y_train, eval_set=[(x_val_no_calc_cb, y_val)], callbacks=[pruning_callback])
    pruning_callback.check_pruned()

    return roc_auc_score(y_val, modell.predict_proba(x_val_no_calc_cb)[:, 1])

In [22]:
study_ordered_without_calc_full = optuna.create_study(
    study_name = "CatBoost_Ordered_without_calc_full",
    storage = "sqlite:///catboost_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=200)
)

[I 2026-08-13 16:27:44,274] A new study created in RDB with name: CatBoost_Ordered_without_calc_full

In [23]:
study_ordered_without_calc_full.optimize(
    objective_ordered_no_calc_full,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:39:06,758] Trial 0 finished with value: 0.6317207829663305 and parameters: {'learning_rate': 0.03574712922600244, 'depth': 10, 'l2_leaf_reg': 12.057126287443763, 'random_strength': 0.24810409748678125, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.9091248360355031}. Best is trial 0 with value: 0.6317207829663305.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:40:58,411] Trial 1 finished with value: 0.6296060656024607 and parameters: {'learning_rate': 0.018659959624904916, 'depth': 6, 'l2_leaf_reg': 5.958389350068956, 'random_strength': 0.05342937261279776, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 4, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.5232252063599989}. Best is trial 0 with value: 0.6317207829663305.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:45:29,810] Trial 2 finished with value: 0.6305436400330271 and parameters: {'learning_rate': 0.07896186801026692, 'depth': 5, 'l2_leaf_reg': 1.2476394272569447, 'random_strength': 6.245139574743075, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 7, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.6293899908000085}. Best is trial 0 with value: 0.6317207829663305.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:47:32,736] Trial 3 finished with value: 0.6321803216894858 and parameters: {'learning_rate': 0.09519754482692679, 'depth': 6, 'l2_leaf_reg': 5.864129169696525, 'random_strength': 0.1537592023548176, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6626651653816322}. Best is trial 3 with value: 0.6321803216894858.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:48:55,453] Trial 4 finished with value: 0.6310688064743335 and parameters: {'learning_rate': 0.03750796359625606, 'depth': 5, 'l2_leaf_reg': 16.755052359850303, 'random_strength': 0.026730883107816707, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.8534286719238086}. Best is trial 3 with value: 0.6321803216894858.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 16:50:04,659] Trial 5 finished with value: 0.6269197705245323 and parameters: {'learning_rate': 0.11935262708510537, 'depth': 9, 'l2_leaf_reg': 1.286390810198991, 'random_strength': 0.02715581955282941, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 1, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7361074625809747}. Best is trial 3 with value: 0.6321803216894858.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 18:07:59,412] Trial 6 finished with value: 0.6334691941248208 and parameters: {'learning_rate': 0.015019490572374374, 'depth': 8, 'l2_leaf_reg': 13.297554090738672, 'random_strength': 0.17583640270008521, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 4.537832369630465}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 18:09:31,655] Trial 7 finished with value: 0.627939198732668 and parameters: {'learning_rate': 0.02334720250903525, 'depth': 6, 'l2_leaf_reg': 13.062931388340921, 'random_strength': 0.008226074946221037, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'MVS', 'subsample': 0.7696711209578253}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 18:11:57,864] Trial 8 finished with value: 0.6319214442966212 and parameters: {'learning_rate': 0.1558428978238547, 'depth': 10, 'l2_leaf_reg': 2.949372944095385, 'random_strength': 0.002755546207779663, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.9714548519562596}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:02:13,192] Trial 9 finished with value: 0.6318845628695172 and parameters: {'learning_rate': 0.030019946952402964, 'depth': 7, 'l2_leaf_reg': 10.925573591447922, 'random_strength': 0.02847858516856297, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 4, 'auto_class_weights': None, 'bootstrap_type': 'Bayesian', 'bagging_temperature': 1.3932323211830573}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:03:19,302] Trial 10 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:05:04,507] Trial 11 finished with value: 0.6288392406036988 and parameters: {'learning_rate': 0.28166124941677534, 'depth': 4, 'l2_leaf_reg': 4.776978233510026, 'random_strength': 0.42542470405011734, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 10, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5070961151457483}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:10:49,371] Trial 12 finished with value: 0.631679753584478 and parameters: {'learning_rate': 0.05879970831903129, 'depth': 8, 'l2_leaf_reg': 6.3272733167425566, 'random_strength': 0.526166497962489, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 6, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9903481067957725}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:11:36,725] Trial 13 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:13:28,712] Trial 14 finished with value: 0.6289171272966395 and parameters: {'learning_rate': 0.27608283973621234, 'depth': 8, 'l2_leaf_reg': 28.770234490461362, 'random_strength': 1.636795219492306, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 8, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8705765955899739}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:16:14,142] Trial 15 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:17:58,119] Trial 16 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:18:59,601] Trial 17 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:19:53,421] Trial 18 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:20:59,981] Trial 19 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:22:41,229] Trial 20 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:24:09,636] Trial 21 finished with value: 0.6294293675533812 and parameters: {'learning_rate': 0.19215293084840904, 'depth': 10, 'l2_leaf_reg': 2.005665021173009, 'random_strength': 0.0020768665554523765, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'MVS', 'subsample': 0.9880953697780657}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:28:53,223] Trial 22 finished with value: 0.6330768988928877 and parameters: {'learning_rate': 0.12171840272734935, 'depth': 10, 'l2_leaf_reg': 3.197470386409182, 'random_strength': 0.008015721194036651, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.906708728779495}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:31:01,771] Trial 23 finished with value: 0.6307893581198389 and parameters: {'learning_rate': 0.09600825479015597, 'depth': 9, 'l2_leaf_reg': 4.128925910480677, 'random_strength': 0.009636708475048883, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8875784180765833}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:32:24,752] Trial 24 finished with value: 0.6320615583494603 and parameters: {'learning_rate': 0.12127708351852082, 'depth': 8, 'l2_leaf_reg': 6.572164356539712, 'random_strength': 0.055814052566859444, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 3, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8055110742746786}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:34:17,231] Trial 25 finished with value: 0.6292653143353469 and parameters: {'learning_rate': 0.18678597314814038, 'depth': 7, 'l2_leaf_reg': 2.2796444754249516, 'random_strength': 0.18956128337625625, 'one_hot_max_size': 10, 'leaf_estimation_iterations': 5, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.6803063384432332}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:38:35,126] Trial 26 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:39:38,195] Trial 27 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:40:24,477] Trial 28 finished with value: 0.6192064517223848 and parameters: {'learning_rate': 0.11273322653216135, 'depth': 6, 'l2_leaf_reg': 1.6171802810941245, 'random_strength': 0.3596446207648625, 'one_hot_max_size': 2, 'leaf_estimation_iterations': 9, 'auto_class_weights': 'Balanced', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.3135794905348237}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:42:36,522] Trial 29 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:43:41,565] Trial 30 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:44:46,177] Trial 31 finished with value: 0.6309859438434291 and parameters: {'learning_rate': 0.12416742305224979, 'depth': 8, 'l2_leaf_reg': 6.5190622931022535, 'random_strength': 0.06176645943239258, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 3, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8031693078937754}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:46:10,721] Trial 32 finished with value: 0.6328873389686194 and parameters: {'learning_rate': 0.23744168377425612, 'depth': 7, 'l2_leaf_reg': 11.589280345843626, 'random_strength': 0.01800166544524237, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8382656388643585}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:46:51,146] Trial 33 finished with value: 0.6322822842050457 and parameters: {'learning_rate': 0.24514668667247863, 'depth': 6, 'l2_leaf_reg': 13.390205135430117, 'random_strength': 0.020442719373363703, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8290320671750591}. Best is trial 6 with value: 0.6334691941248208.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:47:41,970] Trial 34 finished with value: 0.6344766487310229 and parameters: {'learning_rate': 0.21647264801000893, 'depth': 7, 'l2_leaf_reg': 14.18773180353138, 'random_strength': 0.014972807165820902, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8506514785371476}. Best is trial 34 with value: 0.6344766487310229.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:48:58,402] Trial 35 finished with value: 0.6320052554908209 and parameters: {'learning_rate': 0.20582451889390413, 'depth': 7, 'l2_leaf_reg': 21.045404866219307, 'random_strength': 0.01331952014263641, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 2, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.927881279774589}. Best is trial 34 with value: 0.6344766487310229.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:50:30,437] Trial 36 finished with value: 0.6344747837591206 and parameters: {'learning_rate': 0.15192211077510728, 'depth': 7, 'l2_leaf_reg': 22.585524589455698, 'random_strength': 0.004656152865419044, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8507972753963935}. Best is trial 34 with value: 0.6344766487310229.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:50:46,259] Trial 37 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:51:37,569] Trial 38 finished with value: 0.6323703800114175 and parameters: {'learning_rate': 0.1437374881911391, 'depth': 7, 'l2_leaf_reg': 14.8806076303635, 'random_strength': 0.0014777880758638662, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8924471917189747}. Best is trial 34 with value: 0.6344766487310229.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")
[I 2026-08-13 19:52:05,684] Trial 39 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:53:08,641] Trial 40 pruned. Trial was pruned at iteration 200.
[I 2026-08-13 19:53:53,930] Trial 41 pruned. Trial was pruned at iteration 258.
[I 2026-08-13 19:55:01,723] Trial 42 finished with value: 0.6342592508856425 and parameters: {'learning_rate': 0.16914723720871272, 'depth': 7, 'l2_leaf_reg': 11.865878361427175, 'random_strength': 0.03525468832396377, 'one_hot_max_size': 105, 'leaf_estimation_iterations': 1, 'auto_class_weights': None, 'bootstrap_type': 'Bernoulli', 'subsample': 0.8211887565272952}. Best is trial 34 with value: 0.6344766487310229.
C:\Users\linus\AppData\Local\Temp\ipykernel_26220\1778171121.py:6: ExperimentalWarning: CatBoostPruningCallback is experimental (supported from v3.0.0). The interface can change in the future.
  pruning_callback = CatBoostPruningCallback(trial, "AUC")

In [24]:
pd.Series({
    "best auc_val": study_ordered_without_calc_full.best_value,
    "best gini": 2 * study_ordered_without_calc_full.best_value - 1,
    "trials": len(study_ordered_without_calc_full.trials),
    "pruned": len([t for t in study_ordered_without_calc_full.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_ordered_without_calc_full.trials if t.state.name == "FAIL"]),
    "best params": study_ordered_without_calc_full.best_params
})

best auc_val                                             0.635504
best gini                                                0.271008
trials                                                         50
pruned                                                         19
fail                                                            0
best params     {'learning_rate': 0.10624277494598432, 'depth'...
dtype: object

In [25]:
study_ordered_without_calc_full.best_params

{'learning_rate': 0.10624277494598432,
 'depth': 7,
 'l2_leaf_reg': 18.039747295507677,
 'random_strength': 0.005187373722068937,
 'one_hot_max_size': 105,
 'leaf_estimation_iterations': 1,
 'auto_class_weights': None,
 'bootstrap_type': 'Bernoulli',
 'subsample': 0.8119454704358904}

## Load Study

In [27]:
study_plain_with_calc_full_loaded = optuna.load_study(
    study_name = "CatBoost_Plain_with_calc_full",
    storage = "sqlite:///catboost_opti.db"
)

In [28]:
study_plain_without_calc_full_loaded = optuna.load_study(
    study_name = "CatBoost_Plain_without_calc_full",
    storage = "sqlite:///catboost_opti.db"
)

In [29]:
study_ordered_without_calc_full_loaded = optuna.load_study(
    study_name = "CatBoost_Ordered_without_calc_full",
    storage = "sqlite:///catboost_opti.db"
)

## Best Params again

In [30]:
study_plain_with_calc_full_loaded.best_params

{'learning_rate': 0.06338750302989393,
 'depth': 5,
 'l2_leaf_reg': 2.430516929648288,
 'random_strength': 0.0011888525233311397,
 'one_hot_max_size': 10,
 'leaf_estimation_iterations': 3,
 'auto_class_weights': 'Balanced',
 'bootstrap_type': 'Bernoulli',
 'subsample': 0.5657526432159653}

In [31]:
study_plain_without_calc_full_loaded.best_params

{'learning_rate': 0.05445057683691509,
 'depth': 8,
 'l2_leaf_reg': 7.076480471311773,
 'random_strength': 0.8387744815011882,
 'one_hot_max_size': 18,
 'leaf_estimation_iterations': 5,
 'auto_class_weights': None,
 'bootstrap_type': 'Bayesian',
 'bagging_temperature': 1.8158099900059381}

In [32]:
study_ordered_without_calc_full_loaded.best_params

{'learning_rate': 0.10624277494598432,
 'depth': 7,
 'l2_leaf_reg': 18.039747295507677,
 'random_strength': 0.005187373722068937,
 'one_hot_max_size': 105,
 'leaf_estimation_iterations': 1,
 'auto_class_weights': None,
 'bootstrap_type': 'Bernoulli',
 'subsample': 0.8119454704358904}

## 100% Train

In [33]:
results = []
train_times = {}

In [34]:
name = "L_cb_opt_01_full"

L_cb_opt_01_full = CatBoostClassifier(
    **fixed_params_plain,
    **study_plain_with_calc_full_loaded.best_params
)

start = time.time()
L_cb_opt_01_full.fit(
    x_train_cb, y_train, 
    eval_set=(x_val_cb, y_val), 
    verbose=250
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_cb_opt_01_full, x_train_cb, y_train, x_val_cb, y_val, train_times[name], best_iter=L_cb_opt_01_full.get_best_iteration())
)

0:	test: 0.5920158	best: 0.5920158 (0)	total: 117ms	remaining: 9m 44s
250:	test: 0.6296309	best: 0.6298320 (236)	total: 29.3s	remaining: 9m 15s
500:	test: 0.6333300	best: 0.6333876 (474)	total: 1m	remaining: 9m 6s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.63381464
bestIteration = 623

Shrink model to first 624 iterations.

In [35]:
name = "L_cb_opt_02_full"

L_cb_opt_02_full = CatBoostClassifier(
    **fixed_params_plain,
    **study_plain_without_calc_full_loaded.best_params
)

start = time.time()
L_cb_opt_02_full.fit(
    x_train_no_calc_cb, y_train, 
    eval_set=(x_val_no_calc_cb, y_val), 
    verbose=250
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_cb_opt_02_full, x_train_no_calc_cb, y_train, x_val_no_calc_cb, y_val, train_times[name], best_iter=L_cb_opt_02_full.get_best_iteration())
)

0:	test: 0.5655829	best: 0.5655829 (0)	total: 177ms	remaining: 14m 43s
250:	test: 0.6320901	best: 0.6320901 (250)	total: 43.9s	remaining: 13m 49s
500:	test: 0.6358414	best: 0.6360036 (494)	total: 1m 27s	remaining: 13m 8s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6364019991
bestIteration = 558

Shrink model to first 559 iterations.

In [36]:
name = "L_cb_opt_03_full"

L_cb_opt_03_full = CatBoostClassifier(
    **fixed_params_ordered,
    **study_ordered_without_calc_full_loaded.best_params
)

start = time.time()
L_cb_opt_03_full.fit(
    x_train_no_calc_cb, y_train, 
    eval_set=(x_val_no_calc_cb, y_val), 
    verbose=250
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_cb_opt_03_full, x_train_no_calc_cb, y_train, x_val_no_calc_cb, y_val, train_times[name], best_iter=L_cb_opt_03_full.get_best_iteration())
)

0:	test: 0.5575105	best: 0.5575105 (0)	total: 92.3ms	remaining: 7m 41s
250:	test: 0.6324803	best: 0.6324939 (249)	total: 34.7s	remaining: 10m 56s
500:	test: 0.6345583	best: 0.6345583 (500)	total: 1m 9s	remaining: 10m 25s
750:	test: 0.6352451	best: 0.6353866 (732)	total: 1m 44s	remaining: 9m 51s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.6355038302
bestIteration = 789

Shrink model to first 790 iterations.

In [37]:
pd.DataFrame(results)

,model_idx,auc_train,auc_val,gini,delta_auc,best_iter,trainingszeit
0,L_cb_opt_01_full,0.696718,0.633815,0.267629,0.062904,623,88.705495
1,L_cb_opt_02_full,0.692775,0.636402,0.272804,0.056373,558,116.162328
2,L_cb_opt_03_full,0.685571,0.635504,0.271008,0.050067,789,124.465556

## Save Models

In [38]:
Modelle = [
    (L_cb_opt_01_full, "L_cb_opt_01_full"),
    (L_cb_opt_02_full, "L_cb_opt_02_full"),
    (L_cb_opt_03_full, "L_cb_opt_03_full")
]

for modell, name in Modelle:
    modell.save_model(f"{name}.cbm")

## Notizen
- Die Learning Curves zeigten kein definitives Plateau, also optimiere ich hier nochmal anhand des vollen train sets
- ich setze die zeitbegrenzung mal auf 4 stunden zur sicherheit