# 18 XGBoost Optuna mit target encoded ps_car_11_cat

## Import

In [11]:
import time

import numpy as np
import pandas as pd

from sklearn.datasets import fetch_openml
from sklearn.metrics import roc_auc_score

from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.preprocessing import TargetEncoder

import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner

from optuna_integration import XGBoostPruningCallback

from xgboost import XGBClassifier

import matplotlib as mpl
import matplotlib.pyplot as plt

In [12]:
mpl.style.use("seaborn-v0_8-colorblind")
RANDOM_STATE = 42

## Dataframe

In [13]:
df_raw = fetch_openml(data_id=42742, as_frame=True).frame

In [14]:
feat_cols = [col for col in df_raw.columns if col not in ("target",)]
cat_cols = [col for col in feat_cols if col.endswith("_cat")]
bin_cols = [col for col in feat_cols if col.endswith("_bin")]
num_cols = [col for col in feat_cols if col not in cat_cols and col not in bin_cols]

for col in cat_cols:
    df_raw[col] = df_raw[col].astype("category")

for col in bin_cols:
    if df_raw[col].isna().sum() == 0:
        df_raw[col] = df_raw[col].astype(int).astype("bool")
    else:
        df_raw[col] = df_raw[col].astype("Int8")

for col in num_cols:
    df_raw[col] = df_raw[col].astype("float32")

df_raw["target"] = df_raw["target"].astype(int).astype("bool")

idx_train = np.load("../../../data/processed/train_idx.npy")
idx_val = np.load("../../../data/processed/val_idx.npy")
idx_test = np.load("../../../data/processed/test_idx.npy")

df_train = df_raw.iloc[idx_train]
df_val = df_raw.iloc[idx_val]
df_test = df_raw.iloc[idx_test]

x_train, y_train = df_train[feat_cols], df_train["target"]
x_val, y_val = df_val[feat_cols], df_val["target"]
x_test, y_test = df_test[feat_cols], df_test["target"]
x_full, y_full = df_raw[feat_cols], df_raw["target"]

pd.Series(
    {
        "train": [len(df_train), len(x_train), len(y_train)],
        "val": [len(df_val), len(x_val), len(y_val)],
        "test": [len(df_test), len(x_test), len(y_test)],
        "full": [len(df_raw), len(x_full), len(y_full)]
    }
)

train    [476168, 476168, 476168]
val         [59522, 59522, 59522]
test        [59522, 59522, 59522]
full     [595212, 595212, 595212]
dtype: object

## Hilfsvariablen

In [15]:
calc_cols = [c for c in feat_cols if c.startswith("ps_calc_")]

mv_cols = ["ps_car_03_cat", "ps_car_05_cat", "ps_reg_03", "ps_car_14"]

num_cols_no_calc = [c for c in num_cols if c not in calc_cols]
bin_cols_no_calc = [c for c in bin_cols if c not in calc_cols]
feat_cols_no_calc = [c for c in feat_cols if c not in calc_cols]

high_kard_cols = ["ps_car_11_cat"]
low_kard_cols = [c for c in cat_cols if c not in high_kard_cols]

In [16]:
def eval_modell(mod_idx, model, x_train, y_train, x_val, y_val, train_time, best_iter=None):
    """AUC auf Train und Val"""
    auc_train = roc_auc_score(y_train, model.predict_proba(x_train)[:, 1])
    auc_val = roc_auc_score(y_val, model.predict_proba(x_val)[:, 1])
    return {
        "model_idx": mod_idx,
        "auc_train": auc_train,
        "auc_val": auc_val,
        "gini": 2 * auc_val - 1,
        "delta_auc": auc_train - auc_val,
        "best_iter": best_iter,
        "trainingszeit": train_time
    }

In [17]:
x_train_no_calc = x_train[feat_cols_no_calc]
x_val_no_calc = x_val[feat_cols_no_calc]
x_test_no_calc = x_test[feat_cols_no_calc]
x_full_no_calc = x_full[feat_cols_no_calc]

## Optuna Hilfe

## Suchräume

|Parameter|Bereich|
|---|---|
|learning_rate|0.01-0.1 (log)|
|max_depth|3-7|
|min_child_weight|1-200 (log)|
|gamma|1e-3-5 (log)|
|reg_lambda|0.1-100 (log)|
|reg_alpha|1e-3-10 (log)|
|max_delta_step|0-10|
|subsample|0.5-1.0|
|colsample_bynode|0.5-1.0|
|scale_pos_weight|1 / 5 / 27|
|max_cat_to_onehot|2 / 10 / 18|

In [18]:
fixed_params_xgb = {
    "random_state": RANDOM_STATE,
    "verbosity": 0,
    "device": "cpu",
    "n_jobs": -1,
    "tree_method": "hist",
    "objective": "binary:logistic",
    "eval_metric": "auc",
    "enable_categorical": True,
    "n_estimators": 3000,
    "early_stopping_rounds": 100
}

In [19]:
def suchraum_params(trial):
    """Suchraum definition"""
    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 7),
        "min_child_weight": trial.suggest_float("min_child_weight", 1.0, 200.0, log=True),
        "gamma": trial.suggest_float("gamma", 1e-3, 5.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.1, 100.0, log=True),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bynode": trial.suggest_float("colsample_bynode", 0.5, 1.0),
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [1, 5, 27]),
        "max_cat_to_onehot": trial.suggest_categorical("max_cat_to_onehot", [2, 10, 18]),
    }

    return params

In [20]:
targ_enc = TargetEncoder(cv=5, random_state=RANDOM_STATE)

x_train_te = x_train.copy()
x_val_te = x_val.copy()
x_test_te = x_test.copy()

x_train_te[high_kard_cols] = targ_enc.fit_transform(x_train[high_kard_cols], y_train)
x_val_te[high_kard_cols] = targ_enc.transform(x_val[high_kard_cols])
x_test_te[high_kard_cols] = targ_enc.transform(x_test[high_kard_cols])

x_train_no_calc_te = x_train_te[feat_cols_no_calc]
x_val_no_calc_te = x_val_te[feat_cols_no_calc]
x_test_no_calc_te = x_test_te[feat_cols_no_calc]

x_train_te[high_kard_cols].describe()

c:\Users\linus\anaconda3\envs\ADA\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:341: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(

       ps_car_11_cat
count  476168.000000
mean        0.036446
std         0.009676
min         0.016329
25%         0.028362
50%         0.034718
75%         0.044178
max         0.078113

## Mit Calc

In [21]:
def objective_xgb_calc_te(trial):
    pruning_callback = XGBoostPruningCallback(trial, "validation_0-auc")

    modell = XGBClassifier(
        **fixed_params_xgb,
        **suchraum_params(trial),
        callbacks=[pruning_callback]
    )

    modell.fit(x_train_te, y_train, eval_set=[(x_val_te, y_val)], verbose=0)

    return roc_auc_score(y_val, modell.predict_proba(x_val_te)[:, 1])

In [22]:
study_xgb_calc_te = optuna.create_study(
    study_name = "XGBoost_calc_te",
    storage = "sqlite:///xgboost_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=500)
)

[I 2026-08-18 15:21:53,462] A new study created in RDB with name: XGBoost_calc_te

In [23]:
study_xgb_calc_te.optimize(
    objective_xgb_calc_te,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

[I 2026-08-18 15:22:20,298] Trial 0 finished with value: 0.6327024093194189 and parameters: {'learning_rate': 0.023688639503640783, 'max_depth': 7, 'min_child_weight': 48.343714531846395, 'gamma': 0.16383993835282307, 'reg_lambda': 0.2938027938703535, 'reg_alpha': 0.004207053950287938, 'max_delta_step': 0, 'subsample': 0.9330880728874675, 'colsample_bynode': 0.8005575058716043, 'scale_pos_weight': 27, 'max_cat_to_onehot': 2}. Best is trial 0 with value: 0.6327024093194189.
[I 2026-08-18 15:24:28,919] Trial 1 finished with value: 0.634489474432188 and parameters: {'learning_rate': 0.015254729458052608, 'max_depth': 4, 'min_child_weight': 16.12427845856261, 'gamma': 0.039605150456850806, 'reg_lambda': 0.7476312062252299, 'reg_alpha': 0.2801635158716261, 'max_delta_step': 1, 'subsample': 0.6460723242676091, 'colsample_bynode': 0.6831809216468459, 'scale_pos_weight': 5, 'max_cat_to_onehot': 10}. Best is trial 1 with value: 0.634489474432188.
[I 2026-08-18 15:25:16,041] Trial 2 finished with value: 0.6323597729837228 and parameters: {'learning_rate': 0.04050837781329675, 'max_depth': 3, 'min_child_weight': 1.4115155493448333, 'gamma': 3.235185145617431, 'reg_lambda': 78.86714129990483, 'reg_alpha': 1.7123375973163988, 'max_delta_step': 3, 'subsample': 0.5488360570031919, 'colsample_bynode': 0.8421165132560784, 'scale_pos_weight': 27, 'max_cat_to_onehot': 10}. Best is trial 1 with value: 0.634489474432188.
[I 2026-08-18 15:25:51,928] Trial 3 finished with value: 0.6324992961941703 and parameters: {'learning_rate': 0.04597505784732168, 'max_depth': 4, 'min_child_weight': 15.728674194978577, 'gamma': 0.105260377776104, 'reg_lambda': 0.35856126103453967, 'reg_alpha': 7.556810141274429, 'max_delta_step': 8, 'subsample': 0.9697494707820946, 'colsample_bynode': 0.9474136752138245, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 1 with value: 0.634489474432188.
[I 2026-08-18 15:26:58,844] Trial 4 finished with value: 0.6343079692572565 and parameters: {'learning_rate': 0.02447244097399012, 'max_depth': 4, 'min_child_weight': 80.71418522169694, 'gamma': 0.020874681332882276, 'reg_lambda': 0.6963114377829286, 'reg_alpha': 0.14817820606039092, 'max_delta_step': 1, 'subsample': 0.9010984903770198, 'colsample_bynode': 0.5372753218398854, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 1 with value: 0.634489474432188.
[I 2026-08-18 15:27:21,407] Trial 5 finished with value: 0.6300034975457974 and parameters: {'learning_rate': 0.05358055009231865, 'max_depth': 6, 'min_child_weight': 1.4803996190233553, 'gamma': 0.021181366627251397, 'reg_lambda': 0.22264204303769677, 'reg_alpha': 2.8340904295147746, 'max_delta_step': 6, 'subsample': 0.6654490124263246, 'colsample_bynode': 0.5317791751430119, 'scale_pos_weight': 27, 'max_cat_to_onehot': 10}. Best is trial 1 with value: 0.634489474432188.
[I 2026-08-18 15:29:05,889] Trial 6 finished with value: 0.6347674034776758 and parameters: {'learning_rate': 0.013170256885255107, 'max_depth': 6, 'min_child_weight': 56.310478413508214, 'gamma': 0.1191646709003216, 'reg_lambda': 20.55424552015074, 'reg_alpha': 0.09444574254983566, 'max_delta_step': 5, 'subsample': 0.7137705091792748, 'colsample_bynode': 0.5127095633720475, 'scale_pos_weight': 27, 'max_cat_to_onehot': 18}. Best is trial 6 with value: 0.6347674034776758.
[I 2026-08-18 15:29:49,567] Trial 7 finished with value: 0.6335428404182852 and parameters: {'learning_rate': 0.017753837036522245, 'max_depth': 5, 'min_child_weight': 54.77038995623798, 'gamma': 0.007019683821378796, 'reg_lambda': 0.17019223026554017, 'reg_alpha': 0.014421346497969485, 'max_delta_step': 1, 'subsample': 0.9648488261712865, 'colsample_bynode': 0.9040601897822085, 'scale_pos_weight': 5, 'max_cat_to_onehot': 10}. Best is trial 6 with value: 0.6347674034776758.
[I 2026-08-18 15:30:04,706] Trial 8 finished with value: 0.6321489668493768 and parameters: {'learning_rate': 0.0641859768532441, 'max_depth': 7, 'min_child_weight': 5.391821853721943, 'gamma': 0.0025531643266569876, 'reg_lambda': 0.4828424974818325, 'reg_alpha': 0.05110120656497164, 'max_delta_step': 8, 'subsample': 0.9303652916281717, 'colsample_bynode': 0.5034760652655954, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 6 with value: 0.6347674034776758.
[I 2026-08-18 15:31:04,457] Trial 9 finished with value: 0.634562180201029 and parameters: {'learning_rate': 0.021047616983326124, 'max_depth': 5, 'min_child_weight': 41.4636673787613, 'gamma': 0.02213374957157973, 'reg_lambda': 82.28984573308165, 'reg_alpha': 7.076022085822011, 'max_delta_step': 2, 'subsample': 0.7486242529461927, 'colsample_bynode': 0.6504391549083848, 'scale_pos_weight': 27, 'max_cat_to_onehot': 2}. Best is trial 6 with value: 0.6347674034776758.
[I 2026-08-18 15:31:50,992] Trial 10 pruned. Trial was pruned at iteration 591.
[I 2026-08-18 15:32:46,976] Trial 11 pruned. Trial was pruned at iteration 678.
[I 2026-08-18 15:33:02,416] Trial 12 finished with value: 0.633287222706914 and parameters: {'learning_rate': 0.09261203923129113, 'max_depth': 5, 'min_child_weight': 175.7149123957016, 'gamma': 0.0013311689559882748, 'reg_lambda': 18.195447024751573, 'reg_alpha': 0.0464760812201227, 'max_delta_step': 4, 'subsample': 0.7828704223732299, 'colsample_bynode': 0.6210620520243827, 'scale_pos_weight': 27, 'max_cat_to_onehot': 2}. Best is trial 6 with value: 0.6347674034776758.
[I 2026-08-18 15:33:27,728] Trial 13 finished with value: 0.6329100241009836 and parameters: {'learning_rate': 0.027679377739673716, 'max_depth': 5, 'min_child_weight': 30.4378159906653, 'gamma': 0.5007686614974761, 'reg_lambda': 19.23435784590868, 'reg_alpha': 9.183981330269061, 'max_delta_step': 6, 'subsample': 0.6841945890209447, 'colsample_bynode': 0.5970095676520678, 'scale_pos_weight': 27, 'max_cat_to_onehot': 2}. Best is trial 6 with value: 0.6347674034776758.
[I 2026-08-18 15:34:02,248] Trial 14 finished with value: 0.6311232081870465 and parameters: {'learning_rate': 0.014699397138326449, 'max_depth': 6, 'min_child_weight': 7.80082459979051, 'gamma': 0.09637392176082113, 'reg_lambda': 3.90154429993679, 'reg_alpha': 0.9178999186433512, 'max_delta_step': 3, 'subsample': 0.8442567067490586, 'colsample_bynode': 0.7352187245631512, 'scale_pos_weight': 27, 'max_cat_to_onehot': 18}. Best is trial 6 with value: 0.6347674034776758.
[I 2026-08-18 15:35:13,316] Trial 15 finished with value: 0.635680829737575 and parameters: {'learning_rate': 0.018974336129655, 'max_depth': 5, 'min_child_weight': 96.92484538021604, 'gamma': 0.00654784310628827, 'reg_lambda': 36.15748709041173, 'reg_alpha': 0.01076809793413426, 'max_delta_step': 6, 'subsample': 0.5592754417341768, 'colsample_bynode': 0.5758117164390464, 'scale_pos_weight': 1, 'max_cat_to_onehot': 2}. Best is trial 15 with value: 0.635680829737575.
[I 2026-08-18 15:35:47,769] Trial 16 finished with value: 0.6362326926085706 and parameters: {'learning_rate': 0.031842467167178666, 'max_depth': 7, 'min_child_weight': 100.73379979731283, 'gamma': 0.006672983864560347, 'reg_lambda': 33.39314028370887, 'reg_alpha': 0.013290609520825891, 'max_delta_step': 6, 'subsample': 0.5334831945668879, 'colsample_bynode': 0.5709490970670972, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 16 with value: 0.6362326926085706.
[I 2026-08-18 15:36:20,553] Trial 17 finished with value: 0.6351230343266487 and parameters: {'learning_rate': 0.03364145324711718, 'max_depth': 7, 'min_child_weight': 93.38804858654372, 'gamma': 0.005770519413260278, 'reg_lambda': 3.2653272475394113, 'reg_alpha': 0.01004974299947144, 'max_delta_step': 8, 'subsample': 0.5216004247704906, 'colsample_bynode': 0.5799764255901854, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 16 with value: 0.6362326926085706.
[I 2026-08-18 15:36:49,286] Trial 18 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 15:37:47,319] Trial 19 finished with value: 0.6365661487808505 and parameters: {'learning_rate': 0.019878340693162987, 'max_depth': 7, 'min_child_weight': 128.04423781299766, 'gamma': 0.0013478583901335914, 'reg_lambda': 7.156869062316318, 'reg_alpha': 0.017305896016880668, 'max_delta_step': 10, 'subsample': 0.5755610736038091, 'colsample_bynode': 0.568701533645773, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 19 with value: 0.6365661487808505.
[I 2026-08-18 15:38:24,261] Trial 20 finished with value: 0.6350258387435807 and parameters: {'learning_rate': 0.035533265539253525, 'max_depth': 7, 'min_child_weight': 189.23472115395134, 'gamma': 0.0014530124781678459, 'reg_lambda': 2.490425177412944, 'reg_alpha': 0.0029934657940309016, 'max_delta_step': 10, 'subsample': 0.615775854500438, 'colsample_bynode': 0.5622791134116996, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 19 with value: 0.6365661487808505.
[I 2026-08-18 15:39:51,963] Trial 21 finished with value: 0.6369573829080808 and parameters: {'learning_rate': 0.01822573782577222, 'max_depth': 7, 'min_child_weight': 100.10516263469547, 'gamma': 0.0038032144061324507, 'reg_lambda': 8.062012057784349, 'reg_alpha': 0.01772614812355839, 'max_delta_step': 9, 'subsample': 0.5611004547582974, 'colsample_bynode': 0.5756073073961593, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:40:51,776] Trial 22 finished with value: 0.6355734170024038 and parameters: {'learning_rate': 0.02006816335672632, 'max_depth': 7, 'min_child_weight': 120.52280718931259, 'gamma': 0.002955474666938501, 'reg_lambda': 8.360435545591109, 'reg_alpha': 0.024289858806658057, 'max_delta_step': 9, 'subsample': 0.5186948458340905, 'colsample_bynode': 0.6555230826661727, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:41:35,366] Trial 23 finished with value: 0.6341324247576081 and parameters: {'learning_rate': 0.028039584945906436, 'max_depth': 7, 'min_child_weight': 66.5119668740483, 'gamma': 0.003052041233444986, 'reg_lambda': 6.95364845070584, 'reg_alpha': 0.00399632320422392, 'max_delta_step': 9, 'subsample': 0.592643130883057, 'colsample_bynode': 0.6133811456935782, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:42:41,403] Trial 24 finished with value: 0.6358652971631358 and parameters: {'learning_rate': 0.016192191224604684, 'max_depth': 7, 'min_child_weight': 35.94886710952312, 'gamma': 0.0010058533705774191, 'reg_lambda': 2.0963287784439464, 'reg_alpha': 0.030012425599446974, 'max_delta_step': 9, 'subsample': 0.5055792153219542, 'colsample_bynode': 0.5528840510180267, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:43:19,493] Trial 25 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 15:44:16,331] Trial 26 finished with value: 0.6358061727306268 and parameters: {'learning_rate': 0.02462415691320848, 'max_depth': 6, 'min_child_weight': 72.82156615930258, 'gamma': 0.0024192778493927285, 'reg_lambda': 5.667867299447094, 'reg_alpha': 0.02224008385432733, 'max_delta_step': 7, 'subsample': 0.6348214258474993, 'colsample_bynode': 0.5010655677102203, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:45:08,116] Trial 27 finished with value: 0.6354691031752859 and parameters: {'learning_rate': 0.031762113662353465, 'max_depth': 7, 'min_child_weight': 109.61644636450357, 'gamma': 0.009074374576421334, 'reg_lambda': 12.6422745569183, 'reg_alpha': 0.07729694181412719, 'max_delta_step': 7, 'subsample': 0.5558111709894963, 'colsample_bynode': 0.9992483437747102, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:45:36,263] Trial 28 finished with value: 0.6358073544154098 and parameters: {'learning_rate': 0.06610749096540754, 'max_depth': 6, 'min_child_weight': 25.588108884360484, 'gamma': 0.0041500602870221705, 'reg_lambda': 44.81374947810183, 'reg_alpha': 0.0066429030896239145, 'max_delta_step': 9, 'subsample': 0.608782560422401, 'colsample_bynode': 0.708983590279147, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:46:23,658] Trial 29 finished with value: 0.6363484977173025 and parameters: {'learning_rate': 0.022606429424670667, 'max_depth': 7, 'min_child_weight': 44.78192773952136, 'gamma': 0.04504120017718304, 'reg_lambda': 12.714828941112733, 'reg_alpha': 0.00322745146853951, 'max_delta_step': 10, 'subsample': 0.5311502809467198, 'colsample_bynode': 0.7788560436052057, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:46:56,502] Trial 30 finished with value: 0.6327520561576481 and parameters: {'learning_rate': 0.022087617053378243, 'max_depth': 7, 'min_child_weight': 44.89579597091709, 'gamma': 0.2388104553140316, 'reg_lambda': 13.393158708359891, 'reg_alpha': 0.0025697900425926522, 'max_delta_step': 10, 'subsample': 0.689553313198619, 'colsample_bynode': 0.8018181042784165, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:47:34,544] Trial 31 finished with value: 0.6353213564033895 and parameters: {'learning_rate': 0.02420127523156909, 'max_depth': 7, 'min_child_weight': 69.2287531242907, 'gamma': 0.013946270898627208, 'reg_lambda': 5.29618364622704, 'reg_alpha': 0.005350890346088905, 'max_delta_step': 9, 'subsample': 0.5388813699867651, 'colsample_bynode': 0.7825167231347254, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:48:31,346] Trial 32 finished with value: 0.6356073401982146 and parameters: {'learning_rate': 0.01794553620260544, 'max_depth': 7, 'min_child_weight': 136.95899361118285, 'gamma': 0.06636340036652845, 'reg_lambda': 11.627835479008327, 'reg_alpha': 0.016558942952015765, 'max_delta_step': 10, 'subsample': 0.5011890139657534, 'colsample_bynode': 0.771071927896676, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:48:55,071] Trial 33 finished with value: 0.6338012555875101 and parameters: {'learning_rate': 0.03887283614229246, 'max_depth': 7, 'min_child_weight': 52.22978530637049, 'gamma': 0.03663862762911692, 'reg_lambda': 26.113788578681227, 'reg_alpha': 0.0019842136465501804, 'max_delta_step': 8, 'subsample': 0.5831031378880931, 'colsample_bynode': 0.8587330337093806, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:50:04,572] Trial 34 finished with value: 0.6356789446689928 and parameters: {'learning_rate': 0.015730675010439635, 'max_depth': 6, 'min_child_weight': 9.719921621922111, 'gamma': 0.0017848367139165337, 'reg_lambda': 51.668905733157395, 'reg_alpha': 0.0051352229163756985, 'max_delta_step': 9, 'subsample': 0.6327997011637037, 'colsample_bynode': 0.5887979516941422, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:50:31,639] Trial 35 finished with value: 0.6336332594008631 and parameters: {'learning_rate': 0.04568054445313521, 'max_depth': 7, 'min_child_weight': 20.150883452422054, 'gamma': 0.05011912078823609, 'reg_lambda': 1.3855797057587982, 'reg_alpha': 0.2812204813795655, 'max_delta_step': 8, 'subsample': 0.5489187846894975, 'colsample_bynode': 0.8207182228083693, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:51:09,135] Trial 36 finished with value: 0.634677949135737 and parameters: {'learning_rate': 0.02489623058547945, 'max_depth': 7, 'min_child_weight': 83.023667830537, 'gamma': 0.0036053122062990293, 'reg_lambda': 12.570827302726311, 'reg_alpha': 0.03966448715486086, 'max_delta_step': 0, 'subsample': 0.6555278933691195, 'colsample_bynode': 0.5342487856027951, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:51:50,120] Trial 37 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 15:52:43,985] Trial 38 finished with value: 0.6369045487364063 and parameters: {'learning_rate': 0.021667270936155104, 'max_depth': 7, 'min_child_weight': 33.75655332188885, 'gamma': 0.012531473288124413, 'reg_lambda': 24.92699515150808, 'reg_alpha': 0.1377520020748958, 'max_delta_step': 10, 'subsample': 0.5832907962089645, 'colsample_bynode': 0.6766922182601278, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:53:23,353] Trial 39 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 15:54:25,930] Trial 40 finished with value: 0.6359143933523335 and parameters: {'learning_rate': 0.016955109438489616, 'max_depth': 7, 'min_child_weight': 33.77870131235727, 'gamma': 0.026039355898816324, 'reg_lambda': 17.806034502102467, 'reg_alpha': 0.13878162708990516, 'max_delta_step': 9, 'subsample': 0.5713867251075605, 'colsample_bynode': 0.6879712679802329, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:55:02,828] Trial 41 finished with value: 0.6349971205878855 and parameters: {'learning_rate': 0.0220360800429888, 'max_depth': 7, 'min_child_weight': 60.018569247553636, 'gamma': 0.008999052203131684, 'reg_lambda': 28.22934925412709, 'reg_alpha': 0.06803768409855288, 'max_delta_step': 10, 'subsample': 0.5315242011485345, 'colsample_bynode': 0.6320620614502983, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:56:16,114] Trial 42 finished with value: 0.6363657326300556 and parameters: {'learning_rate': 0.020410162558813744, 'max_depth': 7, 'min_child_weight': 40.65335410733152, 'gamma': 0.004340530981216581, 'reg_lambda': 56.514821531847794, 'reg_alpha': 0.26533217156465305, 'max_delta_step': 8, 'subsample': 0.6003328342938568, 'colsample_bynode': 0.5503831066450566, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 21 with value: 0.6369573829080808.
[I 2026-08-18 15:57:15,113] Trial 43 finished with value: 0.6369807473082285 and parameters: {'learning_rate': 0.019483349145333645, 'max_depth': 7, 'min_child_weight': 13.724130626531322, 'gamma': 0.0019439878105243665, 'reg_lambda': 54.61463043520827, 'reg_alpha': 0.3688665370460532, 'max_delta_step': 8, 'subsample': 0.6020851215477653, 'colsample_bynode': 0.5435990918788849, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 43 with value: 0.6369807473082285.
[I 2026-08-18 15:58:06,888] Trial 44 finished with value: 0.6357436157851768 and parameters: {'learning_rate': 0.01969747339170388, 'max_depth': 7, 'min_child_weight': 10.999189570934924, 'gamma': 0.001962284870742598, 'reg_lambda': 55.47668505417181, 'reg_alpha': 0.49164929196505275, 'max_delta_step': 7, 'subsample': 0.6596319457600273, 'colsample_bynode': 0.5333794879053292, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 43 with value: 0.6369807473082285.
[I 2026-08-18 15:58:46,353] Trial 45 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 15:59:49,440] Trial 46 finished with value: 0.6363147513722758 and parameters: {'learning_rate': 0.02596309959467871, 'max_depth': 7, 'min_child_weight': 15.879784263317097, 'gamma': 0.001261416719470926, 'reg_lambda': 97.0912967743364, 'reg_alpha': 0.2590693236684741, 'max_delta_step': 8, 'subsample': 0.5809469144066103, 'colsample_bynode': 0.5207100579393534, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 43 with value: 0.6369807473082285.
[I 2026-08-18 16:00:28,495] Trial 47 pruned. Trial was pruned at iteration 500.

In [24]:
pd.DataFrame({
    "best auc_val": study_xgb_calc_te.best_value,
    "best gini": 2 * study_xgb_calc_te.best_value - 1,
    "trials": len(study_xgb_calc_te.trials),
    "pruned": len([t for t in study_xgb_calc_te.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_xgb_calc_te.trials if t.state.name == "FAIL"]),
    "best params": study_xgb_calc_te.best_params
})

                   best auc_val  best gini  trials  pruned  fail  best params
learning_rate          0.637973   0.275947      50       8     0     0.018784
max_depth              0.637973   0.275947      50       8     0     6.000000
min_child_weight       0.637973   0.275947      50       8     0    26.805781
gamma                  0.637973   0.275947      50       8     0     0.004322
reg_lambda             0.637973   0.275947      50       8     0    42.387085
reg_alpha              0.637973   0.275947      50       8     0     0.124704
max_delta_step         0.637973   0.275947      50       8     0     7.000000
subsample              0.637973   0.275947      50       8     0     0.610842
colsample_bynode       0.637973   0.275947      50       8     0     0.674854
scale_pos_weight       0.637973   0.275947      50       8     0     1.000000
max_cat_to_onehot      0.637973   0.275947      50       8     0     2.000000

In [25]:
study_xgb_calc_te.best_params

{'learning_rate': 0.01878422273943782,
 'max_depth': 6,
 'min_child_weight': 26.80578055959848,
 'gamma': 0.0043219290644965075,
 'reg_lambda': 42.387084879302726,
 'reg_alpha': 0.12470405254321192,
 'max_delta_step': 7,
 'subsample': 0.6108424214140475,
 'colsample_bynode': 0.6748543547526068,
 'scale_pos_weight': 1,
 'max_cat_to_onehot': 2}

## Ohne Calc

In [26]:
def objective_xgb_no_calc_te(trial):
    pruning_callback = XGBoostPruningCallback(trial, "validation_0-auc")

    modell = XGBClassifier(
        **fixed_params_xgb,
        **suchraum_params(trial),
        callbacks=[pruning_callback]
    )

    modell.fit(x_train_no_calc_te, y_train, eval_set=[(x_val_no_calc_te, y_val)], verbose=0)

    return roc_auc_score(y_val, modell.predict_proba(x_val_no_calc_te)[:, 1])

In [27]:
study_xgb_no_calc_te = optuna.create_study(
    study_name = "XGBoost_no_calc_te",
    storage = "sqlite:///xgboost_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=500)
)

[I 2026-08-18 16:02:25,512] A new study created in RDB with name: XGBoost_no_calc_te

In [28]:
study_xgb_no_calc_te.optimize(
    objective_xgb_no_calc_te,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

[I 2026-08-18 16:02:47,809] Trial 0 finished with value: 0.6306568727667212 and parameters: {'learning_rate': 0.023688639503640783, 'max_depth': 7, 'min_child_weight': 48.343714531846395, 'gamma': 0.16383993835282307, 'reg_lambda': 0.2938027938703535, 'reg_alpha': 0.004207053950287938, 'max_delta_step': 0, 'subsample': 0.9330880728874675, 'colsample_bynode': 0.8005575058716043, 'scale_pos_weight': 27, 'max_cat_to_onehot': 2}. Best is trial 0 with value: 0.6306568727667212.
[I 2026-08-18 16:04:24,237] Trial 1 finished with value: 0.6364710874651968 and parameters: {'learning_rate': 0.015254729458052608, 'max_depth': 4, 'min_child_weight': 16.12427845856261, 'gamma': 0.039605150456850806, 'reg_lambda': 0.7476312062252299, 'reg_alpha': 0.2801635158716261, 'max_delta_step': 1, 'subsample': 0.6460723242676091, 'colsample_bynode': 0.6831809216468459, 'scale_pos_weight': 5, 'max_cat_to_onehot': 10}. Best is trial 1 with value: 0.6364710874651968.
[I 2026-08-18 16:05:17,058] Trial 2 finished with value: 0.6341202140148506 and parameters: {'learning_rate': 0.04050837781329675, 'max_depth': 3, 'min_child_weight': 1.4115155493448333, 'gamma': 3.235185145617431, 'reg_lambda': 78.86714129990483, 'reg_alpha': 1.7123375973163988, 'max_delta_step': 3, 'subsample': 0.5488360570031919, 'colsample_bynode': 0.8421165132560784, 'scale_pos_weight': 27, 'max_cat_to_onehot': 10}. Best is trial 1 with value: 0.6364710874651968.
[I 2026-08-18 16:05:56,663] Trial 3 finished with value: 0.6344294335910716 and parameters: {'learning_rate': 0.04597505784732168, 'max_depth': 4, 'min_child_weight': 15.728674194978577, 'gamma': 0.105260377776104, 'reg_lambda': 0.35856126103453967, 'reg_alpha': 7.556810141274429, 'max_delta_step': 8, 'subsample': 0.9697494707820946, 'colsample_bynode': 0.9474136752138245, 'scale_pos_weight': 5, 'max_cat_to_onehot': 18}. Best is trial 1 with value: 0.6364710874651968.
[I 2026-08-18 16:07:51,249] Trial 4 finished with value: 0.6374504871061429 and parameters: {'learning_rate': 0.02447244097399012, 'max_depth': 4, 'min_child_weight': 80.71418522169694, 'gamma': 0.020874681332882276, 'reg_lambda': 0.6963114377829286, 'reg_alpha': 0.14817820606039092, 'max_delta_step': 1, 'subsample': 0.9010984903770198, 'colsample_bynode': 0.5372753218398854, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 4 with value: 0.6374504871061429.
[I 2026-08-18 16:08:03,488] Trial 5 finished with value: 0.629948392449285 and parameters: {'learning_rate': 0.05358055009231865, 'max_depth': 6, 'min_child_weight': 1.4803996190233553, 'gamma': 0.021181366627251397, 'reg_lambda': 0.22264204303769677, 'reg_alpha': 2.8340904295147746, 'max_delta_step': 6, 'subsample': 0.6654490124263246, 'colsample_bynode': 0.5317791751430119, 'scale_pos_weight': 27, 'max_cat_to_onehot': 10}. Best is trial 4 with value: 0.6374504871061429.
[I 2026-08-18 16:09:17,179] Trial 6 finished with value: 0.6350176553754917 and parameters: {'learning_rate': 0.013170256885255107, 'max_depth': 6, 'min_child_weight': 56.310478413508214, 'gamma': 0.1191646709003216, 'reg_lambda': 20.55424552015074, 'reg_alpha': 0.09444574254983566, 'max_delta_step': 5, 'subsample': 0.7137705091792748, 'colsample_bynode': 0.5127095633720475, 'scale_pos_weight': 27, 'max_cat_to_onehot': 18}. Best is trial 4 with value: 0.6374504871061429.
[I 2026-08-18 16:10:35,505] Trial 7 finished with value: 0.6372128559233562 and parameters: {'learning_rate': 0.017753837036522245, 'max_depth': 5, 'min_child_weight': 54.77038995623798, 'gamma': 0.007019683821378796, 'reg_lambda': 0.17019223026554017, 'reg_alpha': 0.014421346497969485, 'max_delta_step': 1, 'subsample': 0.9648488261712865, 'colsample_bynode': 0.9040601897822085, 'scale_pos_weight': 5, 'max_cat_to_onehot': 10}. Best is trial 4 with value: 0.6374504871061429.
[I 2026-08-18 16:10:51,387] Trial 8 finished with value: 0.6325881958677416 and parameters: {'learning_rate': 0.0641859768532441, 'max_depth': 7, 'min_child_weight': 5.391821853721943, 'gamma': 0.0025531643266569876, 'reg_lambda': 0.4828424974818325, 'reg_alpha': 0.05110120656497164, 'max_delta_step': 8, 'subsample': 0.9303652916281717, 'colsample_bynode': 0.5034760652655954, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 4 with value: 0.6374504871061429.
[I 2026-08-18 16:11:59,247] Trial 9 finished with value: 0.6363887553866437 and parameters: {'learning_rate': 0.021047616983326124, 'max_depth': 5, 'min_child_weight': 41.4636673787613, 'gamma': 0.02213374957157973, 'reg_lambda': 82.28984573308165, 'reg_alpha': 7.076022085822011, 'max_delta_step': 2, 'subsample': 0.7486242529461927, 'colsample_bynode': 0.6504391549083848, 'scale_pos_weight': 27, 'max_cat_to_onehot': 2}. Best is trial 4 with value: 0.6374504871061429.
[I 2026-08-18 16:12:44,217] Trial 10 finished with value: 0.638967420685257 and parameters: {'learning_rate': 0.08946356375348483, 'max_depth': 3, 'min_child_weight': 170.18997474271157, 'gamma': 2.0911024869871846, 'reg_lambda': 3.2180564126206486, 'reg_alpha': 0.0014285676124002457, 'max_delta_step': 10, 'subsample': 0.8189858776055304, 'colsample_bynode': 0.697426806767293, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 10 with value: 0.638967420685257.
[I 2026-08-18 16:13:05,778] Trial 11 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:14:21,813] Trial 12 finished with value: 0.6386500458762991 and parameters: {'learning_rate': 0.0298527946268344, 'max_depth': 4, 'min_child_weight': 190.5243862826254, 'gamma': 0.7960241499361916, 'reg_lambda': 2.0876390822113007, 'reg_alpha': 0.4089959430771121, 'max_delta_step': 4, 'subsample': 0.8336228052393174, 'colsample_bynode': 0.724462803532516, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 10 with value: 0.638967420685257.
[I 2026-08-18 16:15:48,313] Trial 13 finished with value: 0.638177685471315 and parameters: {'learning_rate': 0.033087676505623, 'max_depth': 3, 'min_child_weight': 198.87381277542102, 'gamma': 0.7440112397885874, 'reg_lambda': 4.365224447527162, 'reg_alpha': 0.5860368665862755, 'max_delta_step': 10, 'subsample': 0.8155421717694825, 'colsample_bynode': 0.7613273130367438, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 10 with value: 0.638967420685257.
[I 2026-08-18 16:16:12,612] Trial 14 finished with value: 0.6382453067801206 and parameters: {'learning_rate': 0.08169353079021664, 'max_depth': 4, 'min_child_weight': 108.53259992974927, 'gamma': 0.8696997914548711, 'reg_lambda': 2.29182396601875, 'reg_alpha': 0.018860442092066342, 'max_delta_step': 4, 'subsample': 0.8450353850865742, 'colsample_bynode': 0.7534334704264577, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 10 with value: 0.638967420685257.
[I 2026-08-18 16:16:37,034] Trial 15 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:17:33,832] Trial 16 finished with value: 0.636769507085595 and parameters: {'learning_rate': 0.031842467167178666, 'max_depth': 5, 'min_child_weight': 18.213993335175218, 'gamma': 1.6770546153113206, 'reg_lambda': 1.5092675682640495, 'reg_alpha': 0.005015799436471375, 'max_delta_step': 9, 'subsample': 0.7475519754993947, 'colsample_bynode': 0.7248333961109953, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 10 with value: 0.638967420685257.
[I 2026-08-18 16:18:04,462] Trial 17 finished with value: 0.6390167942086384 and parameters: {'learning_rate': 0.06712237440858096, 'max_depth': 4, 'min_child_weight': 115.1600398918912, 'gamma': 0.3184260587695134, 'reg_lambda': 14.553327577462973, 'reg_alpha': 0.03294900078937184, 'max_delta_step': 5, 'subsample': 0.8803609155918467, 'colsample_bynode': 0.8505748635593766, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 17 with value: 0.6390167942086384.
[I 2026-08-18 16:18:30,906] Trial 18 finished with value: 0.6383676875225429 and parameters: {'learning_rate': 0.09968934319673953, 'max_depth': 3, 'min_child_weight': 27.646206067217655, 'gamma': 0.25629245657534533, 'reg_lambda': 15.32434964419002, 'reg_alpha': 0.0037251976629973115, 'max_delta_step': 6, 'subsample': 0.8815305299590233, 'colsample_bynode': 0.86719553329466, 'scale_pos_weight': 1, 'max_cat_to_onehot': 2}. Best is trial 17 with value: 0.6390167942086384.
[I 2026-08-18 16:18:56,872] Trial 19 finished with value: 0.636896855727309 and parameters: {'learning_rate': 0.0739638298515656, 'max_depth': 4, 'min_child_weight': 89.73562412001226, 'gamma': 0.4196395639032904, 'reg_lambda': 31.215198803199037, 'reg_alpha': 0.024319509382560882, 'max_delta_step': 8, 'subsample': 0.5086792017528844, 'colsample_bynode': 0.9699958356233106, 'scale_pos_weight': 1, 'max_cat_to_onehot': 18}. Best is trial 17 with value: 0.6390167942086384.
[I 2026-08-18 16:19:18,746] Trial 20 finished with value: 0.635174915915692 and parameters: {'learning_rate': 0.06190338203583045, 'max_depth': 5, 'min_child_weight': 6.695992745333427, 'gamma': 2.234982993999123, 'reg_lambda': 10.602314812605009, 'reg_alpha': 0.00960130814917471, 'max_delta_step': 6, 'subsample': 0.6407765816216827, 'colsample_bynode': 0.820265066682815, 'scale_pos_weight': 5, 'max_cat_to_onehot': 10}. Best is trial 17 with value: 0.6390167942086384.
[I 2026-08-18 16:19:54,456] Trial 21 finished with value: 0.6404696997653279 and parameters: {'learning_rate': 0.06840892817037018, 'max_depth': 4, 'min_child_weight': 123.5725817719912, 'gamma': 1.2262777677477144, 'reg_lambda': 1.2624495151772979, 'reg_alpha': 0.3897567030114538, 'max_delta_step': 4, 'subsample': 0.8718352321453859, 'colsample_bynode': 0.6972248821194833, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:20:31,911] Trial 22 finished with value: 0.6376407825688987 and parameters: {'learning_rate': 0.06815528926688239, 'max_depth': 3, 'min_child_weight': 117.3812592256972, 'gamma': 1.3417534983450377, 'reg_lambda': 1.2150083993524388, 'reg_alpha': 0.04866191087995826, 'max_delta_step': 4, 'subsample': 0.8758500704345084, 'colsample_bynode': 0.5905343748898021, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:21:00,290] Trial 23 finished with value: 0.6376048175504017 and parameters: {'learning_rate': 0.05193915932514704, 'max_depth': 4, 'min_child_weight': 74.79815971632948, 'gamma': 0.27091735583145143, 'reg_lambda': 4.998529477845946, 'reg_alpha': 0.9095164438676783, 'max_delta_step': 3, 'subsample': 0.7710643501932481, 'colsample_bynode': 0.9039252388807872, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:21:25,194] Trial 24 finished with value: 0.6367378507952863 and parameters: {'learning_rate': 0.0881954127929761, 'max_depth': 3, 'min_child_weight': 120.96708325913598, 'gamma': 0.05850670904999403, 'reg_lambda': 45.55345756280325, 'reg_alpha': 0.1867822804012066, 'max_delta_step': 5, 'subsample': 0.9096018864625912, 'colsample_bynode': 0.6833401892079869, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:21:44,700] Trial 25 finished with value: 0.6320436200529078 and parameters: {'learning_rate': 0.0581656992790347, 'max_depth': 4, 'min_child_weight': 29.05890072542375, 'gamma': 4.731071273325969, 'reg_lambda': 8.019903540866755, 'reg_alpha': 0.002268928628689806, 'max_delta_step': 3, 'subsample': 0.9870419801318643, 'colsample_bynode': 0.7672320408956917, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:22:31,650] Trial 26 finished with value: 0.6367044782485072 and parameters: {'learning_rate': 0.04133233247759378, 'max_depth': 5, 'min_child_weight': 68.74417316963917, 'gamma': 0.36849479623965853, 'reg_lambda': 0.1162735829418568, 'reg_alpha': 0.05749198068785732, 'max_delta_step': 7, 'subsample': 0.8670454414394625, 'colsample_bynode': 0.5956380703457781, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:22:54,674] Trial 27 finished with value: 0.6374598320623348 and parameters: {'learning_rate': 0.07475860169606469, 'max_depth': 4, 'min_child_weight': 130.88013977113198, 'gamma': 1.3532154505195042, 'reg_lambda': 2.9444657289342855, 'reg_alpha': 0.009010002864947344, 'max_delta_step': 5, 'subsample': 0.8051949762478208, 'colsample_bynode': 0.9992483437747102, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:23:18,111] Trial 28 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:23:54,270] Trial 29 finished with value: 0.635497925833717 and parameters: {'learning_rate': 0.04711976950955051, 'max_depth': 6, 'min_child_weight': 42.08661400257833, 'gamma': 0.1756362609271675, 'reg_lambda': 6.018419249589379, 'reg_alpha': 2.9422365422790904, 'max_delta_step': 0, 'subsample': 0.711184773788314, 'colsample_bynode': 0.8080661442417597, 'scale_pos_weight': 5, 'max_cat_to_onehot': 2}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:24:18,106] Trial 30 finished with value: 0.6365568319600108 and parameters: {'learning_rate': 0.07170969373044123, 'max_depth': 5, 'min_child_weight': 150.46780270413691, 'gamma': 0.47696740002187654, 'reg_lambda': 13.393158708359891, 'reg_alpha': 0.029784944057251683, 'max_delta_step': 2, 'subsample': 0.9329176259502602, 'colsample_bynode': 0.7833003135765791, 'scale_pos_weight': 27, 'max_cat_to_onehot': 2}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:24:47,227] Trial 31 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:25:16,736] Trial 32 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:25:43,928] Trial 33 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:26:18,595] Trial 34 finished with value: 0.6379799542369657 and parameters: {'learning_rate': 0.05505736677828165, 'max_depth': 4, 'min_child_weight': 103.85401223765064, 'gamma': 0.4856064644976152, 'reg_lambda': 0.6487298001902728, 'reg_alpha': 0.11875648479578481, 'max_delta_step': 3, 'subsample': 0.8009444471880748, 'colsample_bynode': 0.6902033581395035, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:26:47,195] Trial 35 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:27:04,262] Trial 36 finished with value: 0.6355876173164796 and parameters: {'learning_rate': 0.08211544985193041, 'max_depth': 4, 'min_child_weight': 196.18105194208172, 'gamma': 3.1252188192104704, 'reg_lambda': 0.42022484900485063, 'reg_alpha': 1.9551694717601737, 'max_delta_step': 7, 'subsample': 0.8523527144347822, 'colsample_bynode': 0.8620569563087507, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:27:36,595] Trial 37 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:28:04,591] Trial 38 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:28:33,068] Trial 39 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:29:11,729] Trial 40 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:29:40,651] Trial 41 finished with value: 0.6376986328718967 and parameters: {'learning_rate': 0.0960693242862534, 'max_depth': 3, 'min_child_weight': 6.238746303257429, 'gamma': 0.24667130238193044, 'reg_lambda': 16.74800701892997, 'reg_alpha': 0.003273462462558096, 'max_delta_step': 5, 'subsample': 0.8803151497902216, 'colsample_bynode': 0.8641048811718385, 'scale_pos_weight': 1, 'max_cat_to_onehot': 2}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:30:20,213] Trial 42 finished with value: 0.6379859269702566 and parameters: {'learning_rate': 0.08360597495873749, 'max_depth': 3, 'min_child_weight': 11.481159568523125, 'gamma': 0.3058035658299143, 'reg_lambda': 48.78321992019825, 'reg_alpha': 0.0014632874604134745, 'max_delta_step': 6, 'subsample': 0.8824416506307482, 'colsample_bynode': 0.9220882928150014, 'scale_pos_weight': 1, 'max_cat_to_onehot': 2}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:30:49,207] Trial 43 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:31:25,387] Trial 44 finished with value: 0.6377068524140095 and parameters: {'learning_rate': 0.07667040537523773, 'max_depth': 4, 'min_child_weight': 16.717054137704906, 'gamma': 1.8751271087592822, 'reg_lambda': 2.509493589164094, 'reg_alpha': 0.0023077876145331843, 'max_delta_step': 3, 'subsample': 0.8566880256133813, 'colsample_bynode': 0.8905951999886973, 'scale_pos_weight': 1, 'max_cat_to_onehot': 2}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:31:49,037] Trial 45 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:32:15,052] Trial 46 pruned. Trial was pruned at iteration 500.
[I 2026-08-18 16:32:38,760] Trial 47 finished with value: 0.6328343359848331 and parameters: {'learning_rate': 0.09097682945855524, 'max_depth': 4, 'min_child_weight': 10.895717027142558, 'gamma': 0.0357304295496369, 'reg_lambda': 4.409210780191574, 'reg_alpha': 0.0016491430908041646, 'max_delta_step': 10, 'subsample': 0.6839766792158486, 'colsample_bynode': 0.7802828923567178, 'scale_pos_weight': 1, 'max_cat_to_onehot': 10}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:32:58,420] Trial 48 finished with value: 0.633026745618323 and parameters: {'learning_rate': 0.0607558741654271, 'max_depth': 5, 'min_child_weight': 55.08855526074376, 'gamma': 0.1284106955592974, 'reg_lambda': 0.5290573432519571, 'reg_alpha': 0.012129370800357454, 'max_delta_step': 6, 'subsample': 0.8221607920688856, 'colsample_bynode': 0.664009753874779, 'scale_pos_weight': 27, 'max_cat_to_onehot': 2}. Best is trial 21 with value: 0.6404696997653279.
[I 2026-08-18 16:33:30,730] Trial 49 pruned. Trial was pruned at iteration 500.

In [29]:
pd.DataFrame({
    "best auc_val": study_xgb_no_calc_te.best_value,
    "best gini": 2 * study_xgb_no_calc_te.best_value - 1,
    "trials": len(study_xgb_no_calc_te.trials),
    "pruned": len([t for t in study_xgb_no_calc_te.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_xgb_no_calc_te.trials if t.state.name == "FAIL"]),
    "best params": study_xgb_no_calc_te.best_params
})

                   best auc_val  best gini  trials  pruned  fail  best params
learning_rate           0.64047   0.280939      50      15     0     0.068409
max_depth               0.64047   0.280939      50      15     0     4.000000
min_child_weight        0.64047   0.280939      50      15     0   123.572582
gamma                   0.64047   0.280939      50      15     0     1.226278
reg_lambda              0.64047   0.280939      50      15     0     1.262450
reg_alpha               0.64047   0.280939      50      15     0     0.389757
max_delta_step          0.64047   0.280939      50      15     0     4.000000
subsample               0.64047   0.280939      50      15     0     0.871835
colsample_bynode        0.64047   0.280939      50      15     0     0.697225
scale_pos_weight        0.64047   0.280939      50      15     0     1.000000
max_cat_to_onehot       0.64047   0.280939      50      15     0    10.000000

In [30]:
study_xgb_no_calc_te.best_params

{'learning_rate': 0.06840892817037018,
 'max_depth': 4,
 'min_child_weight': 123.5725817719912,
 'gamma': 1.2262777677477144,
 'reg_lambda': 1.2624495151772979,
 'reg_alpha': 0.3897567030114538,
 'max_delta_step': 4,
 'subsample': 0.8718352321453859,
 'colsample_bynode': 0.6972248821194833,
 'scale_pos_weight': 1,
 'max_cat_to_onehot': 10}

## Load Study

In [31]:
study_xgb_calc_te_loaded = optuna.load_study(
    study_name = "XGBoost_calc_te",
    storage = "sqlite:///xgboost_opti.db"
)

In [32]:
study_xgb_no_calc_te_loaded = optuna.load_study(
    study_name = "XGBoost_no_calc_te",
    storage = "sqlite:///xgboost_opti.db"
)

## Best Params again

In [33]:
study_xgb_calc_te_loaded.best_params

{'learning_rate': 0.01878422273943782,
 'max_depth': 6,
 'min_child_weight': 26.80578055959848,
 'gamma': 0.0043219290644965075,
 'reg_lambda': 42.387084879302726,
 'reg_alpha': 0.12470405254321192,
 'max_delta_step': 7,
 'subsample': 0.6108424214140475,
 'colsample_bynode': 0.6748543547526068,
 'scale_pos_weight': 1,
 'max_cat_to_onehot': 2}

In [34]:
study_xgb_no_calc_te_loaded.best_params

{'learning_rate': 0.06840892817037018,
 'max_depth': 4,
 'min_child_weight': 123.5725817719912,
 'gamma': 1.2262777677477144,
 'reg_lambda': 1.2624495151772979,
 'reg_alpha': 0.3897567030114538,
 'max_delta_step': 4,
 'subsample': 0.8718352321453859,
 'colsample_bynode': 0.6972248821194833,
 'scale_pos_weight': 1,
 'max_cat_to_onehot': 10}

## 100% Train

In [35]:
results = []
train_times = {}

In [36]:
name = "L_xgb_opt_03"

L_xgb_opt_03 = XGBClassifier(
    **fixed_params_xgb,
    **study_xgb_calc_te_loaded.best_params
)

start = time.time()
L_xgb_opt_03.fit(
    x_train_te, y_train, 
    eval_set=[(x_val_te, y_val)], 
    verbose=250
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_xgb_opt_03, x_train_te, y_train, x_val_te, y_val, train_times[name], best_iter=L_xgb_opt_03.best_iteration)
)

[0]	validation_0-auc:0.59660
[250]	validation_0-auc:0.63438
[500]	validation_0-auc:0.63640
[750]	validation_0-auc:0.63777
[882]	validation_0-auc:0.63742

In [37]:
name = "L_xgb_opt_04"

L_xgb_opt_04 = XGBClassifier(
    **fixed_params_xgb,
    **study_xgb_no_calc_te_loaded.best_params
)

start = time.time()
L_xgb_opt_04.fit(
    x_train_no_calc_te, y_train, 
    eval_set=[(x_val_no_calc_te, y_val)], 
    verbose=250
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_xgb_opt_04, x_train_no_calc_te, y_train, x_val_no_calc_te, y_val, train_times[name], best_iter=L_xgb_opt_04.best_iteration)
)

[0]	validation_0-auc:0.58953
[250]	validation_0-auc:0.63782
[500]	validation_0-auc:0.64021
[665]	validation_0-auc:0.64006

In [38]:
pd.DataFrame(results)

,model_idx,auc_train,auc_val,gini,delta_auc,best_iter,trainingszeit
0,L_xgb_opt_03,0.712847,0.637973,0.275947,0.074874,782,62.368462
1,L_xgb_opt_04,0.685711,0.640470,0.280939,0.045242,565,25.698286

## Save Models

In [39]:
Modelle = [
    (L_xgb_opt_03, "L_xgb_opt_03"),
    (L_xgb_opt_04, "L_xgb_opt_04")
]

for modell, name in Modelle:
    modell.save_model(f"{name}.json")

## Notizen

- 105 aus max one hot kann raus weil target encoding