# 20 HistGradientBoosting Optuna Prep for J_D

## Import

In [2]:
import time

import numpy as np
import pandas as pd

from sklearn.datasets import fetch_openml
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import TargetEncoder
from sklearn.ensemble import HistGradientBoostingClassifier

import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner

import joblib

import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
mpl.style.use("seaborn-v0_8-colorblind")
RANDOM_STATE = 42

## Dataframe

In [4]:
df_raw = fetch_openml(data_id=42742, as_frame=True).frame

In [5]:
feat_cols = [col for col in df_raw.columns if col not in ("target",)]
cat_cols = [col for col in feat_cols if col.endswith("_cat")]
bin_cols = [col for col in feat_cols if col.endswith("_bin")]
num_cols = [col for col in feat_cols if col not in cat_cols and col not in bin_cols]

for col in cat_cols:
    df_raw[col] = df_raw[col].astype("category")

for col in bin_cols:
    if df_raw[col].isna().sum() == 0:
        df_raw[col] = df_raw[col].astype(int).astype("bool")
    else:
        df_raw[col] = df_raw[col].astype("Int8")

for col in num_cols:
    df_raw[col] = df_raw[col].astype("float32")

df_raw["target"] = df_raw["target"].astype(int).astype("bool")

idx_train = np.load("../../../data/processed/train_idx.npy")
idx_val = np.load("../../../data/processed/val_idx.npy")
idx_test = np.load("../../../data/processed/test_idx.npy")

df_train = df_raw.iloc[idx_train]
df_val = df_raw.iloc[idx_val]
df_test = df_raw.iloc[idx_test]

x_train, y_train = df_train[feat_cols], df_train["target"]
x_val, y_val = df_val[feat_cols], df_val["target"]
x_test, y_test = df_test[feat_cols], df_test["target"]
x_full, y_full = df_raw[feat_cols], df_raw["target"]

pd.Series(
    {
        "train": [len(df_train), len(x_train), len(y_train)],
        "val": [len(df_val), len(x_val), len(y_val)],
        "test": [len(df_test), len(x_test), len(y_test)],
        "full": [len(df_raw), len(x_full), len(y_full)]
    }
)

train    [476168, 476168, 476168]
val         [59522, 59522, 59522]
test        [59522, 59522, 59522]
full     [595212, 595212, 595212]
dtype: object

## Hilfsvariablen

In [6]:
calc_cols = [c for c in feat_cols if c.startswith("ps_calc_")]

mv_cols = ["ps_car_03_cat", "ps_car_05_cat", "ps_reg_03", "ps_car_14"]

num_cols_no_calc = [c for c in num_cols if c not in calc_cols]
bin_cols_no_calc = [c for c in bin_cols if c not in calc_cols]
feat_cols_no_calc = [c for c in feat_cols if c not in calc_cols]

high_kard_cols = ["ps_car_11_cat"]
low_kard_cols = [c for c in cat_cols if c not in high_kard_cols]

In [7]:
def eval_modell(mod_idx, model, x_train, y_train, x_val, y_val, train_time, best_iter=None):
    """AUC auf Train und Val"""
    auc_train = roc_auc_score(y_train, model.predict_proba(x_train)[:, 1])
    auc_val = roc_auc_score(y_val, model.predict_proba(x_val)[:, 1])
    return {
        "model_idx": mod_idx,
        "auc_train": auc_train,
        "auc_val": auc_val,
        "gini": 2 * auc_val - 1,
        "delta_auc": auc_train - auc_val,
        "best_iter": best_iter,
        "trainingszeit": train_time
    }

## Preproc nach J_D

In [8]:
targ_enc = TargetEncoder(
    cv=5,
    shuffle=True,
    random_state=RANDOM_STATE,
    smooth=50.0
)

In [9]:
te_train = pd.DataFrame(
    targ_enc.fit_transform(x_train[cat_cols], y_train),
    columns=cat_cols,
    index=x_train.index
)

te_val = pd.DataFrame(
    targ_enc.transform(x_val[cat_cols]),
    columns=cat_cols,
    index=x_val.index
)

te_test = pd.DataFrame(
    targ_enc.transform(x_test[cat_cols]),
    columns=cat_cols,
    index=x_test.index
)

c:\Users\linus\anaconda3\envs\ADA\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:341: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(

In [10]:
x_train_hgb = x_train.copy()
x_val_hgb = x_val.copy()
x_test_hgb = x_test.copy()

x_train_hgb[cat_cols] = te_train
x_val_hgb[cat_cols] = te_val
x_test_hgb[cat_cols] = te_test

In [11]:
x_train_hgb_no_calc = x_train_hgb[feat_cols_no_calc]
x_val_hgb_no_calc = x_val_hgb[feat_cols_no_calc]
x_test_hgb_no_calc = x_test_hgb[feat_cols_no_calc]

In [12]:
pd.Series({
    "train": [len(x_train), len(x_train_hgb), len(x_train_hgb_no_calc)],
    "val": [len(x_val), len(x_val_hgb), len(x_val_hgb_no_calc)],
    "test": [len(x_test), len(x_test_hgb), len(x_test_hgb_no_calc)]
})

train    [476168, 476168, 476168]
val         [59522, 59522, 59522]
test        [59522, 59522, 59522]
dtype: object

## Optuna Hilfe

## Suchräume

|Parameter|Bereich|
|---|---|
|learning_rate|0.003-0.3 (log)|
|min_samples_leaf|5-40000 (log)|
|l2_regularization|1e-8 - 1e5 (log)|
|max_features|0.05-0.35|
|max_bins|104-255|
|interaction_cst|None / pairwise / no_interactions|
|validation_fraction|0.01-0.1|
|n_iter_no_change|5-40|
|tol|1e-10 - 1e-5 (log)|

Für händische Versuche entweder:
|Parameter|Bereich|
|---|---|
|max_leaf_nodes|2-63|
|max_depth|1-6|

In [13]:
fixed_params_leaf = {
    "random_state": RANDOM_STATE,
    "verbose": 0,
    "loss": "log_loss",
    "class_weight": None,
    "categorical_features": None,
    "scoring": "loss",
    "max_iter": 5000,
    "early_stopping": True,
    "max_depth": None
}

In [14]:
fixed_params_depth = {
    "random_state": RANDOM_STATE,
    "verbose": 0,
    "loss": "log_loss",
    "class_weight": None,
    "categorical_features": None,
    "scoring": "loss",
    "max_iter": 5000,
    "early_stopping": True,
    "max_leaf_nodes": None
}

In [15]:
def suchraum_params_leaf(trial):
    """Suchraum definition, leaf"""
    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.3, log=True),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 5, 40000, log=True),
        "l2_regularization": trial.suggest_float("l2_regularization", 1e-8, 1e5, log=True),
        "max_features": trial.suggest_float("max_features", 0.05, 0.35),
        "max_bins": trial.suggest_int("max_bins", 104, 255),
        "interaction_cst": trial.suggest_categorical("interaction_cst", [None, "pairwise", "no_interactions"]),
        "validation_fraction": trial.suggest_float("validation_fraction", 0.01, 0.1),
        "n_iter_no_change": trial.suggest_int("n_iter_no_change", 5, 40),
        "tol": trial.suggest_float("tol", 1e-10, 1e-5, log=True),
        "max_leaf_nodes": trial.suggest_int("max_leaf_nodes", 2, 63)
    }

    return params

In [16]:
def suchraum_params_depth(trial):
    """Suchraum definition, depth"""
    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.3, log=True),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 5, 40000, log=True),
        "l2_regularization": trial.suggest_float("l2_regularization", 1e-8, 1e5, log=True),
        "max_features": trial.suggest_float("max_features", 0.05, 0.35),
        "max_bins": trial.suggest_int("max_bins", 104, 255),
        "interaction_cst": trial.suggest_categorical("interaction_cst", [None, "pairwise", "no_interactions"]),
        "validation_fraction": trial.suggest_float("validation_fraction", 0.01, 0.1),
        "n_iter_no_change": trial.suggest_int("n_iter_no_change", 5, 40),
        "tol": trial.suggest_float("tol", 1e-10, 1e-5, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 6)
    }

    return params

## Leaf mit Calc

In [17]:
def objective_leaf_calc(trial):

    modell = HistGradientBoostingClassifier(
        **fixed_params_leaf,
        **suchraum_params_leaf(trial)
    )

    modell.fit(x_train_hgb, y_train)

    return roc_auc_score(y_val, modell.predict_proba(x_val_hgb)[:, 1])

In [18]:
study_leaf_calc = optuna.create_study(
    study_name = "HGB_leaf_calc",
    storage = "sqlite:///HGB_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=500)
)

[I 2026-08-19 12:02:59,959] A new study created in RDB with name: HGB_leaf_calc

In [19]:
study_leaf_calc.optimize(
    objective_leaf_calc,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

[I 2026-08-19 12:03:33,751] Trial 0 finished with value: 0.6209433354252369 and parameters: {'learning_rate': 0.01683454924600351, 'min_samples_leaf': 25553, 'l2_regularization': 32.8035800581182, 'max_features': 0.22959754525911097, 'max_bins': 127, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.0641003510568888, 'n_iter_no_change': 30, 'tol': 1.267425589893721e-10, 'max_leaf_nodes': 62}. Best is trial 0 with value: 0.6209433354252369.
[I 2026-08-19 12:03:37,043] Trial 1 finished with value: 0.6296457123327305 and parameters: {'learning_rate': 0.13867767003062487, 'min_samples_leaf': 31, 'l2_regularization': 2.3105989608604262e-06, 'max_features': 0.10502135295603016, 'max_bins': 150, 'interaction_cst': None, 'validation_fraction': 0.06506676052501416, 'n_iter_no_change': 10, 'tol': 2.888838362365319e-09, 'max_leaf_nodes': 24}. Best is trial 1 with value: 0.6296457123327305.
[I 2026-08-19 12:03:51,142] Trial 2 finished with value: 0.6277347833425565 and parameters: {'learning_rate': 0.02450536768428048, 'min_samples_leaf': 5672, 'l2_regularization': 3.94238621924438e-06, 'max_features': 0.20427033152408347, 'max_bins': 194, 'interaction_cst': 'pairwise', 'validation_fraction': 0.015854643368675158, 'n_iter_no_change': 39, 'tol': 6.732248920775334e-06, 'max_leaf_nodes': 52}. Best is trial 1 with value: 0.6296457123327305.
[I 2026-08-19 12:04:31,881] Trial 3 finished with value: 0.6228466598317054 and parameters: {'learning_rate': 0.012199689940544376, 'min_samples_leaf': 11, 'l2_regularization': 7.852886936532546, 'max_features': 0.1820457481218804, 'max_bins': 122, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.03329019834400153, 'n_iter_no_change': 28, 'tol': 3.618723330959621e-09, 'max_leaf_nodes': 34}. Best is trial 1 with value: 0.6296457123327305.
[I 2026-08-19 12:05:24,638] Trial 4 finished with value: 0.6127670735223452 and parameters: {'learning_rate': 0.037199903510538264, 'min_samples_leaf': 24, 'l2_regularization': 40234.64380902767, 'max_features': 0.28253984700833434, 'max_bins': 246, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.017964325184672756, 'n_iter_no_change': 12, 'tol': 1.6832027985721906e-10, 'max_leaf_nodes': 22}. Best is trial 1 with value: 0.6296457123327305.
[I 2026-08-19 12:06:29,835] Trial 5 finished with value: 0.6257699791726852 and parameters: {'learning_rate': 0.01796701101676289, 'min_samples_leaf': 53, 'l2_regularization': 593.7281208438861, 'max_features': 0.1570259980080768, 'max_bins': 146, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.016709557931179377, 'n_iter_no_change': 40, 'tol': 7.26480307482673e-07, 'max_leaf_nodes': 14}. Best is trial 1 with value: 0.6296457123327305.
[I 2026-08-19 12:08:32,554] Trial 6 finished with value: 0.6282079315373958 and parameters: {'learning_rate': 0.0030772691922556945, 'min_samples_leaf': 7471, 'l2_regularization': 15.457721201756003, 'max_features': 0.26870215041229617, 'max_bins': 221, 'interaction_cst': 'pairwise', 'validation_fraction': 0.08767930832880343, 'n_iter_no_change': 27, 'tol': 4.513257622008936e-09, 'max_leaf_nodes': 5}. Best is trial 1 with value: 0.6296457123327305.
[I 2026-08-19 12:09:12,179] Trial 7 finished with value: 0.6223037198866224 and parameters: {'learning_rate': 0.012562784156701876, 'min_samples_leaf': 87, 'l2_regularization': 30.540793629644874, 'max_features': 0.24126724140656391, 'max_bins': 238, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.07847065437552077, 'n_iter_no_change': 25, 'tol': 7.158728631500194e-07, 'max_leaf_nodes': 32}. Best is trial 1 with value: 0.6296457123327305.
[I 2026-08-19 12:09:22,490] Trial 8 finished with value: 0.6308958464077309 and parameters: {'learning_rate': 0.033310941939163854, 'min_samples_leaf': 220, 'l2_regularization': 2.1401718512509955e-08, 'max_features': 0.08236742809799133, 'max_bins': 108, 'interaction_cst': None, 'validation_fraction': 0.09168098265334837, 'n_iter_no_change': 13, 'tol': 1.1269758643814652e-08, 'max_leaf_nodes': 48}. Best is trial 8 with value: 0.6308958464077309.
[I 2026-08-19 12:09:53,095] Trial 9 finished with value: 0.6162273118430852 and parameters: {'learning_rate': 0.008604340446309018, 'min_samples_leaf': 9, 'l2_regularization': 5.844789677758518e-05, 'max_features': 0.09836638617620133, 'max_bins': 245, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.0823304869209203, 'n_iter_no_change': 11, 'tol': 2.9026521418263896e-06, 'max_leaf_nodes': 35}. Best is trial 8 with value: 0.6308958464077309.
[I 2026-08-19 12:09:55,066] Trial 10 finished with value: 0.6243366558209708 and parameters: {'learning_rate': 0.24554140659956822, 'min_samples_leaf': 333, 'l2_regularization': 1.2534734834039077e-08, 'max_features': 0.3296871025735361, 'max_bins': 182, 'interaction_cst': None, 'validation_fraction': 0.042518079679762844, 'n_iter_no_change': 5, 'tol': 5.4675303863547164e-08, 'max_leaf_nodes': 47}. Best is trial 8 with value: 0.6308958464077309.
[I 2026-08-19 12:09:59,691] Trial 11 finished with value: 0.6277825250155233 and parameters: {'learning_rate': 0.10017647848692383, 'min_samples_leaf': 394, 'l2_regularization': 2.0375798014091394e-08, 'max_features': 0.06161122669722887, 'max_bins': 106, 'interaction_cst': None, 'validation_fraction': 0.09934237260429883, 'n_iter_no_change': 16, 'tol': 7.639000831242936e-09, 'max_leaf_nodes': 46}. Best is trial 8 with value: 0.6308958464077309.
[I 2026-08-19 12:10:06,181] Trial 12 finished with value: 0.6300210057733984 and parameters: {'learning_rate': 0.07025590950959668, 'min_samples_leaf': 546, 'l2_regularization': 0.00023245726721381158, 'max_features': 0.1278849037818469, 'max_bins': 156, 'interaction_cst': None, 'validation_fraction': 0.05653012128865024, 'n_iter_no_change': 18, 'tol': 3.724899981563061e-08, 'max_leaf_nodes': 19}. Best is trial 8 with value: 0.6308958464077309.
[I 2026-08-19 12:10:21,877] Trial 13 finished with value: 0.6229345868259655 and parameters: {'learning_rate': 0.04744361181844628, 'min_samples_leaf': 653, 'l2_regularization': 0.0013248608435641024, 'max_features': 0.13388197687191256, 'max_bins': 169, 'interaction_cst': None, 'validation_fraction': 0.052635520118438237, 'n_iter_no_change': 21, 'tol': 6.756745259558525e-08, 'max_leaf_nodes': 2}. Best is trial 8 with value: 0.6308958464077309.
[I 2026-08-19 12:10:32,149] Trial 14 finished with value: 0.6306891801894614 and parameters: {'learning_rate': 0.06511945491741467, 'min_samples_leaf': 1678, 'l2_regularization': 0.020371947606485814, 'max_features': 0.06853819583260022, 'max_bins': 152, 'interaction_cst': None, 'validation_fraction': 0.0997589756969091, 'n_iter_no_change': 18, 'tol': 2.693650908162375e-08, 'max_leaf_nodes': 56}. Best is trial 8 with value: 0.6308958464077309.
[I 2026-08-19 12:10:42,357] Trial 15 finished with value: 0.6326842901527467 and parameters: {'learning_rate': 0.04208002447621916, 'min_samples_leaf': 2141, 'l2_regularization': 0.03482419383306384, 'max_features': 0.05963123586947908, 'max_bins': 104, 'interaction_cst': None, 'validation_fraction': 0.09926607901067544, 'n_iter_no_change': 5, 'tol': 7.109581564134797e-10, 'max_leaf_nodes': 61}. Best is trial 15 with value: 0.6326842901527467.
[I 2026-08-19 12:10:49,940] Trial 16 finished with value: 0.6269263582162306 and parameters: {'learning_rate': 0.03493958771083442, 'min_samples_leaf': 154, 'l2_regularization': 0.20263561924974124, 'max_features': 0.05206699267506896, 'max_bins': 104, 'interaction_cst': None, 'validation_fraction': 0.0903284172876723, 'n_iter_no_change': 5, 'tol': 8.553927859848842e-10, 'max_leaf_nodes': 61}. Best is trial 15 with value: 0.6326842901527467.
[I 2026-08-19 12:11:58,900] Trial 17 finished with value: 0.6324425592472434 and parameters: {'learning_rate': 0.004177670123774203, 'min_samples_leaf': 2013, 'l2_regularization': 2.7535109004930417e-07, 'max_features': 0.09330801681395996, 'max_bins': 128, 'interaction_cst': None, 'validation_fraction': 0.07448836864497999, 'n_iter_no_change': 8, 'tol': 6.438419234106952e-10, 'max_leaf_nodes': 41}. Best is trial 15 with value: 0.6326842901527467.
[I 2026-08-19 12:13:19,425] Trial 18 finished with value: 0.6260951032614444 and parameters: {'learning_rate': 0.003410500917024944, 'min_samples_leaf': 2068, 'l2_regularization': 0.10777937582836186, 'max_features': 0.12339862759469852, 'max_bins': 125, 'interaction_cst': 'pairwise', 'validation_fraction': 0.0724833903354674, 'n_iter_no_change': 8, 'tol': 6.928292497507946e-10, 'max_leaf_nodes': 42}. Best is trial 15 with value: 0.6326842901527467.
[I 2026-08-19 12:14:05,276] Trial 19 finished with value: 0.6218853793574314 and parameters: {'learning_rate': 0.005876864256855488, 'min_samples_leaf': 35513, 'l2_regularization': 8.211030695531792e-07, 'max_features': 0.15892209146415986, 'max_bins': 133, 'interaction_cst': None, 'validation_fraction': 0.07282869760048612, 'n_iter_no_change': 7, 'tol': 8.379682891506625e-10, 'max_leaf_nodes': 41}. Best is trial 15 with value: 0.6326842901527467.
[I 2026-08-19 12:14:54,745] Trial 20 finished with value: 0.6330248967237645 and parameters: {'learning_rate': 0.006365072231839667, 'min_samples_leaf': 2737, 'l2_regularization': 0.0035314167242860915, 'max_features': 0.09790219840412595, 'max_bins': 133, 'interaction_cst': None, 'validation_fraction': 0.08230224611361128, 'n_iter_no_change': 14, 'tol': 3.6241193980488433e-10, 'max_leaf_nodes': 54}. Best is trial 20 with value: 0.6330248967237645.
[I 2026-08-19 12:15:55,661] Trial 21 finished with value: 0.632737007763677 and parameters: {'learning_rate': 0.005520947909366304, 'min_samples_leaf': 2076, 'l2_regularization': 0.005531733866349145, 'max_features': 0.09168485843877174, 'max_bins': 137, 'interaction_cst': None, 'validation_fraction': 0.07991001755433379, 'n_iter_no_change': 14, 'tol': 3.580805958335903e-10, 'max_leaf_nodes': 55}. Best is trial 20 with value: 0.6330248967237645.
[I 2026-08-19 12:17:01,570] Trial 22 finished with value: 0.6300174607190494 and parameters: {'learning_rate': 0.006338353265184459, 'min_samples_leaf': 7446, 'l2_regularization': 0.0048764752625246295, 'max_features': 0.051020949219346086, 'max_bins': 138, 'interaction_cst': None, 'validation_fraction': 0.0824347477744436, 'n_iter_no_change': 15, 'tol': 2.6529749670812906e-10, 'max_leaf_nodes': 55}. Best is trial 20 with value: 0.6330248967237645.
[I 2026-08-19 12:18:08,181] Trial 23 finished with value: 0.6345385786600574 and parameters: {'learning_rate': 0.0065900982368848225, 'min_samples_leaf': 1257, 'l2_regularization': 1.5804919483283286, 'max_features': 0.10983287818825169, 'max_bins': 165, 'interaction_cst': None, 'validation_fraction': 0.09376256088307004, 'n_iter_no_change': 22, 'tol': 3.6008673810727267e-10, 'max_leaf_nodes': 57}. Best is trial 23 with value: 0.6345385786600574.
[I 2026-08-19 12:19:06,224] Trial 24 finished with value: 0.6339753571455358 and parameters: {'learning_rate': 0.005561772548588556, 'min_samples_leaf': 1006, 'l2_regularization': 0.5889093916177289, 'max_features': 0.15391265784097832, 'max_bins': 168, 'interaction_cst': None, 'validation_fraction': 0.08954934821641854, 'n_iter_no_change': 22, 'tol': 3.1577053008412667e-10, 'max_leaf_nodes': 54}. Best is trial 23 with value: 0.6345385786600574.
[I 2026-08-19 12:19:51,293] Trial 25 finished with value: 0.628178928008845 and parameters: {'learning_rate': 0.0077103144103518985, 'min_samples_leaf': 868, 'l2_regularization': 0.9647746062583308, 'max_features': 0.14589246165491396, 'max_bins': 174, 'interaction_cst': 'pairwise', 'validation_fraction': 0.09063522074387743, 'n_iter_no_change': 22, 'tol': 1.7281345476989036e-09, 'max_leaf_nodes': 51}. Best is trial 23 with value: 0.6345385786600574.
[I 2026-08-19 12:21:21,190] Trial 26 finished with value: 0.6313153927377206 and parameters: {'learning_rate': 0.009205301149616167, 'min_samples_leaf': 15441, 'l2_regularization': 803.01058484922, 'max_features': 0.11352802256019934, 'max_bins': 205, 'interaction_cst': None, 'validation_fraction': 0.06684251322664161, 'n_iter_no_change': 34, 'tol': 1.2479293591321095e-10, 'max_leaf_nodes': 57}. Best is trial 23 with value: 0.6345385786600574.
[I 2026-08-19 12:22:44,967] Trial 27 finished with value: 0.634659496364177 and parameters: {'learning_rate': 0.004560996946216292, 'min_samples_leaf': 4122, 'l2_regularization': 1.4394552803286365, 'max_features': 0.17247591405654472, 'max_bins': 165, 'interaction_cst': None, 'validation_fraction': 0.0864070322348755, 'n_iter_no_change': 23, 'tol': 1.7626290653374024e-09, 'max_leaf_nodes': 63}. Best is trial 27 with value: 0.634659496364177.
[I 2026-08-19 12:23:53,657] Trial 28 finished with value: 0.6341755361555069 and parameters: {'learning_rate': 0.004484741012565571, 'min_samples_leaf': 1077, 'l2_regularization': 1.7448401174825172, 'max_features': 0.17940074244692655, 'max_bins': 166, 'interaction_cst': None, 'validation_fraction': 0.09382342010803926, 'n_iter_no_change': 23, 'tol': 1.5176659508493544e-09, 'max_leaf_nodes': 63}. Best is trial 27 with value: 0.634659496364177.
[I 2026-08-19 12:25:50,851] Trial 29 finished with value: 0.6230366056122294 and parameters: {'learning_rate': 0.0044206163829193625, 'min_samples_leaf': 15927, 'l2_regularization': 2248.6669912478965, 'max_features': 0.18428625112684063, 'max_bins': 188, 'interaction_cst': 'pairwise', 'validation_fraction': 0.09170751591671367, 'n_iter_no_change': 32, 'tol': 1.583222605492724e-09, 'max_leaf_nodes': 60}. Best is trial 27 with value: 0.634659496364177.
[I 2026-08-19 12:26:28,221] Trial 30 finished with value: 0.6354664343361841 and parameters: {'learning_rate': 0.01199132085276806, 'min_samples_leaf': 5544, 'l2_regularization': 112.53853585803208, 'max_features': 0.2122008396955351, 'max_bins': 160, 'interaction_cst': None, 'validation_fraction': 0.09545320053134587, 'n_iter_no_change': 25, 'tol': 1.5433541750188835e-08, 'max_leaf_nodes': 63}. Best is trial 30 with value: 0.6354664343361841.
[I 2026-08-19 12:27:01,262] Trial 31 finished with value: 0.6355089508723555 and parameters: {'learning_rate': 0.011770051856348171, 'min_samples_leaf': 4587, 'l2_regularization': 3.477929534249391, 'max_features': 0.22533722573731005, 'max_bins': 164, 'interaction_cst': None, 'validation_fraction': 0.09550893433011438, 'n_iter_no_change': 25, 'tol': 1.235049882762607e-08, 'max_leaf_nodes': 63}. Best is trial 31 with value: 0.6355089508723555.
[I 2026-08-19 12:27:36,636] Trial 32 finished with value: 0.6350045483208071 and parameters: {'learning_rate': 0.013590095612999682, 'min_samples_leaf': 5857, 'l2_regularization': 94.50921065630251, 'max_features': 0.22326203923826304, 'max_bins': 179, 'interaction_cst': None, 'validation_fraction': 0.08666756810763349, 'n_iter_no_change': 25, 'tol': 1.4555783960509597e-07, 'max_leaf_nodes': 63}. Best is trial 31 with value: 0.6355089508723555.
[I 2026-08-19 12:28:09,089] Trial 33 finished with value: 0.6346064491676948 and parameters: {'learning_rate': 0.021517909587859575, 'min_samples_leaf': 4022, 'l2_regularization': 148.95440951286008, 'max_features': 0.22592452929002604, 'max_bins': 203, 'interaction_cst': None, 'validation_fraction': 0.08579466842989623, 'n_iter_no_change': 29, 'tol': 1.339743690548261e-07, 'max_leaf_nodes': 63}. Best is trial 31 with value: 0.6355089508723555.
[I 2026-08-19 12:30:52,296] Trial 34 finished with value: 0.6234914417122686 and parameters: {'learning_rate': 0.012622337859601481, 'min_samples_leaf': 12989, 'l2_regularization': 27962.235858555494, 'max_features': 0.22038670346023773, 'max_bins': 180, 'interaction_cst': None, 'validation_fraction': 0.07684061546016195, 'n_iter_no_change': 25, 'tol': 2.3018706921656918e-07, 'max_leaf_nodes': 60}. Best is trial 31 with value: 0.6355089508723555.
[I 2026-08-19 12:31:34,331] Trial 35 finished with value: 0.6358023222067422 and parameters: {'learning_rate': 0.01573830588080476, 'min_samples_leaf': 4715, 'l2_regularization': 169.39897430247444, 'max_features': 0.2513374760810013, 'max_bins': 196, 'interaction_cst': None, 'validation_fraction': 0.0683804938396908, 'n_iter_no_change': 31, 'tol': 1.3157447278857289e-08, 'max_leaf_nodes': 50}. Best is trial 35 with value: 0.6358023222067422.
[I 2026-08-19 12:33:18,105] Trial 36 finished with value: 0.6225953629065304 and parameters: {'learning_rate': 0.01647484866972427, 'min_samples_leaf': 8715, 'l2_regularization': 5585.6370174229205, 'max_features': 0.25462052183176676, 'max_bins': 203, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.06300010335164244, 'n_iter_no_change': 36, 'tol': 1.6128704964227734e-08, 'max_leaf_nodes': 51}. Best is trial 35 with value: 0.6358023222067422.
[I 2026-08-19 12:33:44,699] Trial 37 finished with value: 0.6292033602902963 and parameters: {'learning_rate': 0.016539625653142653, 'min_samples_leaf': 24787, 'l2_regularization': 91.78125125990249, 'max_features': 0.2906191324612584, 'max_bins': 189, 'interaction_cst': None, 'validation_fraction': 0.0662655233738043, 'n_iter_no_change': 31, 'tol': 1.179251232655144e-07, 'max_leaf_nodes': 58}. Best is trial 35 with value: 0.6358023222067422.
[I 2026-08-19 12:34:03,364] Trial 38 finished with value: 0.6301339249988848 and parameters: {'learning_rate': 0.02326089701593906, 'min_samples_leaf': 4205, 'l2_regularization': 6.122092848026212, 'max_features': 0.20237678299739081, 'max_bins': 214, 'interaction_cst': 'pairwise', 'validation_fraction': 0.04312179158679108, 'n_iter_no_change': 27, 'tol': 3.456103627789396e-07, 'max_leaf_nodes': 50}. Best is trial 35 with value: 0.6358023222067422.
[I 2026-08-19 12:34:48,729] Trial 39 finished with value: 0.6233446073296435 and parameters: {'learning_rate': 0.010841307148074762, 'min_samples_leaf': 11180, 'l2_regularization': 180.25424847650234, 'max_features': 0.21123289841075746, 'max_bins': 158, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.09590782205518016, 'n_iter_no_change': 25, 'tol': 5.833212382516872e-09, 'max_leaf_nodes': 59}. Best is trial 35 with value: 0.6358023222067422.
[I 2026-08-19 12:35:28,235] Trial 40 finished with value: 0.6358730384042651 and parameters: {'learning_rate': 0.013833865335098918, 'min_samples_leaf': 5711, 'l2_regularization': 10.739859902750874, 'max_features': 0.2452236936429963, 'max_bins': 225, 'interaction_cst': None, 'validation_fraction': 0.05936357869170278, 'n_iter_no_change': 37, 'tol': 1.6001697814815863e-08, 'max_leaf_nodes': 45}. Best is trial 40 with value: 0.6358730384042651.
[I 2026-08-19 12:36:00,843] Trial 41 finished with value: 0.636600457832917 and parameters: {'learning_rate': 0.014521736210156313, 'min_samples_leaf': 5975, 'l2_regularization': 10.262130162526471, 'max_features': 0.24775997297590835, 'max_bins': 231, 'interaction_cst': None, 'validation_fraction': 0.0573133556070173, 'n_iter_no_change': 38, 'tol': 1.2095870910048285e-08, 'max_leaf_nodes': 36}. Best is trial 41 with value: 0.636600457832917.
[I 2026-08-19 12:36:20,465] Trial 42 finished with value: 0.6355097145461948 and parameters: {'learning_rate': 0.028020659895621195, 'min_samples_leaf': 3282, 'l2_regularization': 16.451519597395137, 'max_features': 0.24635804591166155, 'max_bins': 229, 'interaction_cst': None, 'validation_fraction': 0.05206320937558668, 'n_iter_no_change': 38, 'tol': 1.627438027977471e-08, 'max_leaf_nodes': 30}. Best is trial 41 with value: 0.636600457832917.
[I 2026-08-19 12:36:33,918] Trial 43 finished with value: 0.6345765855012406 and parameters: {'learning_rate': 0.02744790658702949, 'min_samples_leaf': 3341, 'l2_regularization': 10.482029424579991, 'max_features': 0.24618763309630315, 'max_bins': 223, 'interaction_cst': None, 'validation_fraction': 0.049901089930171214, 'n_iter_no_change': 38, 'tol': 9.640469493251888e-09, 'max_leaf_nodes': 30}. Best is trial 41 with value: 0.636600457832917.

In [20]:
pd.DataFrame({
    "best auc_val": study_leaf_calc.best_value,
    "best gini": 2 * study_leaf_calc.best_value - 1,
    "trials": len(study_leaf_calc.trials),
    "pruned": len([t for t in study_leaf_calc.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_leaf_calc.trials if t.state.name == "FAIL"]),
    "best params": study_leaf_calc.best_params
})

                     best auc_val  best gini  ...  fail   best params
learning_rate              0.6366   0.273201  ...     0  1.452174e-02
min_samples_leaf           0.6366   0.273201  ...     0  5.975000e+03
l2_regularization          0.6366   0.273201  ...     0  1.026213e+01
max_features               0.6366   0.273201  ...     0  2.477600e-01
max_bins                   0.6366   0.273201  ...     0  2.310000e+02
interaction_cst            0.6366   0.273201  ...     0           NaN
validation_fraction        0.6366   0.273201  ...     0  5.731336e-02
n_iter_no_change           0.6366   0.273201  ...     0  3.800000e+01
tol                        0.6366   0.273201  ...     0  1.209587e-08
max_leaf_nodes             0.6366   0.273201  ...     0  3.600000e+01

[10 rows x 6 columns]

In [21]:
study_leaf_calc.best_params

{'learning_rate': 0.014521736210156313,
 'min_samples_leaf': 5975,
 'l2_regularization': 10.262130162526471,
 'max_features': 0.24775997297590835,
 'max_bins': 231,
 'interaction_cst': None,
 'validation_fraction': 0.0573133556070173,
 'n_iter_no_change': 38,
 'tol': 1.2095870910048285e-08,
 'max_leaf_nodes': 36}

## Leaf ohne Calc

In [22]:
def objective_leaf_no_calc(trial):

    modell = HistGradientBoostingClassifier(
        **fixed_params_leaf,
        **suchraum_params_leaf(trial)
    )

    modell.fit(x_train_hgb_no_calc, y_train)

    return roc_auc_score(y_val, modell.predict_proba(x_val_hgb_no_calc)[:, 1])

In [23]:
study_leaf_no_calc = optuna.create_study(
    study_name = "HGB_leaf_no_calc",
    storage = "sqlite:///HGB_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=500)
)

[I 2026-08-19 12:41:56,004] A new study created in RDB with name: HGB_leaf_no_calc

In [24]:
study_leaf_no_calc.optimize(
    objective_leaf_no_calc,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

[I 2026-08-19 12:42:33,260] Trial 0 finished with value: 0.6223147167899088 and parameters: {'learning_rate': 0.01683454924600351, 'min_samples_leaf': 25553, 'l2_regularization': 32.8035800581182, 'max_features': 0.22959754525911097, 'max_bins': 127, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.0641003510568888, 'n_iter_no_change': 30, 'tol': 1.267425589893721e-10, 'max_leaf_nodes': 62}. Best is trial 0 with value: 0.6223147167899088.
[I 2026-08-19 12:42:35,179] Trial 1 finished with value: 0.6284335408862172 and parameters: {'learning_rate': 0.13867767003062487, 'min_samples_leaf': 31, 'l2_regularization': 2.3105989608604262e-06, 'max_features': 0.10502135295603016, 'max_bins': 150, 'interaction_cst': None, 'validation_fraction': 0.06506676052501416, 'n_iter_no_change': 10, 'tol': 2.888838362365319e-09, 'max_leaf_nodes': 24}. Best is trial 1 with value: 0.6284335408862172.
[I 2026-08-19 12:42:48,262] Trial 2 finished with value: 0.6290737527817523 and parameters: {'learning_rate': 0.02450536768428048, 'min_samples_leaf': 5672, 'l2_regularization': 3.94238621924438e-06, 'max_features': 0.20427033152408347, 'max_bins': 194, 'interaction_cst': 'pairwise', 'validation_fraction': 0.015854643368675158, 'n_iter_no_change': 39, 'tol': 6.732248920775334e-06, 'max_leaf_nodes': 52}. Best is trial 2 with value: 0.6290737527817523.
[I 2026-08-19 12:43:22,733] Trial 3 finished with value: 0.622933887461502 and parameters: {'learning_rate': 0.012199689940544376, 'min_samples_leaf': 11, 'l2_regularization': 7.852886936532546, 'max_features': 0.1820457481218804, 'max_bins': 122, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.03329019834400153, 'n_iter_no_change': 28, 'tol': 3.618723330959621e-09, 'max_leaf_nodes': 34}. Best is trial 2 with value: 0.6290737527817523.
[I 2026-08-19 12:44:24,673] Trial 4 finished with value: 0.6162335538718877 and parameters: {'learning_rate': 0.037199903510538264, 'min_samples_leaf': 24, 'l2_regularization': 40234.64380902767, 'max_features': 0.28253984700833434, 'max_bins': 246, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.017964325184672756, 'n_iter_no_change': 12, 'tol': 1.6832027985721906e-10, 'max_leaf_nodes': 22}. Best is trial 2 with value: 0.6290737527817523.
[I 2026-08-19 12:44:54,969] Trial 5 finished with value: 0.6241069387107612 and parameters: {'learning_rate': 0.01796701101676289, 'min_samples_leaf': 53, 'l2_regularization': 593.7281208438861, 'max_features': 0.1570259980080768, 'max_bins': 146, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.016709557931179377, 'n_iter_no_change': 40, 'tol': 7.26480307482673e-07, 'max_leaf_nodes': 14}. Best is trial 2 with value: 0.6290737527817523.
[I 2026-08-19 12:46:26,296] Trial 6 finished with value: 0.628796153321816 and parameters: {'learning_rate': 0.0030772691922556945, 'min_samples_leaf': 7471, 'l2_regularization': 15.457721201756003, 'max_features': 0.26870215041229617, 'max_bins': 221, 'interaction_cst': 'pairwise', 'validation_fraction': 0.08767930832880343, 'n_iter_no_change': 27, 'tol': 4.513257622008936e-09, 'max_leaf_nodes': 5}. Best is trial 2 with value: 0.6290737527817523.
[I 2026-08-19 12:46:57,923] Trial 7 finished with value: 0.6223643395121219 and parameters: {'learning_rate': 0.012562784156701876, 'min_samples_leaf': 87, 'l2_regularization': 30.540793629644874, 'max_features': 0.24126724140656391, 'max_bins': 238, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.07847065437552077, 'n_iter_no_change': 25, 'tol': 7.158728631500194e-07, 'max_leaf_nodes': 32}. Best is trial 2 with value: 0.6290737527817523.
[I 2026-08-19 12:47:04,564] Trial 8 finished with value: 0.6327151827692159 and parameters: {'learning_rate': 0.033310941939163854, 'min_samples_leaf': 220, 'l2_regularization': 2.1401718512509955e-08, 'max_features': 0.08236742809799133, 'max_bins': 108, 'interaction_cst': None, 'validation_fraction': 0.09168098265334837, 'n_iter_no_change': 13, 'tol': 1.1269758643814652e-08, 'max_leaf_nodes': 48}. Best is trial 8 with value: 0.6327151827692159.
[I 2026-08-19 12:47:27,331] Trial 9 finished with value: 0.6167000098722931 and parameters: {'learning_rate': 0.008604340446309018, 'min_samples_leaf': 9, 'l2_regularization': 5.844789677758518e-05, 'max_features': 0.09836638617620133, 'max_bins': 245, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.0823304869209203, 'n_iter_no_change': 11, 'tol': 2.9026521418263896e-06, 'max_leaf_nodes': 35}. Best is trial 8 with value: 0.6327151827692159.
[I 2026-08-19 12:47:28,717] Trial 10 finished with value: 0.6266301411919584 and parameters: {'learning_rate': 0.24554140659956822, 'min_samples_leaf': 333, 'l2_regularization': 1.2534734834039077e-08, 'max_features': 0.3296871025735361, 'max_bins': 182, 'interaction_cst': None, 'validation_fraction': 0.042518079679762844, 'n_iter_no_change': 5, 'tol': 5.4675303863547164e-08, 'max_leaf_nodes': 47}. Best is trial 8 with value: 0.6327151827692159.
[I 2026-08-19 12:47:36,894] Trial 11 finished with value: 0.628965343251254 and parameters: {'learning_rate': 0.055493794544567765, 'min_samples_leaf': 1234, 'l2_regularization': 0.00022939453595477533, 'max_features': 0.06601442426626078, 'max_bins': 194, 'interaction_cst': 'pairwise', 'validation_fraction': 0.09883283829600645, 'n_iter_no_change': 40, 'tol': 5.6367675593144375e-08, 'max_leaf_nodes': 55}. Best is trial 8 with value: 0.6327151827692159.
[I 2026-08-19 12:47:43,749] Trial 12 finished with value: 0.6280510488147794 and parameters: {'learning_rate': 0.04905210146583551, 'min_samples_leaf': 2377, 'l2_regularization': 1.7998196807046904e-08, 'max_features': 0.1632482856156553, 'max_bins': 108, 'interaction_cst': 'pairwise', 'validation_fraction': 0.04793404566344977, 'n_iter_no_change': 21, 'tol': 7.887577413194241e-06, 'max_leaf_nodes': 48}. Best is trial 8 with value: 0.6327151827692159.
[I 2026-08-19 12:47:46,985] Trial 13 finished with value: 0.6336813346787176 and parameters: {'learning_rate': 0.08688481071804603, 'min_samples_leaf': 368, 'l2_regularization': 0.004498254932680299, 'max_features': 0.3471805600806288, 'max_bins': 179, 'interaction_cst': None, 'validation_fraction': 0.05987657928205367, 'n_iter_no_change': 18, 'tol': 1.0089309882791848e-07, 'max_leaf_nodes': 46}. Best is trial 13 with value: 0.6336813346787176.
[I 2026-08-19 12:47:49,917] Trial 14 finished with value: 0.6325839032168973 and parameters: {'learning_rate': 0.10118854084445855, 'min_samples_leaf': 285, 'l2_regularization': 0.020371947606485814, 'max_features': 0.34591598719331107, 'max_bins': 161, 'interaction_cst': None, 'validation_fraction': 0.06306386516611832, 'n_iter_no_change': 18, 'tol': 3.089069228882131e-08, 'max_leaf_nodes': 41}. Best is trial 13 with value: 0.6336813346787176.
[I 2026-08-19 12:47:52,864] Trial 15 finished with value: 0.6315023963642952 and parameters: {'learning_rate': 0.09170013884812149, 'min_samples_leaf': 289, 'l2_regularization': 0.009712586400259585, 'max_features': 0.3054296194394985, 'max_bins': 171, 'interaction_cst': None, 'validation_fraction': 0.0979336273679862, 'n_iter_no_change': 16, 'tol': 2.0090753682926005e-07, 'max_leaf_nodes': 61}. Best is trial 13 with value: 0.6336813346787176.
[I 2026-08-19 12:47:54,307] Trial 16 finished with value: 0.631006900661315 and parameters: {'learning_rate': 0.2811506402608882, 'min_samples_leaf': 891, 'l2_regularization': 0.0573495724052183, 'max_features': 0.1275708505571809, 'max_bins': 217, 'interaction_cst': None, 'validation_fraction': 0.07185260188789533, 'n_iter_no_change': 6, 'tol': 1.5153019002715068e-08, 'max_leaf_nodes': 42}. Best is trial 13 with value: 0.6336813346787176.
[I 2026-08-19 12:47:56,740] Trial 17 finished with value: 0.6310430746852838 and parameters: {'learning_rate': 0.15546493891228116, 'min_samples_leaf': 132, 'l2_regularization': 2.2368580623077475e-07, 'max_features': 0.07008991674013271, 'max_bins': 135, 'interaction_cst': None, 'validation_fraction': 0.042641720279635906, 'n_iter_no_change': 16, 'tol': 6.438419234106952e-10, 'max_leaf_nodes': 55}. Best is trial 13 with value: 0.6336813346787176.
[I 2026-08-19 12:48:00,821] Trial 18 finished with value: 0.6340960658441835 and parameters: {'learning_rate': 0.07144014542466597, 'min_samples_leaf': 739, 'l2_regularization': 0.0008570127998766416, 'max_features': 0.2236639020871625, 'max_bins': 110, 'interaction_cst': None, 'validation_fraction': 0.052824827416605984, 'n_iter_no_change': 22, 'tol': 1.859601186581151e-07, 'max_leaf_nodes': 41}. Best is trial 18 with value: 0.6340960658441835.
[I 2026-08-19 12:48:06,196] Trial 19 finished with value: 0.6331163607337015 and parameters: {'learning_rate': 0.07082980440903153, 'min_samples_leaf': 825, 'l2_regularization': 0.0009777812280119828, 'max_features': 0.3016694050521777, 'max_bins': 204, 'interaction_cst': None, 'validation_fraction': 0.05284476454224033, 'n_iter_no_change': 32, 'tol': 1.9443061514226793e-07, 'max_leaf_nodes': 25}. Best is trial 18 with value: 0.6340960658441835.
[I 2026-08-19 12:48:08,888] Trial 20 finished with value: 0.6319194024739352 and parameters: {'learning_rate': 0.15108652239392678, 'min_samples_leaf': 2765, 'l2_regularization': 0.5531484100854281, 'max_features': 0.2566888000455919, 'max_bins': 171, 'interaction_cst': None, 'validation_fraction': 0.05562336529573156, 'n_iter_no_change': 21, 'tol': 2.423980985803599e-07, 'max_leaf_nodes': 40}. Best is trial 18 with value: 0.6340960658441835.
[I 2026-08-19 12:48:13,471] Trial 21 finished with value: 0.6339875357336052 and parameters: {'learning_rate': 0.07087297965013734, 'min_samples_leaf': 744, 'l2_regularization': 0.0005006468284903911, 'max_features': 0.3053039651116837, 'max_bins': 210, 'interaction_cst': None, 'validation_fraction': 0.050646970737476885, 'n_iter_no_change': 31, 'tol': 1.5945959870945529e-07, 'max_leaf_nodes': 24}. Best is trial 18 with value: 0.6340960658441835.
[I 2026-08-19 12:48:18,393] Trial 22 finished with value: 0.6338581613465489 and parameters: {'learning_rate': 0.06667212714787642, 'min_samples_leaf': 595, 'l2_regularization': 0.0017127113152859185, 'max_features': 0.31891132062032385, 'max_bins': 227, 'interaction_cst': None, 'validation_fraction': 0.029163661069284412, 'n_iter_no_change': 35, 'tol': 1.0136753505187713e-06, 'max_leaf_nodes': 11}. Best is trial 18 with value: 0.6340960658441835.
[I 2026-08-19 12:48:29,434] Trial 23 finished with value: 0.6303718495931994 and parameters: {'learning_rate': 0.04923128187689943, 'min_samples_leaf': 696, 'l2_regularization': 3.8404734635537834e-05, 'max_features': 0.3075580308711734, 'max_bins': 229, 'interaction_cst': None, 'validation_fraction': 0.028258721802914166, 'n_iter_no_change': 34, 'tol': 9.974520474509106e-07, 'max_leaf_nodes': 4}. Best is trial 18 with value: 0.6340960658441835.
[I 2026-08-19 12:48:35,124] Trial 24 finished with value: 0.6315093739315851 and parameters: {'learning_rate': 0.06649524671185368, 'min_samples_leaf': 1841, 'l2_regularization': 1.4036293110737319e-05, 'max_features': 0.22551571725004124, 'max_bins': 209, 'interaction_cst': None, 'validation_fraction': 0.03378072294531602, 'n_iter_no_change': 35, 'tol': 2.2186830339379393e-06, 'max_leaf_nodes': 12}. Best is trial 18 with value: 0.6340960658441835.
[I 2026-08-19 12:48:44,074] Trial 25 finished with value: 0.6354460482640097 and parameters: {'learning_rate': 0.03454877247794397, 'min_samples_leaf': 4220, 'l2_regularization': 0.26169545768148283, 'max_features': 0.28413218038935056, 'max_bins': 198, 'interaction_cst': None, 'validation_fraction': 0.025474285822670372, 'n_iter_no_change': 36, 'tol': 3.840879372571634e-07, 'max_leaf_nodes': 16}. Best is trial 25 with value: 0.6354460482640097.
[I 2026-08-19 12:48:53,170] Trial 26 finished with value: 0.6348120864359492 and parameters: {'learning_rate': 0.033765373242483326, 'min_samples_leaf': 12837, 'l2_regularization': 0.522401806999554, 'max_features': 0.27808560488085293, 'max_bins': 254, 'interaction_cst': None, 'validation_fraction': 0.04139293636549933, 'n_iter_no_change': 23, 'tol': 2.9488877319404626e-07, 'max_leaf_nodes': 19}. Best is trial 25 with value: 0.6354460482640097.
[I 2026-08-19 12:49:05,480] Trial 27 finished with value: 0.632285515751187 and parameters: {'learning_rate': 0.030759212057711368, 'min_samples_leaf': 22588, 'l2_regularization': 0.37575523434947994, 'max_features': 0.2776167687006001, 'max_bins': 253, 'interaction_cst': None, 'validation_fraction': 0.024222063238026847, 'n_iter_no_change': 23, 'tol': 3.2844991561353843e-07, 'max_leaf_nodes': 19}. Best is trial 25 with value: 0.6354460482640097.
[I 2026-08-19 12:49:17,618] Trial 28 finished with value: 0.6345428311175417 and parameters: {'learning_rate': 0.023414291235951915, 'min_samples_leaf': 11057, 'l2_regularization': 0.09974352008231131, 'max_features': 0.20931882356431336, 'max_bins': 153, 'interaction_cst': None, 'validation_fraction': 0.04178423741851735, 'n_iter_no_change': 25, 'tol': 4.580144730561454e-07, 'max_leaf_nodes': 17}. Best is trial 25 with value: 0.6354460482640097.
[I 2026-08-19 12:49:25,341] Trial 29 finished with value: 0.6182354766096871 and parameters: {'learning_rate': 0.01989151997410562, 'min_samples_leaf': 30899, 'l2_regularization': 260.26792135029274, 'max_features': 0.20761930310510393, 'max_bins': 135, 'interaction_cst': 'pairwise', 'validation_fraction': 0.010177798564500566, 'n_iter_no_change': 29, 'tol': 2.246247870233833e-06, 'max_leaf_nodes': 17}. Best is trial 25 with value: 0.6354460482640097.
[I 2026-08-19 12:50:00,004] Trial 30 finished with value: 0.635772410308256 and parameters: {'learning_rate': 0.006438937945041666, 'min_samples_leaf': 9255, 'l2_regularization': 0.642043766781501, 'max_features': 0.2553210436678902, 'max_bins': 195, 'interaction_cst': None, 'validation_fraction': 0.0405404893912014, 'n_iter_no_change': 25, 'tol': 5.705961893739617e-07, 'max_leaf_nodes': 29}. Best is trial 30 with value: 0.635772410308256.
[I 2026-08-19 12:50:50,966] Trial 31 finished with value: 0.635091422249036 and parameters: {'learning_rate': 0.005600584024611953, 'min_samples_leaf': 13357, 'l2_regularization': 1.193903478459263, 'max_features': 0.24995261528355123, 'max_bins': 194, 'interaction_cst': None, 'validation_fraction': 0.03956150310418299, 'n_iter_no_change': 25, 'tol': 5.225920046855066e-07, 'max_leaf_nodes': 29}. Best is trial 30 with value: 0.635772410308256.
[I 2026-08-19 12:51:42,643] Trial 32 finished with value: 0.6347543687710391 and parameters: {'learning_rate': 0.004685624409534816, 'min_samples_leaf': 14446, 'l2_regularization': 0.5482444376335031, 'max_features': 0.24686555010732805, 'max_bins': 194, 'interaction_cst': None, 'validation_fraction': 0.036510100886152815, 'n_iter_no_change': 26, 'tol': 7.532199536406732e-08, 'max_leaf_nodes': 29}. Best is trial 30 with value: 0.635772410308256.
[I 2026-08-19 12:52:23,104] Trial 33 finished with value: 0.6366290031571643 and parameters: {'learning_rate': 0.00594879129434682, 'min_samples_leaf': 4631, 'l2_regularization': 3.151722464968134, 'max_features': 0.28612377429945113, 'max_bins': 186, 'interaction_cst': None, 'validation_fraction': 0.03875509378324408, 'n_iter_no_change': 37, 'tol': 1.7836664497302137e-06, 'max_leaf_nodes': 30}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:53:00,266] Trial 34 finished with value: 0.6364886961761975 and parameters: {'learning_rate': 0.006398122212179539, 'min_samples_leaf': 3904, 'l2_regularization': 3.0191266147092706, 'max_features': 0.2592874867288397, 'max_bins': 186, 'interaction_cst': None, 'validation_fraction': 0.022320765084500434, 'n_iter_no_change': 37, 'tol': 3.9607284520134444e-06, 'max_leaf_nodes': 30}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:53:56,976] Trial 35 finished with value: 0.6362597467591632 and parameters: {'learning_rate': 0.007155215413418921, 'min_samples_leaf': 4391, 'l2_regularization': 613.5832695775857, 'max_features': 0.2858315529338463, 'max_bins': 184, 'interaction_cst': None, 'validation_fraction': 0.022352555788027154, 'n_iter_no_change': 36, 'tol': 4.3453888045031795e-06, 'max_leaf_nodes': 36}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:54:49,832] Trial 36 finished with value: 0.6133157691565755 and parameters: {'learning_rate': 0.006773156004402018, 'min_samples_leaf': 4581, 'l2_regularization': 5585.6370174229205, 'max_features': 0.2613265267258382, 'max_bins': 183, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.020141449200782067, 'n_iter_no_change': 38, 'tol': 4.65381306960855e-06, 'max_leaf_nodes': 36}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:55:36,029] Trial 37 finished with value: 0.6316305729892244 and parameters: {'learning_rate': 0.003402069920023806, 'min_samples_leaf': 7120, 'l2_regularization': 130.6305633114332, 'max_features': 0.18326097324545879, 'max_bins': 168, 'interaction_cst': None, 'validation_fraction': 0.01013050106134783, 'n_iter_no_change': 37, 'tol': 1.489146770576815e-06, 'max_leaf_nodes': 28}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:55:59,156] Trial 38 finished with value: 0.6280132911724281 and parameters: {'learning_rate': 0.010454512054858874, 'min_samples_leaf': 3556, 'l2_regularization': 4.365308034864513, 'max_features': 0.2885372651724599, 'max_bins': 186, 'interaction_cst': 'pairwise', 'validation_fraction': 0.031100578045039004, 'n_iter_no_change': 33, 'tol': 4.846094499009878e-06, 'max_leaf_nodes': 32}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:56:24,636] Trial 39 finished with value: 0.6146315791817591 and parameters: {'learning_rate': 0.007897700933937508, 'min_samples_leaf': 21054, 'l2_regularization': 1545.9835765889968, 'max_features': 0.23204400470068598, 'max_bins': 158, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.019323524528985087, 'n_iter_no_change': 30, 'tol': 9.553473003847297e-06, 'max_leaf_nodes': 37}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:58:13,205] Trial 40 finished with value: 0.6268429248396147 and parameters: {'learning_rate': 0.014660008484667473, 'min_samples_leaf': 1602, 'l2_regularization': 28887.40290641184, 'max_features': 0.26791808042506604, 'max_bins': 177, 'interaction_cst': None, 'validation_fraction': 0.04647449499378174, 'n_iter_no_change': 38, 'tol': 3.2749685399087896e-06, 'max_leaf_nodes': 27}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:59:02,027] Trial 41 finished with value: 0.6362990317491932 and parameters: {'learning_rate': 0.004219557801087054, 'min_samples_leaf': 5249, 'l2_regularization': 3.28561698684069, 'max_features': 0.2899113829277475, 'max_bins': 201, 'interaction_cst': None, 'validation_fraction': 0.023955947151521842, 'n_iter_no_change': 36, 'tol': 1.1718670555979885e-06, 'max_leaf_nodes': 32}. Best is trial 33 with value: 0.6366290031571643.
[I 2026-08-19 12:59:55,567] Trial 42 finished with value: 0.6367181681069113 and parameters: {'learning_rate': 0.004338123809038022, 'min_samples_leaf': 5908, 'l2_regularization': 3.3250760273671296, 'max_features': 0.29104454290959547, 'max_bins': 187, 'interaction_cst': None, 'validation_fraction': 0.023399098429884118, 'n_iter_no_change': 40, 'tol': 1.489260698077153e-06, 'max_leaf_nodes': 32}. Best is trial 42 with value: 0.6367181681069113.
[I 2026-08-19 13:00:48,953] Trial 43 finished with value: 0.6363579310988865 and parameters: {'learning_rate': 0.0041485673075862955, 'min_samples_leaf': 6016, 'l2_regularization': 5.079693205411676, 'max_features': 0.2877674212951193, 'max_bins': 187, 'interaction_cst': None, 'validation_fraction': 0.022954108458583363, 'n_iter_no_change': 40, 'tol': 1.544681612884463e-06, 'max_leaf_nodes': 32}. Best is trial 42 with value: 0.6367181681069113.

In [25]:
pd.DataFrame({
    "best auc_val": study_leaf_no_calc.best_value,
    "best gini": 2 * study_leaf_no_calc.best_value - 1,
    "trials": len(study_leaf_no_calc.trials),
    "pruned": len([t for t in study_leaf_no_calc.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_leaf_no_calc.trials if t.state.name == "FAIL"]),
    "best params": study_leaf_no_calc.best_params
})

                     best auc_val  best gini  trials  pruned  fail  best params
learning_rate            0.638318   0.276637      50       0     0     0.004109
min_samples_leaf         0.638318   0.276637      50       0     0  6833.000000
l2_regularization        0.638318   0.276637      50       0     0    52.458189
max_features             0.638318   0.276637      50       0     0     0.296687
max_bins                 0.638318   0.276637      50       0     0   202.000000
interaction_cst          0.638318   0.276637      50       0     0          NaN
validation_fraction      0.638318   0.276637      50       0     0     0.013916
n_iter_no_change         0.638318   0.276637      50       0     0    40.000000
tol                      0.638318   0.276637      50       0     0     0.000001
max_leaf_nodes           0.638318   0.276637      50       0     0    32.000000

In [26]:
study_leaf_no_calc.best_params

{'learning_rate': 0.004108690179427848,
 'min_samples_leaf': 6833,
 'l2_regularization': 52.45818863330329,
 'max_features': 0.2966869253501312,
 'max_bins': 202,
 'interaction_cst': None,
 'validation_fraction': 0.01391561653087682,
 'n_iter_no_change': 40,
 'tol': 1.4783911269827303e-06,
 'max_leaf_nodes': 32}

## Depth mit Calc

In [27]:
def objective_depth_calc(trial):

    modell = HistGradientBoostingClassifier(
        **fixed_params_depth,
        **suchraum_params_depth(trial)
    )

    modell.fit(x_train_hgb, y_train)

    return roc_auc_score(y_val, modell.predict_proba(x_val_hgb)[:, 1])

In [28]:
study_depth_calc = optuna.create_study(
    study_name = "HGB_depth_calc",
    storage = "sqlite:///HGB_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=500)
)

[I 2026-08-19 13:07:38,842] A new study created in RDB with name: HGB_depth_calc

In [29]:
study_depth_calc.optimize(
    objective_depth_calc,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

[I 2026-08-19 13:08:09,094] Trial 0 finished with value: 0.6208656496990961 and parameters: {'learning_rate': 0.01683454924600351, 'min_samples_leaf': 25553, 'l2_regularization': 32.8035800581182, 'max_features': 0.22959754525911097, 'max_bins': 127, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.0641003510568888, 'n_iter_no_change': 30, 'tol': 1.267425589893721e-10, 'max_depth': 6}. Best is trial 0 with value: 0.6208656496990961.
[I 2026-08-19 13:08:12,436] Trial 1 finished with value: 0.6265900000833611 and parameters: {'learning_rate': 0.13867767003062487, 'min_samples_leaf': 31, 'l2_regularization': 2.3105989608604262e-06, 'max_features': 0.10502135295603016, 'max_bins': 150, 'interaction_cst': None, 'validation_fraction': 0.06506676052501416, 'n_iter_no_change': 10, 'tol': 2.888838362365319e-09, 'max_depth': 3}. Best is trial 1 with value: 0.6265900000833611.
[I 2026-08-19 13:08:28,265] Trial 2 finished with value: 0.6292753787526822 and parameters: {'learning_rate': 0.02450536768428048, 'min_samples_leaf': 5672, 'l2_regularization': 3.94238621924438e-06, 'max_features': 0.20427033152408347, 'max_bins': 194, 'interaction_cst': 'pairwise', 'validation_fraction': 0.015854643368675158, 'n_iter_no_change': 39, 'tol': 6.732248920775334e-06, 'max_depth': 5}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:09:10,338] Trial 3 finished with value: 0.6230574740047233 and parameters: {'learning_rate': 0.012199689940544376, 'min_samples_leaf': 11, 'l2_regularization': 7.852886936532546, 'max_features': 0.1820457481218804, 'max_bins': 122, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.03329019834400153, 'n_iter_no_change': 28, 'tol': 3.618723330959621e-09, 'max_depth': 4}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:09:57,792] Trial 4 finished with value: 0.6118677551317938 and parameters: {'learning_rate': 0.037199903510538264, 'min_samples_leaf': 24, 'l2_regularization': 40234.64380902767, 'max_features': 0.28253984700833434, 'max_bins': 246, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.017964325184672756, 'n_iter_no_change': 12, 'tol': 1.6832027985721906e-10, 'max_depth': 2}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:10:56,546] Trial 5 finished with value: 0.6263563601012188 and parameters: {'learning_rate': 0.01796701101676289, 'min_samples_leaf': 53, 'l2_regularization': 593.7281208438861, 'max_features': 0.1570259980080768, 'max_bins': 146, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.016709557931179377, 'n_iter_no_change': 40, 'tol': 7.26480307482673e-07, 'max_depth': 2}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:12:28,451] Trial 6 finished with value: 0.6185629359326604 and parameters: {'learning_rate': 0.0030772691922556945, 'min_samples_leaf': 7471, 'l2_regularization': 15.457721201756003, 'max_features': 0.26870215041229617, 'max_bins': 221, 'interaction_cst': 'pairwise', 'validation_fraction': 0.08767930832880343, 'n_iter_no_change': 27, 'tol': 4.513257622008936e-09, 'max_depth': 1}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:13:10,976] Trial 7 finished with value: 0.6237185422347445 and parameters: {'learning_rate': 0.012562784156701876, 'min_samples_leaf': 87, 'l2_regularization': 30.540793629644874, 'max_features': 0.24126724140656391, 'max_bins': 238, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.07847065437552077, 'n_iter_no_change': 25, 'tol': 7.158728631500194e-07, 'max_depth': 3}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:13:20,257] Trial 8 finished with value: 0.6277981280778617 and parameters: {'learning_rate': 0.033310941939163854, 'min_samples_leaf': 220, 'l2_regularization': 2.1401718512509955e-08, 'max_features': 0.08236742809799133, 'max_bins': 108, 'interaction_cst': None, 'validation_fraction': 0.09168098265334837, 'n_iter_no_change': 13, 'tol': 1.1269758643814652e-08, 'max_depth': 5}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:13:47,462] Trial 9 finished with value: 0.6181744550505879 and parameters: {'learning_rate': 0.008604340446309018, 'min_samples_leaf': 9, 'l2_regularization': 5.844789677758518e-05, 'max_features': 0.09836638617620133, 'max_bins': 245, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.0823304869209203, 'n_iter_no_change': 11, 'tol': 2.9026521418263896e-06, 'max_depth': 4}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:13:51,243] Trial 10 finished with value: 0.628374508898436 and parameters: {'learning_rate': 0.241151417537371, 'min_samples_leaf': 724, 'l2_regularization': 0.00875770364290532, 'max_features': 0.3296871025735361, 'max_bins': 194, 'interaction_cst': 'pairwise', 'validation_fraction': 0.042518079679762844, 'n_iter_no_change': 39, 'tol': 7.124252843547845e-08, 'max_depth': 6}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:13:54,160] Trial 11 finished with value: 0.6254085122478452 and parameters: {'learning_rate': 0.28899499483894037, 'min_samples_leaf': 1234, 'l2_regularization': 0.009111575055313376, 'max_features': 0.3437845844969563, 'max_bins': 195, 'interaction_cst': 'pairwise', 'validation_fraction': 0.04104554270673259, 'n_iter_no_change': 40, 'tol': 1.1120142058393473e-07, 'max_depth': 6}. Best is trial 2 with value: 0.6292753787526822.
[I 2026-08-19 13:14:01,429] Trial 12 finished with value: 0.6296424486319012 and parameters: {'learning_rate': 0.08755364352686051, 'min_samples_leaf': 2377, 'l2_regularization': 0.012392754474826611, 'max_features': 0.3269048324908785, 'max_bins': 186, 'interaction_cst': 'pairwise', 'validation_fraction': 0.03969785846829931, 'n_iter_no_change': 37, 'tol': 8.316430200376446e-06, 'max_depth': 5}. Best is trial 12 with value: 0.6296424486319012.
[I 2026-08-19 13:14:06,753] Trial 13 finished with value: 0.628606263811996 and parameters: {'learning_rate': 0.08688481071804603, 'min_samples_leaf': 3093, 'l2_regularization': 0.005889008508495228, 'max_features': 0.1939106376742602, 'max_bins': 181, 'interaction_cst': 'pairwise', 'validation_fraction': 0.028586940834054275, 'n_iter_no_change': 35, 'tol': 9.434550772187525e-06, 'max_depth': 5}. Best is trial 12 with value: 0.6296424486319012.
[I 2026-08-19 13:14:15,703] Trial 14 finished with value: 0.6249418994933362 and parameters: {'learning_rate': 0.05719752096456939, 'min_samples_leaf': 30426, 'l2_regularization': 2.105149155571895e-05, 'max_features': 0.3140088104586761, 'max_bins': 172, 'interaction_cst': 'pairwise', 'validation_fraction': 0.011266731119408641, 'n_iter_no_change': 33, 'tol': 7.059503101601697e-06, 'max_depth': 5}. Best is trial 12 with value: 0.6296424486319012.
[I 2026-08-19 13:14:21,141] Trial 15 finished with value: 0.6300149365760435 and parameters: {'learning_rate': 0.11146707253599732, 'min_samples_leaf': 6921, 'l2_regularization': 1.1970482228021407e-08, 'max_features': 0.15553252717821017, 'max_bins': 211, 'interaction_cst': 'pairwise', 'validation_fraction': 0.05362441959916081, 'n_iter_no_change': 21, 'tol': 1.3312056319594048e-06, 'max_depth': 4}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:14:27,573] Trial 16 finished with value: 0.6280496259698366 and parameters: {'learning_rate': 0.12136123008943, 'min_samples_leaf': 730, 'l2_regularization': 1.4836442813558473e-08, 'max_features': 0.13321951920075079, 'max_bins': 217, 'interaction_cst': 'pairwise', 'validation_fraction': 0.05527060387125602, 'n_iter_no_change': 20, 'tol': 9.536460582142999e-07, 'max_depth': 4}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:14:33,313] Trial 17 finished with value: 0.6297683663900007 and parameters: {'learning_rate': 0.08233952996866001, 'min_samples_leaf': 9308, 'l2_regularization': 0.21646106827159106, 'max_features': 0.2887603285680719, 'max_bins': 217, 'interaction_cst': 'pairwise', 'validation_fraction': 0.057367848499662526, 'n_iter_no_change': 19, 'tol': 1.6449060876858528e-07, 'max_depth': 3}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:14:38,669] Trial 18 finished with value: 0.6267125215025432 and parameters: {'learning_rate': 0.172313858457622, 'min_samples_leaf': 14663, 'l2_regularization': 0.415910099286638, 'max_features': 0.06095696893899223, 'max_bins': 219, 'interaction_cst': None, 'validation_fraction': 0.056249304178286025, 'n_iter_no_change': 17, 'tol': 8.602625092613549e-08, 'max_depth': 3}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:15:31,900] Trial 19 finished with value: 0.615184012798466 and parameters: {'learning_rate': 0.05372250287233754, 'min_samples_leaf': 8396, 'l2_regularization': 89316.15058858797, 'max_features': 0.28648813023416453, 'max_bins': 211, 'interaction_cst': 'pairwise', 'validation_fraction': 0.07263603973775105, 'n_iter_no_change': 5, 'tol': 2.879320155136875e-07, 'max_depth': 2}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:15:44,658] Trial 20 finished with value: 0.6237251942358188 and parameters: {'learning_rate': 0.07020115171743503, 'min_samples_leaf': 324, 'l2_regularization': 0.00014235048214091906, 'max_features': 0.12927366496043605, 'max_bins': 233, 'interaction_cst': 'pairwise', 'validation_fraction': 0.05116756015310744, 'n_iter_no_change': 22, 'tol': 1.7134389973291782e-08, 'max_depth': 1}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:15:49,022] Trial 21 finished with value: 0.6277953145426641 and parameters: {'learning_rate': 0.10047331472212762, 'min_samples_leaf': 2515, 'l2_regularization': 0.2901047518504171, 'max_features': 0.3053039651116837, 'max_bins': 173, 'interaction_cst': 'pairwise', 'validation_fraction': 0.04498120008237519, 'n_iter_no_change': 16, 'tol': 2.8040263943179266e-06, 'max_depth': 4}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:15:51,899] Trial 22 finished with value: 0.628010891628838 and parameters: {'learning_rate': 0.1926585517890825, 'min_samples_leaf': 3245, 'l2_regularization': 0.18294615875194295, 'max_features': 0.34874344078729064, 'max_bins': 207, 'interaction_cst': 'pairwise', 'validation_fraction': 0.029163661069284412, 'n_iter_no_change': 22, 'tol': 1.935010196591198e-06, 'max_depth': 3}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:16:02,387] Trial 23 finished with value: 0.627941537986218 and parameters: {'learning_rate': 0.04067404096916973, 'min_samples_leaf': 13906, 'l2_regularization': 6.245511384953048e-07, 'max_features': 0.2591577364784643, 'max_bins': 184, 'interaction_cst': 'pairwise', 'validation_fraction': 0.06689709740668197, 'n_iter_no_change': 18, 'tol': 2.6128762600867504e-07, 'max_depth': 4}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:16:05,733] Trial 24 finished with value: 0.6253796694927342 and parameters: {'learning_rate': 0.08906131543714102, 'min_samples_leaf': 1777, 'l2_regularization': 0.0011986868200012165, 'max_features': 0.30661477426143413, 'max_bins': 159, 'interaction_cst': 'pairwise', 'validation_fraction': 0.05126079727056389, 'n_iter_no_change': 6, 'tol': 2.805358495982332e-07, 'max_depth': 5}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:16:11,400] Trial 25 finished with value: 0.6289066448683606 and parameters: {'learning_rate': 0.15493086457257607, 'min_samples_leaf': 4583, 'l2_regularization': 1.3348551569211763e-07, 'max_features': 0.22359789958707227, 'max_bins': 203, 'interaction_cst': None, 'validation_fraction': 0.03515804702019728, 'n_iter_no_change': 24, 'tol': 1.8737038463898439e-06, 'max_depth': 3}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:16:27,926] Trial 26 finished with value: 0.627400808675933 and parameters: {'learning_rate': 0.07152347634345757, 'min_samples_leaf': 14297, 'l2_regularization': 1296.9967673921483, 'max_features': 0.16043679560211763, 'max_bins': 254, 'interaction_cst': 'pairwise', 'validation_fraction': 0.06267255664482031, 'n_iter_no_change': 32, 'tol': 3.148971013245808e-08, 'max_depth': 4}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:16:35,357] Trial 27 finished with value: 0.6290966951516205 and parameters: {'learning_rate': 0.05252872456629248, 'min_samples_leaf': 1103, 'l2_regularization': 1.7312034858583174, 'max_features': 0.2521518821430556, 'max_bins': 223, 'interaction_cst': 'pairwise', 'validation_fraction': 0.050147779286156755, 'n_iter_no_change': 20, 'tol': 5.931352792202007e-07, 'max_depth': 5}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:16:41,161] Trial 28 finished with value: 0.6227529128389224 and parameters: {'learning_rate': 0.11219836232107878, 'min_samples_leaf': 35999, 'l2_regularization': 0.0006193841856166525, 'max_features': 0.321022316519036, 'max_bins': 233, 'interaction_cst': 'pairwise', 'validation_fraction': 0.05969486967925332, 'n_iter_no_change': 36, 'tol': 4.034159120391438e-06, 'max_depth': 2}. Best is trial 15 with value: 0.6300149365760435.
[I 2026-08-19 13:16:45,615] Trial 29 finished with value: 0.6322828549507572 and parameters: {'learning_rate': 0.2207601579968008, 'min_samples_leaf': 431, 'l2_regularization': 492.25069901566206, 'max_features': 0.3002253827537782, 'max_bins': 200, 'interaction_cst': None, 'validation_fraction': 0.07464085238577813, 'n_iter_no_change': 15, 'tol': 4.0886236471208393e-10, 'max_depth': 6}. Best is trial 29 with value: 0.6322828549507572.
[I 2026-08-19 13:16:50,148] Trial 30 finished with value: 0.6319832054135439 and parameters: {'learning_rate': 0.21923328337960762, 'min_samples_leaf': 270, 'l2_regularization': 672.0223983770298, 'max_features': 0.22949176576140445, 'max_bins': 203, 'interaction_cst': None, 'validation_fraction': 0.09994468579432358, 'n_iter_no_change': 15, 'tol': 1.1531122873634824e-10, 'max_depth': 6}. Best is trial 29 with value: 0.6322828549507572.
[I 2026-08-19 13:16:53,991] Trial 31 finished with value: 0.6310474798775361 and parameters: {'learning_rate': 0.20465061307990845, 'min_samples_leaf': 217, 'l2_regularization': 312.1082939144855, 'max_features': 0.22533722573731005, 'max_bins': 201, 'interaction_cst': None, 'validation_fraction': 0.09914170894954749, 'n_iter_no_change': 15, 'tol': 1.2015696863564917e-10, 'max_depth': 6}. Best is trial 29 with value: 0.6322828549507572.
[I 2026-08-19 13:17:01,467] Trial 32 finished with value: 0.6322973004443287 and parameters: {'learning_rate': 0.24561979433333583, 'min_samples_leaf': 173, 'l2_regularization': 2447.3548576489757, 'max_features': 0.22034048702554415, 'max_bins': 201, 'interaction_cst': None, 'validation_fraction': 0.0987195465389537, 'n_iter_no_change': 14, 'tol': 1.1011640512653346e-10, 'max_depth': 6}. Best is trial 32 with value: 0.6322973004443287.
[I 2026-08-19 13:17:07,227] Trial 33 finished with value: 0.634703620634747 and parameters: {'learning_rate': 0.2158114975072843, 'min_samples_leaf': 185, 'l2_regularization': 718.8748437890337, 'max_features': 0.2160953488876775, 'max_bins': 199, 'interaction_cst': None, 'validation_fraction': 0.09844241887597069, 'n_iter_no_change': 15, 'tol': 2.3658675988459827e-10, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:17:13,875] Trial 34 finished with value: 0.6312366378682046 and parameters: {'learning_rate': 0.2812088491194453, 'min_samples_leaf': 116, 'l2_regularization': 6540.510080127284, 'max_features': 0.2145213907996423, 'max_bins': 170, 'interaction_cst': None, 'validation_fraction': 0.0995007775313653, 'n_iter_no_change': 9, 'tol': 3.863803221968388e-10, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:17:28,969] Trial 35 finished with value: 0.6324316266533327 and parameters: {'learning_rate': 0.14664678259239855, 'min_samples_leaf': 520, 'l2_regularization': 4145.316022475526, 'max_features': 0.17962462468805537, 'max_bins': 189, 'interaction_cst': None, 'validation_fraction': 0.09201042631953567, 'n_iter_no_change': 14, 'tol': 5.606768713804527e-10, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:17:39,230] Trial 36 finished with value: 0.6293847288078038 and parameters: {'learning_rate': 0.1501856524740678, 'min_samples_leaf': 584, 'l2_regularization': 7099.443803238222, 'max_features': 0.18200401163732316, 'max_bins': 158, 'interaction_cst': None, 'validation_fraction': 0.0907699441749434, 'n_iter_no_change': 8, 'tol': 6.527094151617249e-10, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:17:43,114] Trial 37 finished with value: 0.6329961745487332 and parameters: {'learning_rate': 0.14896138050598273, 'min_samples_leaf': 24, 'l2_regularization': 91.82644016093462, 'max_features': 0.18711700437074952, 'max_bins': 191, 'interaction_cst': None, 'validation_fraction': 0.08422734366109921, 'n_iter_no_change': 13, 'tol': 1.2445208250664075e-09, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:18:07,455] Trial 38 finished with value: 0.6326633735282206 and parameters: {'learning_rate': 0.14224345103398406, 'min_samples_leaf': 27, 'l2_regularization': 9504.259142988389, 'max_features': 0.1976164845761588, 'max_bins': 142, 'interaction_cst': None, 'validation_fraction': 0.08443960551439465, 'n_iter_no_change': 13, 'tol': 1.440086887071322e-09, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:18:12,737] Trial 39 finished with value: 0.631523481800933 and parameters: {'learning_rate': 0.13736410537712904, 'min_samples_leaf': 20, 'l2_regularization': 72.09567456197288, 'max_features': 0.19286548876782184, 'max_bins': 145, 'interaction_cst': None, 'validation_fraction': 0.08656535792293486, 'n_iter_no_change': 11, 'tol': 1.455674147228197e-09, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:18:39,124] Trial 40 finished with value: 0.6304396758881409 and parameters: {'learning_rate': 0.17293101563916646, 'min_samples_leaf': 5, 'l2_regularization': 23110.004631206575, 'max_features': 0.1687844014154721, 'max_bins': 133, 'interaction_cst': None, 'validation_fraction': 0.09351761575540476, 'n_iter_no_change': 13, 'tol': 1.7174061827960098e-09, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:18:53,511] Trial 41 finished with value: 0.6321305703485207 and parameters: {'learning_rate': 0.13752079860802519, 'min_samples_leaf': 40, 'l2_regularization': 3910.629748000801, 'max_features': 0.20436656522753194, 'max_bins': 108, 'interaction_cst': None, 'validation_fraction': 0.08347361407185462, 'n_iter_no_change': 14, 'tol': 2.5462608833792835e-10, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:18:55,950] Trial 42 finished with value: 0.6293950504626428 and parameters: {'learning_rate': 0.2695320556503449, 'min_samples_leaf': 95, 'l2_regularization': 41.92359020062082, 'max_features': 0.13954921994505964, 'max_bins': 122, 'interaction_cst': None, 'validation_fraction': 0.09439068318287686, 'n_iter_no_change': 10, 'tol': 9.144369988289398e-10, 'max_depth': 6}. Best is trial 33 with value: 0.634703620634747.
[I 2026-08-19 13:20:22,545] Trial 43 finished with value: 0.6313620009579364 and parameters: {'learning_rate': 0.0031484271793506065, 'min_samples_leaf': 15, 'l2_regularization': 114.61176527318115, 'max_features': 0.17537201040074052, 'max_bins': 177, 'interaction_cst': None, 'validation_fraction': 0.07840571818920304, 'n_iter_no_change': 12, 'tol': 5.103692047727179e-09, 'max_depth': 5}. Best is trial 33 with value: 0.634703620634747.

In [30]:
pd.DataFrame({
    "best auc_val": study_depth_calc.best_value,
    "best gini": 2 * study_depth_calc.best_value - 1,
    "trials": len(study_depth_calc.trials),
    "pruned": len([t for t in study_depth_calc.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_depth_calc.trials if t.state.name == "FAIL"]),
    "best params": study_depth_calc.best_params
})

                     best auc_val  best gini  ...  fail   best params
learning_rate            0.634704   0.269407  ...     0  2.158115e-01
min_samples_leaf         0.634704   0.269407  ...     0  1.850000e+02
l2_regularization        0.634704   0.269407  ...     0  7.188748e+02
max_features             0.634704   0.269407  ...     0  2.160953e-01
max_bins                 0.634704   0.269407  ...     0  1.990000e+02
interaction_cst          0.634704   0.269407  ...     0           NaN
validation_fraction      0.634704   0.269407  ...     0  9.844242e-02
n_iter_no_change         0.634704   0.269407  ...     0  1.500000e+01
tol                      0.634704   0.269407  ...     0  2.365868e-10
max_depth                0.634704   0.269407  ...     0  6.000000e+00

[10 rows x 6 columns]

In [31]:
study_depth_calc.best_params

{'learning_rate': 0.2158114975072843,
 'min_samples_leaf': 185,
 'l2_regularization': 718.8748437890337,
 'max_features': 0.2160953488876775,
 'max_bins': 199,
 'interaction_cst': None,
 'validation_fraction': 0.09844241887597069,
 'n_iter_no_change': 15,
 'tol': 2.3658675988459827e-10,
 'max_depth': 6}

## Depth ohne Calc

In [32]:
def objective_depth_no_calc(trial):

    modell = HistGradientBoostingClassifier(
        **fixed_params_depth,
        **suchraum_params_depth(trial)
    )

    modell.fit(x_train_hgb_no_calc, y_train)

    return roc_auc_score(y_val, modell.predict_proba(x_val_hgb_no_calc)[:, 1])

In [33]:
study_depth_no_calc = optuna.create_study(
    study_name = "HGB_depth_no_calc",
    storage = "sqlite:///HGB_opti.db",
    load_if_exists = True,
    direction = "maximize",
    sampler = TPESampler(seed=RANDOM_STATE),
    pruner = MedianPruner(n_startup_trials=10, n_warmup_steps=500)
)

[I 2026-08-19 13:21:19,066] A new study created in RDB with name: HGB_depth_no_calc

In [34]:
study_depth_no_calc.optimize(
    objective_depth_no_calc,
    n_trials = 50,
    timeout = 4*60*60,
    catch = (Exception, )
)

[I 2026-08-19 13:21:45,955] Trial 0 finished with value: 0.6212898584588418 and parameters: {'learning_rate': 0.01683454924600351, 'min_samples_leaf': 25553, 'l2_regularization': 32.8035800581182, 'max_features': 0.22959754525911097, 'max_bins': 127, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.0641003510568888, 'n_iter_no_change': 30, 'tol': 1.267425589893721e-10, 'max_depth': 6}. Best is trial 0 with value: 0.6212898584588418.
[I 2026-08-19 13:21:49,242] Trial 1 finished with value: 0.6293356607539581 and parameters: {'learning_rate': 0.13867767003062487, 'min_samples_leaf': 31, 'l2_regularization': 2.3105989608604262e-06, 'max_features': 0.10502135295603016, 'max_bins': 150, 'interaction_cst': None, 'validation_fraction': 0.06506676052501416, 'n_iter_no_change': 10, 'tol': 2.888838362365319e-09, 'max_depth': 3}. Best is trial 1 with value: 0.6293356607539581.
[I 2026-08-19 13:22:03,352] Trial 2 finished with value: 0.630655948319442 and parameters: {'learning_rate': 0.02450536768428048, 'min_samples_leaf': 5672, 'l2_regularization': 3.94238621924438e-06, 'max_features': 0.20427033152408347, 'max_bins': 194, 'interaction_cst': 'pairwise', 'validation_fraction': 0.015854643368675158, 'n_iter_no_change': 39, 'tol': 6.732248920775334e-06, 'max_depth': 5}. Best is trial 2 with value: 0.630655948319442.
[I 2026-08-19 13:22:30,586] Trial 3 finished with value: 0.6217099755345429 and parameters: {'learning_rate': 0.012199689940544376, 'min_samples_leaf': 11, 'l2_regularization': 7.852886936532546, 'max_features': 0.1820457481218804, 'max_bins': 122, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.03329019834400153, 'n_iter_no_change': 28, 'tol': 3.618723330959621e-09, 'max_depth': 4}. Best is trial 2 with value: 0.630655948319442.
[I 2026-08-19 13:23:15,274] Trial 4 finished with value: 0.6133016854032435 and parameters: {'learning_rate': 0.037199903510538264, 'min_samples_leaf': 24, 'l2_regularization': 40234.64380902767, 'max_features': 0.28253984700833434, 'max_bins': 246, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.017964325184672756, 'n_iter_no_change': 12, 'tol': 1.6832027985721906e-10, 'max_depth': 2}. Best is trial 2 with value: 0.630655948319442.
[I 2026-08-19 13:23:44,737] Trial 5 finished with value: 0.6242502923484134 and parameters: {'learning_rate': 0.01796701101676289, 'min_samples_leaf': 53, 'l2_regularization': 593.7281208438861, 'max_features': 0.1570259980080768, 'max_bins': 146, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.016709557931179377, 'n_iter_no_change': 40, 'tol': 7.26480307482673e-07, 'max_depth': 2}. Best is trial 2 with value: 0.630655948319442.
[I 2026-08-19 13:24:59,281] Trial 6 finished with value: 0.6185583699669683 and parameters: {'learning_rate': 0.0030772691922556945, 'min_samples_leaf': 7471, 'l2_regularization': 15.457721201756003, 'max_features': 0.26870215041229617, 'max_bins': 221, 'interaction_cst': 'pairwise', 'validation_fraction': 0.08767930832880343, 'n_iter_no_change': 27, 'tol': 4.513257622008936e-09, 'max_depth': 1}. Best is trial 2 with value: 0.630655948319442.
[I 2026-08-19 13:25:33,641] Trial 7 finished with value: 0.6240463432012775 and parameters: {'learning_rate': 0.012562784156701876, 'min_samples_leaf': 87, 'l2_regularization': 30.540793629644874, 'max_features': 0.24126724140656391, 'max_bins': 238, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.07847065437552077, 'n_iter_no_change': 25, 'tol': 7.158728631500194e-07, 'max_depth': 3}. Best is trial 2 with value: 0.630655948319442.
[I 2026-08-19 13:25:41,539] Trial 8 finished with value: 0.6316072286857568 and parameters: {'learning_rate': 0.033310941939163854, 'min_samples_leaf': 220, 'l2_regularization': 2.1401718512509955e-08, 'max_features': 0.08236742809799133, 'max_bins': 108, 'interaction_cst': None, 'validation_fraction': 0.09168098265334837, 'n_iter_no_change': 13, 'tol': 1.1269758643814652e-08, 'max_depth': 5}. Best is trial 8 with value: 0.6316072286857568.
[I 2026-08-19 13:26:01,891] Trial 9 finished with value: 0.6186314455147213 and parameters: {'learning_rate': 0.008604340446309018, 'min_samples_leaf': 9, 'l2_regularization': 5.844789677758518e-05, 'max_features': 0.09836638617620133, 'max_bins': 245, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.0823304869209203, 'n_iter_no_change': 11, 'tol': 2.9026521418263896e-06, 'max_depth': 4}. Best is trial 8 with value: 0.6316072286857568.
[I 2026-08-19 13:26:03,231] Trial 10 finished with value: 0.6248272640113792 and parameters: {'learning_rate': 0.24554140659956822, 'min_samples_leaf': 333, 'l2_regularization': 1.2534734834039077e-08, 'max_features': 0.3296871025735361, 'max_bins': 182, 'interaction_cst': None, 'validation_fraction': 0.042518079679762844, 'n_iter_no_change': 5, 'tol': 5.4675303863547164e-08, 'max_depth': 6}. Best is trial 8 with value: 0.6316072286857568.
[I 2026-08-19 13:26:12,655] Trial 11 finished with value: 0.6304575217399654 and parameters: {'learning_rate': 0.055493794544567765, 'min_samples_leaf': 1234, 'l2_regularization': 0.00022939453595477533, 'max_features': 0.06601442426626078, 'max_bins': 194, 'interaction_cst': 'pairwise', 'validation_fraction': 0.09883283829600645, 'n_iter_no_change': 40, 'tol': 5.6367675593144375e-08, 'max_depth': 5}. Best is trial 8 with value: 0.6316072286857568.
[I 2026-08-19 13:26:19,026] Trial 12 finished with value: 0.629749178079953 and parameters: {'learning_rate': 0.04905210146583551, 'min_samples_leaf': 2377, 'l2_regularization': 1.7998196807046904e-08, 'max_features': 0.1632482856156553, 'max_bins': 108, 'interaction_cst': 'pairwise', 'validation_fraction': 0.04793404566344977, 'n_iter_no_change': 21, 'tol': 7.887577413194241e-06, 'max_depth': 5}. Best is trial 8 with value: 0.6316072286857568.
[I 2026-08-19 13:26:22,544] Trial 13 finished with value: 0.6315940653603679 and parameters: {'learning_rate': 0.08688481071804603, 'min_samples_leaf': 368, 'l2_regularization': 0.004498254932680299, 'max_features': 0.3471805600806288, 'max_bins': 179, 'interaction_cst': None, 'validation_fraction': 0.05987657928205367, 'n_iter_no_change': 18, 'tol': 1.0089309882791848e-07, 'max_depth': 5}. Best is trial 8 with value: 0.6316072286857568.
[I 2026-08-19 13:26:27,081] Trial 14 finished with value: 0.6342409548681864 and parameters: {'learning_rate': 0.10118854084445855, 'min_samples_leaf': 285, 'l2_regularization': 0.020371947606485814, 'max_features': 0.34591598719331107, 'max_bins': 161, 'interaction_cst': None, 'validation_fraction': 0.06306386516611832, 'n_iter_no_change': 18, 'tol': 3.089069228882131e-08, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:26:29,267] Trial 15 finished with value: 0.6298316709319458 and parameters: {'learning_rate': 0.12637057750692324, 'min_samples_leaf': 256, 'l2_regularization': 0.03482419383306384, 'max_features': 0.30531087104731336, 'max_bins': 155, 'interaction_cst': None, 'validation_fraction': 0.0980836657132757, 'n_iter_no_change': 16, 'tol': 1.1350376627541223e-08, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:26:30,710] Trial 16 finished with value: 0.6244436425065264 and parameters: {'learning_rate': 0.28390843242674896, 'min_samples_leaf': 128, 'l2_regularization': 0.1567410891541737, 'max_features': 0.1275708505571809, 'max_bins': 105, 'interaction_cst': None, 'validation_fraction': 0.07185260188789533, 'n_iter_no_change': 6, 'tol': 6.976358547240415e-10, 'max_depth': 3}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:26:35,736] Trial 17 finished with value: 0.6316136515846791 and parameters: {'learning_rate': 0.08976372605929342, 'min_samples_leaf': 958, 'l2_regularization': 2.6337683989379286e-07, 'max_features': 0.07008991674013271, 'max_bins': 165, 'interaction_cst': None, 'validation_fraction': 0.09001323524656743, 'n_iter_no_change': 16, 'tol': 1.8383294579853736e-07, 'max_depth': 6}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:26:39,135] Trial 18 finished with value: 0.6322092769860048 and parameters: {'learning_rate': 0.08367663931665299, 'min_samples_leaf': 1049, 'l2_regularization': 0.0008570127998766416, 'max_features': 0.12728394974935964, 'max_bins': 169, 'interaction_cst': None, 'validation_fraction': 0.05209096330879708, 'n_iter_no_change': 22, 'tol': 2.422546522519087e-07, 'max_depth': 6}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:26:42,572] Trial 19 finished with value: 0.6293226702600174 and parameters: {'learning_rate': 0.15732658497251278, 'min_samples_leaf': 851, 'l2_regularization': 0.001029315794866295, 'max_features': 0.1306622045960869, 'max_bins': 207, 'interaction_cst': None, 'validation_fraction': 0.051169972645461796, 'n_iter_no_change': 32, 'tol': 3.833499244521206e-07, 'max_depth': 6}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:26:49,043] Trial 20 finished with value: 0.6321887703337504 and parameters: {'learning_rate': 0.07020115171743503, 'min_samples_leaf': 2689, 'l2_regularization': 0.1258813603032034, 'max_features': 0.05026629161270149, 'max_bins': 169, 'interaction_cst': None, 'validation_fraction': 0.039200291337037174, 'n_iter_no_change': 21, 'tol': 2.1482451271946934e-08, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:26:53,530] Trial 21 finished with value: 0.6296430434936288 and parameters: {'learning_rate': 0.07750948421790581, 'min_samples_leaf': 4690, 'l2_regularization': 0.17377363576140198, 'max_features': 0.062207956665912015, 'max_bins': 168, 'interaction_cst': None, 'validation_fraction': 0.031662334532562224, 'n_iter_no_change': 21, 'tol': 1.624474099083771e-08, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:03,853] Trial 22 finished with value: 0.6308329839927452 and parameters: {'learning_rate': 0.0661332359569998, 'min_samples_leaf': 13437, 'l2_regularization': 0.012165363058808734, 'max_features': 0.05068637665090361, 'max_bins': 138, 'interaction_cst': None, 'validation_fraction': 0.055293634888802, 'n_iter_no_change': 23, 'tol': 2.549678429245178e-08, 'max_depth': 3}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:06,575] Trial 23 finished with value: 0.6309151151044984 and parameters: {'learning_rate': 0.19653121221731853, 'min_samples_leaf': 1895, 'l2_regularization': 0.9508472709235438, 'max_features': 0.13094056536242393, 'max_bins': 171, 'interaction_cst': None, 'validation_fraction': 0.03968125623387415, 'n_iter_no_change': 19, 'tol': 2.4891769867536186e-07, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:10,095] Trial 24 finished with value: 0.6322212385299304 and parameters: {'learning_rate': 0.09922621100736329, 'min_samples_leaf': 718, 'l2_regularization': 4.706297402865151e-05, 'max_features': 0.20693579838229326, 'max_bins': 190, 'interaction_cst': None, 'validation_fraction': 0.026874253164600154, 'n_iter_no_change': 33, 'tol': 5.906538210270154e-08, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:12,526] Trial 25 finished with value: 0.6304173123026562 and parameters: {'learning_rate': 0.12277765547043776, 'min_samples_leaf': 556, 'l2_regularization': 3.0864883422561776e-05, 'max_features': 0.21761864021095978, 'max_bins': 207, 'interaction_cst': None, 'validation_fraction': 0.026776310279287147, 'n_iter_no_change': 35, 'tol': 2.036207647109221e-06, 'max_depth': 6}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:19,065] Trial 26 finished with value: 0.6315120588480307 and parameters: {'learning_rate': 0.040776086844446335, 'min_samples_leaf': 135, 'l2_regularization': 0.00047592944234141967, 'max_features': 0.25736686311392465, 'max_bins': 187, 'interaction_cst': None, 'validation_fraction': 0.07126686603181989, 'n_iter_no_change': 25, 'tol': 1.1175307676806816e-07, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:22,876] Trial 27 finished with value: 0.6330978476721014 and parameters: {'learning_rate': 0.10176716667537379, 'min_samples_leaf': 637, 'l2_regularization': 2.6249110133859357e-05, 'max_features': 0.3053389452718494, 'max_bins': 157, 'interaction_cst': None, 'validation_fraction': 0.01017787688405028, 'n_iter_no_change': 33, 'tol': 5.986619360742473e-08, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:26,080] Trial 28 finished with value: 0.6325385811842004 and parameters: {'learning_rate': 0.1693636833048164, 'min_samples_leaf': 509, 'l2_regularization': 1.3381744911850385e-05, 'max_features': 0.3115156165156874, 'max_bins': 136, 'interaction_cst': None, 'validation_fraction': 0.010770918334875493, 'n_iter_no_change': 35, 'tol': 4.682392584843151e-08, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:29,090] Trial 29 finished with value: 0.6314551128956319 and parameters: {'learning_rate': 0.17443918054822025, 'min_samples_leaf': 181, 'l2_regularization': 1.6085862736823736e-06, 'max_features': 0.3084716622834852, 'max_bins': 129, 'interaction_cst': 'pairwise', 'validation_fraction': 0.010020597336091144, 'n_iter_no_change': 36, 'tol': 1.2857924968765823e-09, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:31,939] Trial 30 finished with value: 0.6327043546780413 and parameters: {'learning_rate': 0.21923328337960762, 'min_samples_leaf': 456, 'l2_regularization': 5.695143147685679e-07, 'max_features': 0.3015598135568042, 'max_bins': 136, 'interaction_cst': None, 'validation_fraction': 0.010412533373073268, 'n_iter_no_change': 30, 'tol': 5.64045990948152e-09, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:34,850] Trial 31 finished with value: 0.6306967767344949 and parameters: {'learning_rate': 0.20538399036303068, 'min_samples_leaf': 461, 'l2_regularization': 1.8243930428049348e-07, 'max_features': 0.3046513008259017, 'max_bins': 134, 'interaction_cst': None, 'validation_fraction': 0.010972148013260597, 'n_iter_no_change': 30, 'tol': 5.787689136564912e-09, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:40,185] Trial 32 finished with value: 0.6272840228492177 and parameters: {'learning_rate': 0.1161658349072649, 'min_samples_leaf': 37179, 'l2_regularization': 1.0579004556415078e-05, 'max_features': 0.3327149214621972, 'max_bins': 155, 'interaction_cst': None, 'validation_fraction': 0.022808741793345216, 'n_iter_no_change': 37, 'tol': 1.5674378566974426e-09, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:42,796] Trial 33 finished with value: 0.6323969237063387 and parameters: {'learning_rate': 0.2977504062989052, 'min_samples_leaf': 503, 'l2_regularization': 3.875555332547149e-07, 'max_features': 0.2863277199730784, 'max_bins': 118, 'interaction_cst': None, 'validation_fraction': 0.02053162654100886, 'n_iter_no_change': 33, 'tol': 2.8636683128201092e-08, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:44,870] Trial 34 finished with value: 0.6326365283830998 and parameters: {'learning_rate': 0.1529234057904223, 'min_samples_leaf': 98, 'l2_regularization': 1.3716720695434804e-06, 'max_features': 0.3495055324405246, 'max_bins': 142, 'interaction_cst': None, 'validation_fraction': 0.01177415431414411, 'n_iter_no_change': 30, 'tol': 9.155499411850046e-09, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:46,687] Trial 35 finished with value: 0.6248168941245081 and parameters: {'learning_rate': 0.21863001156567122, 'min_samples_leaf': 45, 'l2_regularization': 2.3539447646939675e-06, 'max_features': 0.34820149605427564, 'max_bins': 146, 'interaction_cst': None, 'validation_fraction': 0.025245819895505665, 'n_iter_no_change': 28, 'tol': 3.4385035065025466e-10, 'max_depth': 6}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:51,920] Trial 36 finished with value: 0.6257963540554944 and parameters: {'learning_rate': 0.13051970293685197, 'min_samples_leaf': 18, 'l2_regularization': 368.78490633442374, 'max_features': 0.3275232052576235, 'max_bins': 158, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.015597824299746557, 'n_iter_no_change': 30, 'tol': 8.39035134585276e-09, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:55,318] Trial 37 finished with value: 0.6322920994235492 and parameters: {'learning_rate': 0.10194413485832544, 'min_samples_leaf': 47, 'l2_regularization': 1.3936295393575104e-07, 'max_features': 0.286004350388942, 'max_bins': 121, 'interaction_cst': None, 'validation_fraction': 0.03191136687642405, 'n_iter_no_change': 30, 'tol': 2.219498440228118e-09, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:27:59,505] Trial 38 finished with value: 0.6306785008137186 and parameters: {'learning_rate': 0.1557281954887317, 'min_samples_leaf': 71, 'l2_regularization': 8.379419515836888e-07, 'max_features': 0.2606952933634683, 'max_bins': 141, 'interaction_cst': 'pairwise', 'validation_fraction': 0.015247243951562794, 'n_iter_no_change': 26, 'tol': 3.814772549001517e-09, 'max_depth': 2}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:28:12,677] Trial 39 finished with value: 0.6252281887576969 and parameters: {'learning_rate': 0.05594376528776429, 'min_samples_leaf': 106, 'l2_regularization': 7.078334198531151e-08, 'max_features': 0.3289063258838978, 'max_bins': 148, 'interaction_cst': 'no_interactions', 'validation_fraction': 0.019323524528985087, 'n_iter_no_change': 38, 'tol': 6.996129985434352e-09, 'max_depth': 3}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:29:06,982] Trial 40 finished with value: 0.6319129634976686 and parameters: {'learning_rate': 0.0033321244843162456, 'min_samples_leaf': 6, 'l2_regularization': 6.050478246145001e-06, 'max_features': 0.27597528590439635, 'max_bins': 159, 'interaction_cst': None, 'validation_fraction': 0.06654087824163585, 'n_iter_no_change': 24, 'tol': 1.0377622674967574e-09, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:29:11,412] Trial 41 finished with value: 0.6324376315413115 and parameters: {'learning_rate': 0.16487629960452344, 'min_samples_leaf': 213, 'l2_regularization': 9.16611641370464e-06, 'max_features': 0.3165861395534729, 'max_bins': 128, 'interaction_cst': None, 'validation_fraction': 0.010961271902394164, 'n_iter_no_change': 35, 'tol': 3.151425244782452e-08, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:29:13,960] Trial 42 finished with value: 0.6323279920939983 and parameters: {'learning_rate': 0.22513626054321548, 'min_samples_leaf': 1380, 'l2_regularization': 0.00012181587021659758, 'max_features': 0.2971800716292355, 'max_bins': 136, 'interaction_cst': None, 'validation_fraction': 0.014798057528129877, 'n_iter_no_change': 32, 'tol': 4.5951195372625885e-08, 'max_depth': 5}. Best is trial 14 with value: 0.6342409548681864.
[I 2026-08-19 13:29:17,014] Trial 43 finished with value: 0.6316128236014639 and parameters: {'learning_rate': 0.14485447646434066, 'min_samples_leaf': 337, 'l2_regularization': 1.295664931688731e-05, 'max_features': 0.31939988633189254, 'max_bins': 116, 'interaction_cst': None, 'validation_fraction': 0.021038841687367853, 'n_iter_no_change': 28, 'tol': 1.3917827978617398e-08, 'max_depth': 4}. Best is trial 14 with value: 0.6342409548681864.

In [35]:
pd.DataFrame({
    "best auc_val": study_depth_no_calc.best_value,
    "best gini": 2 * study_depth_no_calc.best_value - 1,
    "trials": len(study_depth_no_calc.trials),
    "pruned": len([t for t in study_depth_no_calc.trials if t.state.name == "PRUNED"]),
    "fail": len([t for t in study_depth_no_calc.trials if t.state.name == "FAIL"]),
    "best params": study_depth_no_calc.best_params
})

                     best auc_val  best gini  ...  fail   best params
learning_rate            0.634533   0.269067  ...     0  2.468715e-02
min_samples_leaf         0.634533   0.269067  ...     0  1.650000e+02
l2_regularization        0.634533   0.269067  ...     0  4.711124e-03
max_features             0.634533   0.269067  ...     0  2.469807e-01
max_bins                 0.634533   0.269067  ...     0  1.440000e+02
interaction_cst          0.634533   0.269067  ...     0           NaN
validation_fraction      0.634533   0.269067  ...     0  1.482309e-02
n_iter_no_change         0.634533   0.269067  ...     0  3.400000e+01
tol                      0.634533   0.269067  ...     0  8.370655e-08
max_depth                0.634533   0.269067  ...     0  6.000000e+00

[10 rows x 6 columns]

In [36]:
study_depth_no_calc.best_params

{'learning_rate': 0.024687148414834312,
 'min_samples_leaf': 165,
 'l2_regularization': 0.004711123505991509,
 'max_features': 0.2469806711366302,
 'max_bins': 144,
 'interaction_cst': None,
 'validation_fraction': 0.014823091721617599,
 'n_iter_no_change': 34,
 'tol': 8.37065478390795e-08,
 'max_depth': 6}

## Load Study

In [37]:
study_leaf_calc_loaded = optuna.load_study(
    study_name = "HGB_leaf_calc",
    storage = "sqlite:///HGB_opti.db"
)

In [38]:
study_leaf_no_calc_loaded = optuna.load_study(
    study_name = "HGB_leaf_no_calc",
    storage = "sqlite:///HGB_opti.db"
)

In [39]:
study_depth_calc_loaded = optuna.load_study(
    study_name = "HGB_depth_calc",
    storage = "sqlite:///HGB_opti.db"
)

In [40]:
study_depth_no_calc_loaded = optuna.load_study(
    study_name = "HGB_depth_no_calc",
    storage = "sqlite:///HGB_opti.db"
)

## Best Params again

In [41]:
study_leaf_calc_loaded.best_params

{'learning_rate': 0.014521736210156313,
 'min_samples_leaf': 5975,
 'l2_regularization': 10.262130162526471,
 'max_features': 0.24775997297590835,
 'max_bins': 231,
 'interaction_cst': None,
 'validation_fraction': 0.0573133556070173,
 'n_iter_no_change': 38,
 'tol': 1.2095870910048285e-08,
 'max_leaf_nodes': 36}

In [42]:
study_leaf_no_calc_loaded.best_params

{'learning_rate': 0.004108690179427848,
 'min_samples_leaf': 6833,
 'l2_regularization': 52.45818863330329,
 'max_features': 0.2966869253501312,
 'max_bins': 202,
 'interaction_cst': None,
 'validation_fraction': 0.01391561653087682,
 'n_iter_no_change': 40,
 'tol': 1.4783911269827303e-06,
 'max_leaf_nodes': 32}

In [43]:
study_depth_calc_loaded.best_params

{'learning_rate': 0.2158114975072843,
 'min_samples_leaf': 185,
 'l2_regularization': 718.8748437890337,
 'max_features': 0.2160953488876775,
 'max_bins': 199,
 'interaction_cst': None,
 'validation_fraction': 0.09844241887597069,
 'n_iter_no_change': 15,
 'tol': 2.3658675988459827e-10,
 'max_depth': 6}

In [44]:
study_depth_no_calc_loaded.best_params

{'learning_rate': 0.024687148414834312,
 'min_samples_leaf': 165,
 'l2_regularization': 0.004711123505991509,
 'max_features': 0.2469806711366302,
 'max_bins': 144,
 'interaction_cst': None,
 'validation_fraction': 0.014823091721617599,
 'n_iter_no_change': 34,
 'tol': 8.37065478390795e-08,
 'max_depth': 6}

## 100% Train

In [45]:
results = []
train_times = {}

In [46]:
name = "L_hgb_opt_01"

L_hgb_opt_01 = HistGradientBoostingClassifier(
    **fixed_params_leaf,
    **study_leaf_calc_loaded.best_params
)

start = time.time()
L_hgb_opt_01.fit(
    x_train_hgb, y_train
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_hgb_opt_01, x_train_hgb, y_train, x_val_hgb, y_val, train_times[name], best_iter=L_hgb_opt_01.n_iter_)
)

In [47]:
name = "L_hgb_opt_02"

L_hgb_opt_02 = HistGradientBoostingClassifier(
    **fixed_params_leaf,
    **study_leaf_no_calc_loaded.best_params
)

start = time.time()
L_hgb_opt_02.fit(
    x_train_hgb_no_calc, y_train
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_hgb_opt_02, x_train_hgb_no_calc, y_train, x_val_hgb_no_calc, y_val, train_times[name], best_iter=L_hgb_opt_02.n_iter_)
)

In [48]:
name = "L_hgb_opt_03"

L_hgb_opt_03 = HistGradientBoostingClassifier(
    **fixed_params_depth,
    **study_depth_calc_loaded.best_params
)

start = time.time()
L_hgb_opt_03.fit(
    x_train_hgb, y_train
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_hgb_opt_03, x_train_hgb, y_train, x_val_hgb, y_val, train_times[name], best_iter=L_hgb_opt_03.n_iter_)
)

In [49]:
name = "L_hgb_opt_04"

L_hgb_opt_04 = HistGradientBoostingClassifier(
    **fixed_params_depth,
    **study_depth_no_calc_loaded.best_params
)

start = time.time()
L_hgb_opt_04.fit(
    x_train_hgb_no_calc, y_train
)
train_times[name] = time.time()- start

results.append(
    eval_modell(name, L_hgb_opt_04, x_train_hgb_no_calc, y_train, x_val_hgb_no_calc, y_val, train_times[name], best_iter=L_hgb_opt_04.n_iter_)
)

In [50]:
pd.DataFrame(results)

      model_idx  auc_train   auc_val  ...  delta_auc  best_iter  trainingszeit
0  L_hgb_opt_01   0.691162  0.636600  ...   0.054562        669      32.303958
1  L_hgb_opt_02   0.679824  0.638318  ...   0.041506       2469      85.016068
2  L_hgb_opt_03   0.683218  0.634704  ...   0.048514        126       5.613486
3  L_hgb_opt_04   0.696819  0.634533  ...   0.062285        365      11.549956

[4 rows x 7 columns]

## Save Models

In [51]:
Modelle = [
    (L_hgb_opt_01, "L_hgb_opt_01"),
    (L_hgb_opt_02, "L_hgb_opt_02"),
    (L_hgb_opt_03, "L_hgb_opt_03"),
    (L_hgb_opt_04, "L_hgb_opt_04")
]

for modell, name in Modelle:
    joblib.dump(modell, f"{name}.joblib")

joblib.dump(targ_enc, "L_hgb_targ_enc.joblib")

['L_hgb_targ_enc.joblib']

## Notizen
- Ich habe bis jetzt noch nichts zum pruning für HGB gefunden: Mines Verständnisses nach ist die Pruner implementation wie XGBPruner eine Schnittstelle durch die während des trainings gepruned werden kann. Ich setze den Median Pruner trotzdem, aber mMn wird dieser einfach keinen Effekt haben.
- J_D hatte erwähnt entweder max_depth oder max_leaf_nodes zu setzen, ich behandle es wie plain und ordered als händische versuchsreihe
- ich muss über joblib speichern
- da jd etwas anders als ich target encoded speichere ich den target encoder von hier auch mal

## Ressourcen [Abrufdatum: 19.08.2026]:
- https://www.kaggle.com/code/adrienriaux/histgradientboosting-with-optuna
- https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html
- https://sklearngeneticopt.rodrigo-arenas.com/versions/latest/tutorials/tune-gradient-boosting
- https://www.cosmiclearn.com/scikitlearn/joblib.php
- https://www.geeksforgeeks.org/machine-learning/saving-a-machine-learning-model/
- https://www.simplified.guide/scikit-learn/model-persist-joblib